### ISSUE TITLE
[REQ] Support of Kingsmith WR1 rowing device

### ISSUE THREAD

**Issue by Carael** [cagnulein/qdomyos-zwift#1118]
Hi Roberto,

Please add support for the Kingsmith WR1 water rower machine.

following the guide I've created the Bluetooth [bt dump log](https://github.com/cagnulein/qdomyos-zwift/files/10342520/bt.zip) on my Android device (Samsung S9+).

Steps I did:
1. Opened the app
2. Woke up the rower
3. Pair the rower
4. Started a training and rowed constantly for 2minutes at about 20 stroke rate
5. Finnished the training
6. Closed app and created report

If you need any additional logs I'm happy to help.

**Comment by cagnulein** [comment]
great! i will add this in the next days!

**Comment by cagnulein** [comment]
done @Carael ! i'm sending the version today!

**Comment by Carael** [comment]
Updated app detects the rower but crashes right afterwards. Debug log:
[debug-Wed_Jan_4_15_38_41_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/10344991/debug-Wed_Jan_4_15_38_41_2023.log)

**Comment by cagnulein** [comment]
found the issue @Carael 
i will send you another one later today!

**Comment by cagnulein** [comment]
@Carael version online in an hour or so!

**Comment by Carael** [comment]
@cagnulein Is the new version already online on Android beta channel? I've tested right now and it's still crashing - version 2.12.36 (don't know if that's already the updated version or not because of the autoupdate).

**Comment by cagnulein** [comment]
it's the version 2.12.37
google is reviewing it, usually takes an hour

**Comment by Carael** [comment]
I confirm it works. Tested on both Android and Ios version of the app in latest beta. Good work, thanks!

**Comment by cagnulein** [comment]
Yeah! Thanks for the feedback!

**Comment by Carael** [comment]
@cagnulein I did some testing. The only thing I noticed is that the current SPM value in the app is divided by 2 compared to the value of the rower monitor. So in the app I see 10 and on the monitor 20. Is this a feature or a bug:)? I'm new in rowing and not sure which one is correct.

**Comment by cagnulein** [comment]
i never used a rower so I can't help @Carael but i see in the code of the rowers that i already managed the possibility to multiply x2 the cadence for the WHIPR for example. Which value do you see usually? Maybe @jonathancolledge can help us on this.

**Comment by Carael** [comment]
Today I rowed with steady 20 SPM (showed on rower monitor) and in the app I saw exactly 10. With any change it was always consistant. Maybe an option in the advance section of the app to multiply cadence? I guess that would make more sense and will be more future proof than adding it per rower?

**Comment by cagnulein** [comment]
i prefer to keep the settings releated to the equipment when it's possible in order to keep the number of settings as minimum :)
So i'm adding your rower to the the list of the cadence x2. I'm sending you a new beta today

**Comment by Carael** [comment]
Nice, thanks! Will retest tomorrow and confirm.

**Comment by cagnulein** [comment]
i'm uploading it, version 2.12.40

**Comment by Carael** [comment]
On ios I’m still on the previous beta I recieved (2.12.37). I recieved no update to 2.12.40 yet.

**Comment by cagnulein** [comment]
@Carael yes i didn't build yet, very crazy days. tomorrow i will do, i promise

**Comment by Carael** [comment]
No problem:)

**Comment by Carael** [comment]
I've recieved the beta, tested and now the cadence is correct. Thanks for the quick fix!

**Comment by Carael** [comment]
@cagnulein I think I found one more thing. During the workout the pace (m/500m) displayed is only the current pace. The max and average is always zero. Could you please fix the average and max? 

![IMG_2853](https://user-images.githubusercontent.com/6861396/212474787-ce564121-8c07-4813-9ebf-266a068cdef1.PNG)

Also would it be possible to add the pace metric by lap? For rowing it's more important to see the average of m/500m than the current since the current pace changes too much. Thanks in advance!

**Comment by cagnulein** [comment]
ok i will check this in the next days!

**Comment by cagnulein** [comment]
@Carael hello, I fixed the pace issue. About the avg lap pace. So you're asking to:
- add a setting to auto lap every 500m for rowers?
or
- add a tile to show the avg pace of the last 500m?

let me know

**Comment by Carael** [comment]
@cagnulein Thanks!

The second option would be perfect. With the initial pace field all needed metrics will be there: 
- the first tile with current, average over whole, max 
- the second new tile with average pace of last 500ma

**Comment by cagnulein** [comment]
ok i will do in the next days. i'm starting a new ticket for this!
