### ISSUE TITLE
[BUG]QZ (qdomyos-zwift) not working with QZ Companion on Nordictrack Commercial S15i Studio Bike

### ISSUE THREAD

**Issue by ggaggo** [cagnulein/qdomyos-zwift#1676]
I installed QZ Companion on a Nordictrack Commercial S15i Studio Bike (Android 7.0) according to instructions, as well as QZ - qdomyos-zwift from Apple Store on my iPhone 13mini (iOS v. 16.6.1). 
Activating BT on Nordictrack and pairing with QZ - qdomyos-zwift works. Also, I can ping Nordictrack bike's IP 192.168.0.9
However, no transmission of data sent to QZ on iPhone (not shown at least in dashboard). I tried with selected bike "S221 Bike" as well as with "Other" in QZ Companion, none of both works.
What could be the mistake I make or what extra configuration in the settings of the Bike or the QZ iPhone App could help?
thanks for any help.

attached the log file of my last try yesterday.

[debug-Di__Sept__26_22_29_00_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/12740058/debug-Di__Sept__26_22_29_00_2023.log)

**Comment by ggaggo** [comment]
BTW: I also bought QZ - qdomyos-zwift in the Google Play Store and installed it on my Android Phone. Didn't work either.

**Comment by cagnulein** [comment]
try to use the c1750 treadmill device in the companion and restart the
tablet. let me know

Il giorno mer 27 set 2023 alle 16:52 ggaggo ***@***.***> ha
scritto:

**Comment by cagnulein** [comment]
did you see my previous message? let me know

Il giorno mer 27 set 2023 alle 16:53 ggaggo ***@***.***> ha
scritto:

**Comment by ggaggo** [comment]
Hi Roberto

Appreciating your quick response. Unfortunately, I only this evening had a chance to follow up the issue.

So, I first went back in system settings to verify USB debugging is on, and BT is on, and WiFi is on.

Then re-installed QZ Companion using the install package resp. QZ-Companion.bat. this worked fine, i.e ping IP address is ok (min. 5ms / max 60ms).

Then started QZ Companion on NordicTrack Bike S15i and selecting a few different treadmills for different trials.

Then re-installed QZ on iPhone and configured it according to instructions.

Then starting iFit and manually training.

Then starting QZ on iPhone, closing it after each trial resp. before changing selection of another treadmill in QZ Companion.

QZ dows not connect to Nordictrack and does not show data on dashboard. I’m desperate since I have no clue what I’m doing wrong.

So, in the diff. log files attached, you should see different treadmill selections. Btw. I checked ping of the IP between trials to assure it’s still working. Ping from iPhone ok.

I hope to helping you finding the bug or the error I commit in the settings or of the bike or the apps.

Have a nice weekend and 1000 thx in advance for your commitment

Best

Hannes

**Comment by cagnulein** [comment]
hi @ggaggo i can't see the files because you have to upload them from the web interface of github directly. thanks

**Comment by ggaggo** [comment]
[debug-Fr__Sept__29_17_49_34_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/12775193/debug-Fr__Sept__29_17_49_34_2023.log)
[debug-Fr__Sept__29_17_50_25_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/12775194/debug-Fr__Sept__29_17_50_25_2023.log)
[debug-Fr__Sept__29_17_52_10_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/12775195/debug-Fr__Sept__29_17_52_10_2023.log)
[debug-Fr__Sept__29_17_52_53_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/12775197/debug-Fr__Sept__29_17_52_53_2023.log)
[debug-Fr__Sept__29_17_53_38_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/12775198/debug-Fr__Sept__29_17_53_38_2023.log)
[debug-Fr__Sept__29_17_54_19_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/12775199/debug-Fr__Sept__29_17_54_19_2023.log)
[debug-Fr__Sept__29_17_55_00_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/12775200/debug-Fr__Sept__29_17_55_00_2023.log)

**Comment by cagnulein** [comment]
good news is that i can see a communication from the bike. can you set the c1750 device in the companion  and try again?
thanks

**Comment by ggaggo** [comment]
Ciao Roberto
grazie mille for your quick reply. I did as you said and set the c1750 device in the companion and restarted the bike. nothing. I attache the logs.
[debug-Sa__Sept__30_12_07_56_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/12775321/debug-Sa__Sept__30_12_07_56_2023.log)
[debug-Sa__Sept__30_12_09_20_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/12775322/debug-Sa__Sept__30_12_09_20_2023.log)

**Comment by cagnulein** [comment]
Ok, I'll check it out tomorrow! have a nice saturday night

Il giorno sab 30 set 2023 alle 20:32 ggaggo ***@***.***> ha
scritto:

**Comment by cagnulein** [comment]
i did a quick look! good news i can see the tile, must be a stupid issue.
could i send you the beta to check if i already fixed it? send me a email
to ***@***.*** indicating this ticket and i will send you it!
Let me know

Il giorno sab 30 set 2023 alle 20:36 cagnulein ***@***.***> ha
scritto:

**Comment by ggaggo** [comment]
Dear Roberto
sure, send me the beta (I'll confirm by mail)
attached some sren prints: I installed Rouvy on the same device as the QZ Companion runs (Nordictrack Android), and connected with the QZ on the iPhone by bluetooth, and the Wahoo thing works fine bridging to the device. However, as the problem persists, no data is transferred and Rouvy does logically not start the workout because it does not receive the pedal signal.
![IMG-2](https://github.com/cagnulein/qdomyos-zwift/assets/10462019/c6e82f9e-1ebc-4f3a-b8fe-964a08cffa27)
![IMG-4](https://github.com/cagnulein/qdomyos-zwift/assets/10462019/c1a92182-9792-4fa1-b17a-cf96e0cf86c8)
![IMG-1](https://github.com/cagnulein/qdomyos-zwift/assets/10462019/7d6a031c-1fa9-4529-9bfe-3aa6e13e3cd9)
![IMG-3](https://github.com/cagnulein/qdomyos-zwift/assets/10462019/f3417709-7c54-4d8e-a64a-1b372e546350)

**Comment by ggaggo** [comment]
Ciao Roberto
yes please, send me the beta version, I'll try it.

btw
Sono di Basilea, Svizzera, ma al momento lavoro in Tegucigalpa, Honduras. abbiamo un fuso orario di 8 ore. qui sono solo le 12:24. ho comprato la nordictrack qui ed è l'unica smartbike decente disponibile nel paese. non posso importar altra, troppo complicato. e andare in bici fuori è impossibile, troppo pericoloso.

saludos
Hannes

***************************************************

Hannes Herrmann, St. Alban-Rheinweg 116, CH-4052 Basel

Zur Zeit im Ausland in Tegucigalpa/Honduras im Auftrag
der Schweizerischen Entwicklungszusammenarbeit (DEZA)

Phones:+41 58 282 01 52 (skype for business)
Phones:+504 9458 5125 (cell phone Honduras)

Emails: ***@***.***
Emails: ***@***.***

***@***.***

Sicher versendet mit [Proton Mail](https://proton.me/).

------- Original Message -------
Roberto Viola ***@***.***> schrieb am Samstag, 30. September 2023 um 12:41:

**Comment by cagnulein** [comment]
scusami mandami la mail a roberto.viola83@gmail.com altrimenti github nasconde l'account

**Comment by cagnulein** [comment]
got the issue, you have the "nordictrack_2950_ip" configured too! Please blank it, press ok and restart QZ. Let me know!

**Comment by ggaggo** [comment]
Ciao Roberto
If I blank IP, QZ does not show tiles anymore, so seams not to connect to Nordoctrack

Buen domingo
Saluti
Hannes

**Comment by cagnulein** [comment]
Hi, you have to set this instead 
it was in the last log that you sent me

let me know 

![image](https://github.com/cagnulein/qdomyos-zwift/assets/48216/4761114c-0c4b-40d6-a3bd-508cc3cba83f)

**Comment by cagnulein** [comment]
ok let me check tomorrow, don't worry it will work :)

Il giorno lun 2 ott 2023 alle 17:37 georges gaggo ***@***.***>
ha scritto:

**Comment by cagnulein** [comment]
@ggaggo the issue on your log is that you set also the tdf4 setting with the ip! don't! only the tdf companion ip must be set
blank it, press ok and restart qz
let me know

**Comment by cagnulein** [comment]
@ggaggo hah ok you enabled it later thinking that could fix the issue. no, leave it blank.

in the first log where you have only the right one setting, i see the messages from the bike but with only changing resistance. did you start a manual workout on the bike?

**Comment by cagnulein** [comment]
@ggaggo any news?

**Comment by ggaggo** [comment]
Hi Roberto
This weekend, I gave it another try and attach the logs. 
1. The first log is only a try with my Garmin Fenix and the QZ Garmin App, having the iPhone running QZ connected to iPad running Zwift. Nothing worked, i.e. no data in the tiles, iPad did not recognize Wahoo.
2. The second log then is another try with the Nordictrack s15i, what did not work out either.

I hope you'll find a bug to fix that and make it work. Thanks in advance for your commitment.

[debug-Fr__Okt__6_15_33_17_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/12848507/debug-Fr__Okt__6_15_33_17_2023.log)
[debug-Fr__Okt__6_19_46_08_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/12848508/debug-Fr__Okt__6_19_46_08_2023.log)

**Comment by cagnulein** [comment]
ok @ggaggo i guess you have one of the consoles with the blocked ifit version.

good news is I already developed something to unlock it

check this https://github.com/cagnulein/qdomyos-zwift/issues/1591#issuecomment-1664105559

and let me know if you can follow it

**Comment by cagnulein** [comment]
same instructions also described here https://github.com/cagnulein/QZCompanionNordictrackTreadmill/issues/60

**Comment by ggaggo** [comment]
Hi Robert
I tried and failed. When I started in power shell the command 
.\adb shell pm grant org.cagnulein.qzcompanionnordictracktreadmill android.permission.READ_LOGS

I got error message: 
_./adb : adb.exe: device offline
In Zeile:1 Zeichen:1
+ ./adb shell pm grant org.cagnulein.qzcompanionnordictracktreadmill an ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (adb.exe: device offline:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError_

So I packed the command in a bat file, but failed again, after entering the treadmill's IP, there was an error message:

_List of devices attached
192.168.0.2:5555       offline transport_id:1_

however, the ping is working, the IP is correct. And i changed it in QZ app too, see attached log file
So, I'm desperate. I spent hours and hours without a result and lost hope.
Until the weekend I'm not able to check anything, I'm out of town.

Have a good day

[debug-Di__Okt__10_22_56_07_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/12865104/debug-Di__Okt__10_22_56_07_2023.log)

**Comment by cagnulein** [comment]
the problem is that adb is not able to find your device. did you enable adb
on the tablet?
I know that it sounds hard but we are literally hacking your machine, it's
not a easy job since ifit is trying to lock up all the things

Il giorno mer 11 ott 2023 alle 07:16 georges gaggo ***@***.***>
ha scritto:

**Comment by ggaggo** [comment]
Hi Roberto
there is no way to enable or disable adb on my tablet - the option doesn't exist in the tablet's settings.
couldn't we send the command as an executable file to the tablet's download folder (or any other folder) via WiFi and PC the same way I installed the QZ Companion apk on the Nordictrack tablet? or include the command in the code of the QZ Companion apk itself?

**Comment by cagnulein** [comment]
nope adb is giving us root access, we can inject it. did you try to factory reset the tablet? it worked for others users here

**Comment by ggaggo** [comment]
I did a factory reset when receiving it. I'll try - and then install all from scratch incl. QZ Companion. Should I update iFit or leave it in original reset version?

**Comment by cagnulein** [comment]
it's important to leave the original ifit version without updating it
I'm going to bed now ;)

Il giorno ven 13 ott 2023 alle 22:28 georges gaggo ***@***.***>
ha scritto:

**Comment by ggaggo** [comment]
have a good rest
