### ISSUE TITLE
[BUG] resistance not working on proform studio bike with companion

### ISSUE THREAD

**Issue by skydivedvm** [cagnulein/qdomyos-zwift#1690]
No changes to resistance from Qz or when running through zwift 

#**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Append a debug log**

 Follow this guide https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
  
  
**Additional context**

**Comment by cagnulein** [comment]
hi @skydivedvm please attach also a debug log so i can check your setup, thanks

**Comment by skydivedvm** [comment]
How do I do that

**Comment by cagnulein** [comment]
@skydivedvm here https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F there are the instructions 

let me know if they are not clear

**Comment by skydivedvm** [comment]
I found the file file I'm not sure how to attach it. 
Sorry I'm not tech savvy

**Comment by skydivedvm** [comment]
![Sun Oct 8 10_40_37 2023_speedInclination](https://github.com/cagnulein/qdomyos-zwift/assets/147333735/34e73db9-cb23-4bb7-9762-f32ddaa5bb75)
![Sun Oct 8 10_40_38 2023_cadence](https://github.com/cagnulein/qdomyos-zwift/assets/147333735/d72ffc20-bcd0-4e8d-a418-6b0ebc3aa1d6)
![Sun Oct 8 10_40_38 2023_heart](https://github.com/cagnulein/qdomyos-zwift/assets/147333735/9c7b5708-2a34-4d16-b33d-75e108768c18)
![Sun Oct 8 10_40_38 2023_pelotonresistance](https://github.com/cagnulein/qdomyos-zwift/assets/147333735/ad54fcb1-d097-4819-a60f-1acdf1f06def)
![Sun Oct 8 10_40_38 2023_power_badge](https://github.com/cagnulein/qdomyos-zwift/assets/147333735/725b0f48-b385-453a-bebc-1e1c13f72895)
![Sun Oct 8 10_40_38 2023_power](https://github.com/cagnulein/qdomyos-zwift/assets/147333735/c8b104b6-9e41-408b-8698-33ee99feb59e)
![Sun Oct 8 10_40_38 2023_powerDistribution](https://github.com/cagnulein/qdomyos-zwift/assets/147333735/fe729f3c-2a89-4004-9ba2-a2d161d1caa9)
![Sun Oct 8 10_40_44 2023_resistance](https://github.com/cagnulein/qdomyos-zwift/assets/147333735/43fa3567-d166-4193-b93c-327938aca946)
![Sun Oct 8 10_40_44 2023_speedInclination](https://github.com/cagnulein/qdomyos-zwift/assets/147333735/a53c62bd-eb52-4ca4-901d-15aaf9f26572)
![Sun Oct 8 10_40_45 2023_cadence](https://github.com/cagnulein/qdomyos-zwift/assets/147333735/0bba6a46-7fe4-4584-bfe3-e7d519d9c01a)
![Sun Oct 8 10_40_45 2023_heart](https://github.com/cagnulein/qdomyos-zwift/assets/147333735/137b8ced-8f99-444d-b9c4-e4e5878e88e5)
![Sun Oct 8 10_40_45 2023_pelotonresistance](https://github.com/cagnulein/qdomyos-zwift/assets/147333735/eb38c42d-5e6b-4c88-a658-0c105333fc66)

**Comment by cagnulein** [comment]
send me it by email roberto.viola83@gmail.com

**Comment by skydivedvm** [comment]
I don't see a file that says debug

**Comment by cagnulein** [comment]
did you enable the debug log in the experimental settings first?

Il giorno dom 8 ott 2023 alle 18:49 skydivedvm ***@***.***>
ha scritto:

**Comment by skydivedvm** [comment]
I turned it on and tried again here is all the new files not seeing it
![Screenshot_20231008_120544_Cx File Explorer](https://github.com/cagnulein/qdomyos-zwift/assets/147333735/5b1d46a9-75ce-4eb7-8211-651298abb028)

**Comment by cagnulein** [comment]
usually they are on the bottom or on the top. did you close qz after
enabling it? can you please record a video while you're browsing on that
folder?

Il giorno dom 8 ott 2023 alle 19:06 skydivedvm ***@***.***>
ha scritto:

**Comment by skydivedvm** [comment]
[debug-Sun_Oct_8_11_53_31_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/12841276/debug-Sun_Oct_8_11_53_31_2023.log)
[debug-Sun_Oct_8_11_57_18_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/12841277/debug-Sun_Oct_8_11_57_18_2023.log)
[debug-Sun_Oct_8_11_57_55_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/12841278/debug-Sun_Oct_8_11_57_55_2023.log)
[debug-Sun_Oct_8_12_00_30_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/12841279/debug-Sun_Oct_8_12_00_30_2023.log)
[debug-Sun_Oct_8_12_02_43_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/12841280/debug-Sun_Oct_8_12_02_43_2023.log)
[debug-Sun_Oct_8_12_06_50_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/12841281/debug-Sun_Oct_8_12_06_50_2023.log)
[debug-Sun_Oct_8_12_18_27_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/12841282/debug-Sun_Oct_8_12_18_27_2023.log)

**Comment by skydivedvm** [comment]
Sorry that took me forever to figure out

**Comment by cagnulein** [comment]
ok thanks i will check them tomorrow morning

Il giorno dom 8 ott 2023 alle 19:25 skydivedvm ***@***.***>
ha scritto:

**Comment by cagnulein** [comment]
ok good news, from QZ everything is ok.
It's the same bike of this https://github.com/cagnulein/qdomyos-zwift/issues/1676 one ?

**Comment by skydivedvm** [comment]
No it is a Proform Studio Bike Pro 22.
Cadence and power transmit fine all the way through to zwift, and the
pelaton resistance changes when the resistance is changed from the bike,
the resistance tile stays at 0.

Thanks

**Comment by cagnulein** [comment]
yes @skydivedvm I removed the resistance because of this https://github.com/cagnulein/qdomyos-zwift/issues/877 https://github.com/cagnulein/qdomyos-zwift/commit/c92b702b2e245a65f6769731d50329b548ab48fd

Does your bike has also the concept of gear and inclination? I guess they are different models.
If not I can add a setting to switch between 2 modes.

But beside this, we need to understand if we can change the resistance on the bike: to do so, in the android developer setting there is a setting to show the touch event. enable it. now if you touch the screen you have to see a ghost under your finger. then, from qz, try to push both plus/minus button on the resistance and inclination tile. Do you see any event on the touchscreen?

Also are you able to connect via adb from your pc? It will be required in order to collect a screenshot of your tablet in order to map the coordinate of the sliders to change the resistance

**Comment by cagnulein** [comment]
no rush from me. You can read the ADB guide here https://github.com/cagnulein/QZCompanionNordictrackTreadmill/blob/master/README.md

**Comment by skydivedvm** [comment]
![Thu10-12-2023@19-51-51 57](https://github.com/cagnulein/qdomyos-zwift/assets/147333735/0df5dc05-56ce-4e90-9f68-9291a8c0def4)

got it connected, uninstalled and reinstalled it from windows still the same here are some screen shots.
let me know what i need to do next

**Comment by cagnulein** [comment]
perfect @skydivedvm were you be able also to enable the touch event on the developer setting? if so did you check if qz sends them?

**Comment by skydivedvm** [comment]
Yes the touch events are enabled and I dont get anything on the screen from qz

**Comment by cagnulein** [comment]
> Yes the touch events are enabled and I dont get anything on the screen from qz

can you try to enable the adb remote setting in the proform/nordictrack setting and restart QZ and try again with the plus and minus buttons on the inclination and the resistance tile? we have to see the touch event. Thanks!

**Comment by skydivedvm** [comment]
Enabled adb remote and I still don't see any touch events.  It doesn't seem to get any comand, it stays with the last place the screen was touched marked.

**Comment by cagnulein** [comment]
can you try tu the follow

adb shell

and then type

input swipe 100 200 300 400 200

when you press enter you should see a touch event

let me know


Il giorno sab 14 ott 2023 alle 13:04 skydivedvm ***@***.***>
ha scritto:

**Comment by skydivedvm** [comment]
This is what I get from my phone.
Not sure how to conect from windows

Thanks

**Comment by skydivedvm** [comment]
Installed the qz companion simple and I get a response on the bike from +
and-  incline.  It opens things way below the screen it is on

Thanks

**Comment by cagnulein** [comment]
wow perfect! so we got an hit! we just need to fix the coordinates of the screen. let me check the screenshot above and I will let you know!

**Comment by cagnulein** [comment]
@skydivedvm good news! I just finished to implement your bike!
Download the new qz companion apk from here https://github.com/cagnulein/QZCompanionNordictrackTreadmill/releases/download/3.3.6/QZCompanionNordictrackTreadmill.apk

then select the Proform Studio Bike Pro 22 device in the companion and restart the bike

Then try again to change the resistance to qz, now the coordinates should be right! (I guess we just need to fix the delta movement, but let's see first if it's working)

let me know!

**Comment by skydivedvm** [comment]
<!--
/* Font Definitions */
@font-face
	{font-family:"Cambria Math";
	panose-1:2 4 5 3 5 4 6 3 2 4;}
@font-face
	{font-family:Calibri;
	panose-1:2 15 5 2 2 2 4 3 2 4;}
/* Style Definitions */
p.MsoNormal, li.MsoNormal, div.MsoNormal
	{margin:0in;
	font-size:11.0pt;
	font-family:"Calibri",sans-serif;}
a:link, span.MsoHyperlink
	{mso-style-priority:99;
	color:blue;
	text-decoration:underline;}
.MsoChpDefault
	{mso-style-type:export-only;}
@page WordSection1
	{size:8.5in 11.0in;
	margin:1.0in 1.0in 1.0in 1.0in;}
div.WordSection1
	{page:WordSection1;}

**Comment by cagnulein** [comment]
@skydivedvm sorry i don't see your answer. could you please write from github?

**Comment by skydivedvm** [comment]
That did it resistance moves from 1 to 2 with + and back to 2 with -

**Comment by cagnulein** [comment]
amazing! so it does also reflect to the resistance tile on qz?

**Comment by skydivedvm** [comment]
It doesn't change in the resistance tile on qz it does change in the peloton resistance.  
It's a little spotty sometimes it works occasionally it doesn't respond

**Comment by cagnulein** [comment]
i guess because the delta movement needs to be calibrated.

for the resistance tile could you please send me a fresh debug log while you're changing the resistance so i will check it

thanks

**Comment by skydivedvm** [comment]
[debug-Mon_Oct_16_07_34_47_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/12916768/debug-Mon_Oct_16_07_34_47_2023.log)
[debug-Mon_Oct_16_07_36_54_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/12916769/debug-Mon_Oct_16_07_36_54_2023.log)
[debug-Mon_Oct_16_07_42_26_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/12916770/debug-Mon_Oct_16_07_42_26_2023.log)

**Comment by cagnulein** [comment]
fixed @skydivedvm ! the problem was about the fact that your bike doesn't send Gears stats and QZ was searching for it to assign the resistance value. The fix will be in the **2.16.17** that it will be out in the next days. Join the beta channel to receive this update https://play.google.com/apps/testing/org.cagnulen.qdomyoszwift

let me know then!

**Comment by cagnulein** [comment]
sorry it will be version 2.16.18, my fault

**Comment by skydivedvm** [comment]
Resistance tile now reads the correct Resistance,  it's very spoty on responding to the Resistance and incline and appears to be back on the original side of the screen

**Comment by cagnulein** [comment]
@skydivedvm what do you mean? i mean it's something to be fixed?

**Comment by skydivedvm** [comment]
The resistance still doesn't change on the bike.  It only occasionally has a touch event in response to +/- on incline tile and the touch event is back on the left side of the screen, where it was originally.   The resistance tile now displays the resistance that matches the screen on the bike.  

Thanks

[debug-Thu_Oct_19_19_23_08_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/13053767/debug-Thu_Oct_19_19_23_08_2023.log)
[debug-Thu_Oct_19_19_23_28_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/13053768/debug-Thu_Oct_19_19_23_28_2023.log)

**Comment by skydivedvm** [comment]
I will try and get new screenshots today, if I can get hits on the touch events

**Comment by cagnulein** [comment]
@skydivedvm Thanks for the log, unfortunately I don't see any connection from the bike at all in these 2 logs. So when you will try again, be sure that you will see the metrics before testing the resistance. I guess adb is not working again? Let me know

**Comment by skydivedvm** [comment]
[debug-Sat_Oct_21_06_22_21_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/13060544/debug-Sat_Oct_21_06_22_21_2023.log)

Did not get any responce on the bike from the app

**Comment by skydivedvm** [comment]
[debug-Sat_Oct_21_06_30_16_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/13060564/debug-Sat_Oct_21_06_30_16_2023.log)

That is running zwift as well.  Target resistance tile changed nothing on the bike 

Thanks

**Comment by cagnulein** [comment]
log checked: could you confirm that ADB is working on the bike? if so I need a complete bug report from the android phone after a small session on zwift. It seems that your phone can't connect to the adb on the bike. Only with a full bug report I would be able to troubleshoot it. Let me know

**Comment by skydivedvm** [comment]
How do I check the ADB on the bike

**Comment by cagnulein** [comment]
in this way https://github.com/cagnulein/qdomyos-zwift/issues/1690#issuecomment-1752924404 as you did before. Since ADB sometimes could disable itself, I would like only to be sure that ADB is still working
Let me know

**Comment by skydivedvm** [comment]
[debug-Sat_Oct_21_07_34_08_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/13060681/debug-Sat_Oct_21_07_34_08_2023.log)
 
It seems to have 2 ip addresses, switched it and got a responce

**Comment by cagnulein** [comment]
so now you see the touch event on your bike tablet?

**Comment by skydivedvm** [comment]
Yes inresponce to the incline tile

**Comment by skydivedvm** [comment]
![Sat10-21-2023@7-39-25 86](https://github.com/cagnulein/qdomyos-zwift/assets/147333735/10970427-55cf-4dd1-ac9b-1e974d572d2c)

**Comment by cagnulein** [comment]
perfect so now are they only miscalibrated right?

**Comment by skydivedvm** [comment]
I think so, it looks like occasional there is a very brief hit form the resistance tile not enough to trigger an event

**Comment by cagnulein** [comment]
ok i will try to build a new one for this in the next days. I will have to add a new setting in the proform bike settings in qz.

**Comment by skydivedvm** [comment]
Thank you

**Comment by cagnulein** [comment]
done @skydivedvm 
if you want, for a quicker test, we can test it directly on the pc version of qz.
The QZ version with this patch will be the 2.16.20

**remember to enable the proform studio setting in the proform bike section in qz**

let me know

**Comment by skydivedvm** [comment]
Do I need to update/ reinstall anything on the bike

**Comment by cagnulein** [comment]
nope! same setup!

Il giorno lun 23 ott 2023 alle 14:07 skydivedvm ***@***.***>
ha scritto:

**Comment by skydivedvm** [comment]
Awsome

**Comment by skydivedvm** [comment]
The update didn't change anything

**Comment by cagnulein** [comment]
@skydivedvm please provide me a fresh log. As I said calibrating the coordinates will be a tricky job so it will be better using the windows version.

Anyway let's check the debug log first.

**Comment by cagnulein** [comment]
@skydivedvm any news?
