### ISSUE TITLE
[REQ] Watch OS 10 CSC Bluetooth Data for Bike

### ISSUE THREAD

**Issue by keatontaylor** [cagnulein/qdomyos-zwift#1924]
**Is your feature request related to a problem? Please describe.**
In WatchOS 10, apple added the ability for the Apple Watch to connect to various fitness devices for cadence, speed and power. I currently use the iFit subscription for my workouts but prefer to have my workouts recorded in apple health kit. I could sync the iFit workouts to HealthKit but I found them to be semi-inaccurate. 

**Describe the solution you'd like**
I'd like qdomyos-zwift to be able to transmit as an Apple Watch compatible health device via the CSC protocol. 

A great example is here: https://github.com/dbsqp/bluetooth-reebok-57e

**Describe alternatives you've considered**
The Apple Watch does detect the QZ companion app when running as a virtual bluetooth device currently, but no data appears to show up in the apple indoor cycling/running workout even with the watch connected to QZ.

**Additional context**
For additional context, I am not attempting to connect my watches heart rate monitor to qdomyos-zwift. I am attempting to connect my watch so I can use Apple Watch workouts but have those workouts include the live data from qdomyos-zwift in real time. 

If this is currently possible via settings please let me know, I was unable to get it working, even if the watch was able to detect QZ and pair with it, the metrics never showed in the Apple Watch workout. Please see https://github.com/dbsqp/bluetooth-reebok-57e again if you're curious how I ideally see this working.

**Comment by cagnulein** [comment]
you can do already but not via the iphone directly paired with the watch.
you have to use an ipad, or a mac or an android device or a windows machine

Let me know

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno gio 28 dic 2023 alle 20:13 Keaton Taylor ***@***.***>
ha scritto:

**Comment by keatontaylor** [comment]
Yep, had discovered that during the troubleshooting phase, swapped to using qdomyos-zwift on an iPad which makes the health device discoverable as "QZ" on the watch. However, I am still not seeing the data from the bike on the watch. 

My setup is:
NordicTrack S22i with the QZCompanionNordictrackTreadmill app installed
iPad Pro (3rd Gen - iOS 17.1.1) running qdomyos-zwift and accurately showing speed, inclination, watts, odometer.
Watch Series 9 (watchOS 10.1) connected to the "QZ" health device. (does not appear to stay connected). Below are settings.

Under Experimental Features:
- Enable Virtual Device - ON
- Virtual Device Bluetooth - ON
- Bike Power Sensor - ON

Under Treadmill Options:
- Proform/NodicTrack Options -> NodicTrack 295 IP - IP Address of bike

All other settings default

**Comment by cagnulein** [comment]
if you see qz on the watch you are right. you need to several times this
process because sometimes the watch is not getting it.
in the bluetooth settings of the watch pair it and connect it. then open
the apple fitness app and you will get it.
it also works all the time with an android device

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno gio 28 dic 2023 alle 20:45 Keaton Taylor ***@***.***>
ha scritto:

**Comment by keatontaylor** [comment]
I've definitely attempted multiple times, just curious there are any settings that I missing that ensure the bluetooth data transmitted is CSC that the Apple Watch accepts. 

I can dig an android device out and see if that helps, but since I often have any iPad with me anyway was really hoping that would work. 


Does the setting in "Treadmill as Bike" need to be enabled? Under Treadmill options? Or perhaps some other setting that I am missing?

**Comment by cagnulein** [comment]
nope that setting is not useful.
you can also disable the bike power sensor setting and try without it.
Let me know

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno gio 28 dic 2023 alle 20:56 Keaton Taylor ***@***.***>
ha scritto:

**Comment by keatontaylor** [comment]
I did try with and without it the power sensor, still no success getting it to show up on watchOS 10. Side note that might be related, cadence in the qdomyos-zwift is always zero, is this a misconfiguration as well or expected?

**Comment by cagnulein** [comment]
for sure that's the issue. if watchos get cadence 0 it's not connecting to
it. so share a debug log with this issue, that's definitely the issue

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno gio 28 dic 2023 alle 21:10 Keaton Taylor ***@***.***>
ha scritto:

**Comment by keatontaylor** [comment]
Attached is the debug log. 
[debug-Thu_Dec_28_14_21_25_2023.log](https://github.com/cagnulein/qdomyos-zwift/files/13789274/debug-Thu_Dec_28_14_21_25_2023.log)

**Comment by cagnulein** [comment]
found the issue. remove the ip from the nordictrack setting in the treadmill and press ok and set it instead on the nordictrack bike settings , tdf companion ip and press ok

**Comment by keatontaylor** [comment]
Cadence and resistance are correctly showing up in qdomyos-zwift iOS app now, connecting the Apple Watch to the QZ Bluetooth health device still shows no stats from the bike on the watch indoor bike workout. 

Booting up an android device to try also reinstalling the qdomyos-zwift app on the iPad just incase I inadvertently messed up some settings.

**Comment by cagnulein** [comment]
i will record a video for you, maybe you are doing something different from
me

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno gio 28 dic 2023 alle 21:49 Keaton Taylor ***@***.***>
ha scritto:

**Comment by cagnulein** [comment]
done https://github.com/cagnulein/qdomyos-zwift/assets/48216/448505fd-2cd5-4385-9c6c-ed16498d9c8f

**Comment by keatontaylor** [comment]
Following your exact steps, still nothing coming in on the Apple Watch. Attempted an android tablet and the watch sees no bluetooth connection at all. Default settings with the exception of the IP for the bike under the bike settings within the android trial apk under releases. (also tried the nightly build)

**Comment by cagnulein** [comment]
ok android you need the bike power sensor .
can you show me a video of what you are doing on ipad to watch?

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno gio 28 dic 2023 alle 22:30 Keaton Taylor ***@***.***>
ha scritto:

**Comment by keatontaylor** [comment]
Was able to get it to work for the power (watts) by turning off Airdrop (contacts only) on the iPad. I suspect that was messing with the bluetooth signal.

Should I also see cadence, distance, speed on the Apple Watch? I am not seeing those in your video and still not seeing them in the apple watch when doing the workout.

**Comment by cagnulein** [comment]
qz sends all of them but apple watch just use power and cadence as far as i
know

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno gio 28 dic 2023 alle ore 22:52 Keaton Taylor <
***@***.***> ha scritto:

**Comment by keatontaylor** [comment]
hmm, cadence, speed, distance and power. are all supported via https://github.com/dbsqp/bluetooth-reebok-57e as of iOS 10. Also not seeing cadence come in on the Apple Watch.

**Comment by cagnulein** [comment]
yes but in order to send power (the most important one) qz must emulates a
power pedal. power pedal can send only power and cadence. speed is based on
cadence, and also distance of course.
qz is also sending the other metrics by ftms but apple watch doesn't
support it
in order to send cadence on a separate way, qz will need to emulate a
cadence sensor but apple watch is not smart enough to get 2 different
sensors from 1 device only as far as I know.
I will check the code of that project to see if I can do something
different to better like to the apple watch.
11pm right now here, so I will go to sleep ;)

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno gio 28 dic 2023 alle ore 22:56 Keaton Taylor <
***@***.***> ha scritto:

**Comment by keatontaylor** [comment]
thank you very much for all your help, truly appreciate it.

**Comment by cagnulein** [comment]
the reason why you can't see speed or distance is because cadence (note for
me). i guess i understood why, apple watch wants them in a different way.
i will check it tomorrow

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno gio 28 dic 2023 alle ore 23:03 Keaton Taylor <
***@***.***> ha scritto:

**Comment by cagnulein** [comment]
note: AW wants wheel count, that's why, i will add it :)

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno gio 28 dic 2023 alle ore 23:20 cagnulein ***@***.***> ha
scritto:

**Comment by cagnulein** [comment]
done @keatontaylor i did this for both android and ios. i tested and i can see correctly cadence now.
The only thing that I can't understand it's how show speed and distance on the apple watch workout app for indoor bike. It doesn't give me the way. Are you able to see it somehow? I would like to ask to @dbsqp how can I show the metrics there. Anyway qz now is sending the metrics in the same way as https://github.com/dbsqp/bluetooth-reebok-57e/tree/AppleWatch-branch does

You can test it using the android build here https://github.com/cagnulein/qdomyos-zwift/commit/93779d04c50fbb211becdea4906533241c9a4e0f or 
send me an email to roberto.viola83 at gmail.com indicating this ticket to get the ios one.

Let me know!

**Comment by dbsqp** [comment]
It might be that the instance of the CPP service implemented here is not reporting cumulative wheel revolutions and its associated time stamp i.e. only reporting power and cadence. I will have a look at the code but maybe one of the devs would know.

**Comment by cagnulein** [comment]
ehehe i'm the dev :) i'm reporting the timestamp, i guess it's something else, because even when i wasn't sending cadence, i  was able to add the cadence metric (even if it was showing "--")

**Comment by cagnulein** [comment]
maybe it's the feature characteristic

```
// CP 32 bit/0-31 - 4/5:crankRev 3/4:wheelRev
  byte feature[1] = { 0b00000000000000000000000000001100 };
```

i will check this later.

**Comment by dbsqp** [comment]
OK. My code creates one service CSC (cadance/speed) or CPP (power/cadance/speed). For CPP I set the features using the raw binary flags that you just quoted and add the data to the packet send by notify. I found using a layer of abstraction confused and difficult to align with the  BLU CPP specs. I think you are not declaring the feature, if you don't declare it data send will just be ignored by client.

I also think you can create combined services with BLU i.e. one device with CPC and HR etc. I did not do this hence using CPP as a superset of CSC.

**Comment by cagnulein** [comment]
I just tried and it makes no difference. I'm still thinking that it's something else. @dbsqp could you please add here a screenshot from your watch where you can customize the screen for the indoor ride adding the distance and speed metrics? maybe i'm ignoring something simple :)

**Comment by dbsqp** [comment]
![2023-12-29 17-01 at incoming-6B94637E-ECA9-471B-B521-C223114B6D53](https://github.com/cagnulein/qdomyos-zwift/assets/5895806/efda622d-5019-4ce8-abd1-2bbbf29b5e23)
![2023-12-29 17-01 at incoming-03619798-A226-4AC2-A6F3-1E102BB5D332](https://github.com/cagnulein/qdomyos-zwift/assets/5895806/19cb2395-ce99-4cfe-92d4-e9c8b06f40ae)
![2023-12-29 17-02 at incoming-8F9C1E3B-4589-442B-952D-17756D0D37AD](https://github.com/cagnulein/qdomyos-zwift/assets/5895806/d7aef156-851b-438b-9cde-df6dafc19779)
![2023-12-29 17-02 at incoming-75C77190-B404-4526-9677-566498F8670B](https://github.com/cagnulein/qdomyos-zwift/assets/5895806/91275be6-0c4b-4084-885d-f17af38cfdf5)

This just displays metric, if its not reported wont see a value. Can also see trend of metrics in iOS Fitness App under workout details > show more.

**Comment by cagnulein** [comment]
thanks! so yes for sure i need to do something else! thanks for your time! maybe it's a cache issue on the watch.

**Comment by dbsqp** [comment]
No problem. There was a reason I started with FMTS, then implemented CSC and when that was working setup CPP. I also think it is strange wheel dimension is not a variable. Is not cached by watch as since I developed my code I have clean installed my phone and watch and connected as only CPP and all works as expected (surprisingly). Although my code works there was much trial and error to get things working. Good luck!

**Comment by cagnulein** [comment]
@keatontaylor did you try the new beta?

**Comment by keatontaylor** [comment]
Hey @cagnulein the app appears to be working on occasion, having lots of bluetooth disconnection issues. Actually ended up working on @dbsqp code to modify it to fetch the UDP packets coming from QZCompanionNordictrackTreadmill and then just re-broadcast them via an ESP32. 

This is working great for power, but I am having a really hard time calculating the cadence from just the RPM. 

Any insights on how you're taking the RPM and converting it into crank/wheel count and time last crank revolution and last wheel revolutions?

**Comment by cagnulein** [comment]
hi @keatontaylor sorry to hear this, did you also try the android version? 

for the cadence, check the module of @dbsqp is very easy to understand

**Comment by keatontaylor** [comment]
For the android version I am still unable to get it to show up as a bluetooth health device at all, but it could be some issue with the bluetooth on the tablet that I am using. I am unsure.

I had looked into the code written by dbsqp, and I do fully understand all the necessary values, crankCount, time of last crank, etc, but what I do not understand is how you're taking RPM from QZCompanionNordictrackTreadmill and converting it into crank count and time of last crank. (Same for wheel count, etc) 

My understanding that might be wrong is that you're always increasing crank count by 1:


```
CrankRevs++;
LastCrankEventTime += (uint16_t)(1024.0 / (((double)(Cadence.value())) / 60.0));
```

So if I understand this correctly the following example would be true:

CrankRevs = 0
LastCrankEventTime = 0

New UDP packet from Bike reporting an RPM of 55

CrankRevs = 1
LastCrankEventTime = 1229  -> `(1024 / (50 / 60) rounded up`

Is this accurate?

**Comment by keatontaylor** [comment]
Alright got cadence and power correctly working on the watch via an ESP32 repackaging data from QZCompanionNordictrackTreadmill and publishing it over BLE via @dbsqp code.

Thank you both for your efforts, very happy to have this data liberated from NordicTrack's very closed ecosystem.

One additional side note: I am still unable to get the watch to show the speed/distance in real-time, but they do show up in the fitness app under the summary of the workout, need to fiddle with the wheelRotations vs. crankRotations to get them accurate but otherwise things are working exceptionally well.

Going to close this ticket as completed since I was able to get it working on the iPad as well, just not consistently.

**Comment by cagnulein** [comment]
> Alright got cadence and power correctly working on the watch via an ESP32 repackaging data from QZCompanionNordictrackTreadmill and publishing it over BLE via @dbsqp code.


great!


> 
> 
> 
> Thank you both for your efforts, very happy to have this data liberated from NordicTrack's very closed ecosystem.


glad to hear this!

> 
> 
> 
> One additional side note: I am still unable to get the watch to show the speed/distance in real-time, but they do show up in the fitness app under the summary of the workout, need to fiddle with the wheelRotations vs. crankRotations to get them accurate but otherwise things are working exceptionally well.

yes it's what i'm seeing to! @dbsqp are you using any watchos beta? i can't explain this in any other way

> 
> 
> 
> Going to close this ticket as completed since I was able to get it working on the iPad as well, just not consistently.

ok but please keep me updated about this, i'm very curious about distance and speed, thanks

**Comment by dbsqp** [comment]
My Apple Watch Ultra 1 is running 10.2 (21S364). My code was developed on only release versions from 10.0 which implemented support for the cadence/speed/power sensors.

What I could do is log out the raw integers sent from my code, you can then at-least see if there is a problem. At the same time I can set my code to be in CSC mode and take some screenshots of the wheel dimension option.

**Comment by dbsqp** [comment]
One other thing to consider is to use the indoor not outdoor cycling workout. For the latter I think the speed/distance values are taken from GPS data not wheel revolution.

**Comment by cagnulein** [comment]
> My Apple Watch Ultra 1 is running 10.2 (21S364). My code was developed on only release versions from 10.0 which implemented support for the cadence/speed/power sensors

are you able to update the watchos to the latest version to check that it's still working?

> 
> What I could do is log out the raw integers sent from my code, you can then at-least see if there is a problem. At the same time I can set my code to be in CSC mode and take some screenshots of the wheel dimension option.
> 

sure it could be useful, maybe a constant wattage and cadence. let's say 100w and 100rpm. i'm using the CP mode 

thanks

**Comment by cagnulein** [comment]
> One other thing to consider is to use the indoor not outdoor cycling workout. For the latter I think the speed/distance values are taken from GPS data not wheel revolution.

yep right, always used indoor one

**Comment by dbsqp** [comment]
WatchOS 10.2 is current release. Have also uploaded serial logs to my project under /documentation/debug-*. There is the serial output of my code in power mode, the extract of the xml export from health under iOS and two images showing screens from iOS. Note that the rollover of my integers for crank/wheel times are synchronised as lastWheelK = 2 x lastCrankK. Also took screen grab of sensor in CSC mode with the option to set wheel dimension.
![2023-12-30 17-00 at incoming-17B2350A-FBE9-4D3F-B5B3-25CE91FA5074](https://github.com/cagnulein/qdomyos-zwift/assets/5895806/9253001d-ae34-4635-8236-842f11da8a07)

**Comment by cagnulein** [comment]
i see only the screenshot, where did you put the log? Thanks!

**Comment by dbsqp** [comment]
https://github.com/dbsqp/bluetooth-reebok-57e/tree/AppleWatch-branch/documentation

files starting debug-*

**Comment by cagnulein** [comment]
thanks! very helpful! I will compare them with mine!

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno sab 30 dic 2023 alle ore 18:35 dbsqp ***@***.***>
ha scritto:

**Comment by keatontaylor** [comment]
Alright, I got it working, the issue is that if the sensor has only ever reported supporting the Cycling Power Service the Apple Watch will not offer the ability to select putting speed/distance on the workout views.

I setup @dbsqp code, turned off `USEPOWER` so it would instead use the Cycling Speed and Cadence Service. Flashed to the ESP32 and then forgot the bluetooth health device and reconnected it. Then I could add the speed and distance to the workout view watch faces.

Next I reflashed my code that handles the UDP broadcast packet reading from the bike and sets up the Cycling Power Service. The watch preserves the settings and still allows you to see the speed/distance, since it is being reported by the BLE connection.

A few things worth noting:

- Setting the wheel rotations == crank rotations will result in inaccurate distance measurements.
- Setting the last wheel trigger as a multiple of the last crank trigger (*2 for example) will result in inaccurate speed measurements.

Both of these are due to the fact that the reported speed on the bike is dependent on resistance. Instead after some trial and error I arrived at the following function.

```
// Calculate the wheel offset.
double wheelOffset = kphValue * 2.66;
lastWheelK = lastWheelK + (int)(2048.0 / (wheelOffset / 60.0));
wheelCount = wheelCount + 3;
```

This seems to get the best results regardless of the resistance selected in the bike, but I have no idea if they're actually accurate as I might be missing something.

**Comment by cagnulein** [comment]
so it seems a apple bug the fact that i don't see distance! good to know!
thanks for the detailed feedback!

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno sab 30 dic 2023 alle 21:49 Keaton Taylor ***@***.***>
ha scritto:

**Comment by dbsqp** [comment]
So do we think that the wheel size is somehow cached on the client from previous device config where it was set? I also re-read the bluetooth spec for a power meter and searched a bit and only found crank-length being a user set variable. Anyway glad my code was of help.

**Comment by keatontaylor** [comment]
Yeah my guess is that if the wheel size is entirely on the apple side, if it isn't set, then apple just assumes the default. 

I might play around with adjusting the wheel size in Cadence and Speed mode and see if that setting is preserved when moving back to Cycling Power mode.

Side note: does apple really not support the running speed and cadence service? I cannot find a single reference to them supporting this spec,  but haven't modified the BLE code to just try it. Would be cool to get my treadmill integrated as well.

**Comment by cagnulein** [comment]
nope they don't support them. but qz can write all the metrics (bike and run) using the apple watch app of qz .

maybe it will be easier for you?

**Comment by pqhf5kd** [comment]
I'm trying to use QZ on an iPad to link my Doymos bike to my Watch but nothing appears under Health Devices on the watch. Do I ned to enable any settings?

**Comment by cagnulein** [comment]
> I'm trying to use QZ on an iPad to link my Doymos bike to my Watch but nothing appears under Health Devices on the watch. Do I ned to enable any settings?

in the bluetooth settings of the watch, don't you see the ipad or a device called "QZ"?
Anyway, QZ app on the apple watch can already write for you all the metrics!

**Comment by pqhf5kd** [comment]
No I don't. I tried both my own iPhone and my partners iPad (different iCloud accounts).

> Anyway, QZ app on the apple watch can already write for you all the metrics!

I'd liked the metrics for Fitness+ workouts. Does it work for that?

**Comment by cagnulein** [comment]
> No I don't. I tried both my own iPhone and my partners iPad (different iCloud accounts).

is the virtual bluetooth device enabled in the experimetnal settings?

> 
> > Anyway, QZ app on the apple watch can already write for you all the metrics!
> 
> I'd liked the metrics for Fitness+ workouts. Does it work for that?

QZ writes the same stats that the Fitness+ does! Power, Cadence, Speed and Distance. You just need the beta of QZ. Write me an email about this!

**Comment by pqhf5kd** [comment]
> is the virtual bluetooth device enabled in the experimetnal settings?

It is 

> QZ writes the same stats that the Fitness+ does! Power, Cadence, Speed and Distance. You just need the beta of QZ. Write me an email about this!

Into the Fitness+ workout? or as separate metrics directly into Health?

**Comment by cagnulein** [comment]
> > is the virtual bluetooth device enabled in the experimetnal settings?
> 
> It is

so it should be everything right, if you want share a debug log and I can check the others settings

> 
> > QZ writes the same stats that the Fitness+ does! Power, Cadence, Speed and Distance. You just need the beta of QZ. Write me an email about this!
> 
> Into the Fitness+ workout? or as separate metrics directly into Health?

As a workout in the apple health.

**Comment by pqhf5kd** [comment]
[debug-Mon_Jan_1_12_26_49_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/13804340/debug-Mon_Jan_1_12_26_49_2024.log)

I hope this works :)

**Comment by pqhf5kd** [comment]
> As a workout in the apple health.

I'd prefer to integrate them into the Fitness+ workout if possible

**Comment by cagnulein** [comment]
> [debug-Mon_Jan_1_12_26_49_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/13804340/debug-Mon_Jan_1_12_26_49_2024.log)
> 
> I hope this works :)

seems everything fine.
try to disable the ios peloton workaround in the experimental settings. maybe it's just a cache issue on the watch

**Comment by pqhf5kd** [comment]
Unfortunately I still can't see any option to connect from the Watch, even after disabling Peloton workaround, restarting the devices and trying my partners watch. 

I can see my watch in QZ under the Manual Device list but I suppose that's for connecting to the workout equipment. 

I'll email about the beta

**Comment by cagnulein** [comment]
it seems something is preventing the connection. it could be airdrop ( @keatontaylor had a similar issue in the last days )
