### ISSUE TITLE
[BUG] Zwift Treadmill Auto Workout doesn't work correctly, speed was set way to low on treadmill

### ISSUE THREAD

**Issue by afitz85** [cagnulein/qdomyos-zwift#2042]
**Describe the bug**
Enabled "Zwift Treadmill Auto Workout" but the speed that was sent to the treadmill doesn't match the spped it should. The speed of the treadmill was always sent way too low... 1.5 km/h instead of 12.5 km/h for example. And the speed was only decreased, never increased. So when the speed on the treadmill was very low on 1.5 km/h it never gets higher when zwift says 12.5 km/h.
But i tried it several times, and - i don't know why - the speed also was sometimes set correct, but that was only once, and in the next workout step it was totally wrong again.

I have a Horizon Paragon X Treadmill.

**Desktop (please complete the following information):**
 - OS: Windows 10 (PC)
 

[debug-Mi__Jän_24_17_31_25_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14041189/debug-Mi__Jan_24_17_31_25_2024.log)

**Comment by cagnulein** [comment]
@victorypoint i need your help here. it seems that sometimes the paddle ocr returns some strange values

```
Mi. Jän 24 17:32:20 2024 1706113940227 Debug: bluetooth.cpp void bluetooth::debug(const QString&) "python << OUT 30.0;None\r\n"
_thread::runPython(QString) run >>  "zwift-workout.py"
Mi. Jän 24 17:32:20 2024 1706113940233 Debug: bluetooth.cpp void bluetooth::debug(const QString&) "python << ERR "
Mi. Jän 24 17:32:20 2024 1706113940235 Debug: bluetooth.cpp void bluetooth::debug(const QString&) "windows_zwift_workout_paddleocr_thread onInclination None\r\n onSpeed \u001E"
Mi. Jän 24 17:32:20 2024 1706113940239 Debug: treadmill.cpp virtual void treadmill::changeSpeed(double) changeSpeed 30.55 true 1 0 30
```

do you suggest to use the ai server instead?

**Comment by victorypoint** [comment]
@afitz85, I'd like to test with the exact same workout as you to eliminate a few things. What is the workout - provided with Zwift or a custom one?

**Comment by afitz85** [comment]
I tried 3 different zwift workouts, no custom ones.

**Comment by victorypoint** [comment]
> I tried 3 different zwift workouts, no custom ones.

Ok, can you tell me which ones?

**Comment by afitz85** [comment]
![Screenshot_20240124_203008_com zwift zwiftgame](https://github.com/cagnulein/qdomyos-zwift/assets/157009794/613f8345-6e5c-4370-9eec-2c5f38e7b4bc)

I think this was one of them.

**Comment by afitz85** [comment]
I didn't really run today, just wanted to test how it works with qz and automatic treadmill workouts, so i just picked some to try it out.
So i'm not 100% sure which ones i tested. But the one above was definitly one of them.

**Comment by afitz85** [comment]
> > ![Screenshot_20240124_203008_com zwift zwiftgame](https://private-user-images.githubusercontent.com/157009794/299434763-613f8345-6e5c-4370-9eec-2c5f38e7b4bc.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYxMjUwNjEsIm5iZiI6MTcwNjEyNDc2MSwicGF0aCI6Ii8xNTcwMDk3OTQvMjk5NDM0NzYzLTYxM2Y4MzQ1LTZlNWMtNDM3MC05ZWVjLTJjNWYzOGU3YjRiYy5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyNFQxOTMyNDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xOTI5YTUzOWE3ZWMzNWMyZmZkZWU0ZDFjOWMyYWNjZGU2OTg0ODA5OGFmZjI5MzhlZDliNTZiMGZhZThkZWJjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.bTTDe17GQOTJSMvI4pwzx04v2TYtJzFQADQ34m2PDLY)
> > I think this was one of them.
> 
> Ok thanks. I'll give this a test tonight when I get home.

Thank you!

**Comment by victorypoint** [comment]
@afitz85, can you confirm which QZ Windows package you're using? Zip file you downloaded?

**Comment by victorypoint** [comment]
@cagnulein, @afitz85, I know what the issue is. I only tested the code to work with specific workout instructions such as:
![zwift-20-36-18-crop](https://github.com/cagnulein/qdomyos-zwift/assets/63697253/f71bfa00-9aeb-452a-85d6-5196ce19850b)

Unfortunately, most regular Zwift workouts begin with a warmup instruction and rarely have incline, such as:
![zwift-20-41-38-crop](https://github.com/cagnulein/qdomyos-zwift/assets/63697253/453849e9-8fee-43ae-9ee7-9e962f08dd8b)

So I have to revise the python code to accomodate these types of workouts. The OCR conversion is working fine. I'll find time to do this on the weekend.

**Comment by cagnulein** [comment]
awesome!

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno gio 25 gen 2024 alle 04:00 Al Udell ***@***.***> ha
scritto:

**Comment by afitz85** [comment]
Good to hear 👍🏻
I used the windows-binary of this version
![Screenshot_20240125_054247_com android chrome](https://github.com/cagnulein/qdomyos-zwift/assets/157009794/d1333056-4545-4087-8595-2ab9573f9a24)

So workouts with constant speed, without warm-up or cool-down ramps will work so far?

**Comment by afitz85** [comment]
+++ maybe a little bit off topic, but is there a way to add my set speed_offset in qz (-0.55 km/h in my case) to the workout speed zwift sends to the treadmill? Otherwise the "right" speed is always 0.55 km/h to low when the speed_offset is ignored?

**Comment by cagnulein** [comment]
yes just copy and paste that value in the speed offset setting

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno gio 25 gen 2024 alle 05:54 afitz85 ***@***.***> ha
scritto:

**Comment by afitz85** [comment]
Sorry, where i have to copy it?
I set the speed_offset here...
![Screenshot_20240125_064855](https://github.com/cagnulein/qdomyos-zwift/assets/157009794/5b553fc1-5720-4bf1-9b23-e81bbc0e39cd)

Just to be clear...  This works so far, when i set the treadmill to 10.6km/h, zwift speed is about 10km/h (speed offset works).
But when zwift says the workout step is 10km/h, the treadmill runs at 10km/h, and ignores the speed_offset of 0.55km/h (it should run at 10.6km/h to match the "real" 10km/h for me.  Is this possible?

**Comment by cagnulein** [comment]
hah sorry got it now! yes i can apply it to the training too! let me do this today!
thanks for the feedback!

**Comment by afitz85** [comment]
Great to hear 👍🏻🥳
Thanks

**Comment by cagnulein** [comment]
actually @afitz85 I already did for your last ticket #2012 are you using the last version?

**Comment by afitz85** [comment]
i downloaded the latest version yesterday (windows binary) https://github.com/cagnulein/qdomyos-zwift/actions/runs/7641451863 yes.

In the Ticket #2012 there was a problem if i tried to increase the speed on android in the qz app with the + button, then the treadmill speed decreased heavily (think from 8km/h to 1.5km/h or so)
![1](https://github.com/cagnulein/qdomyos-zwift/assets/157009794/844a848d-b9da-4c2c-bcd8-64eae99df300)

**Comment by afitz85** [comment]
ok that's good to hear.

Due to the generally incorrect values transmitted by Zwift, I'm a bit unsure now, I thought it didn't work, but before you do anything I'll check it again in the evening

**Comment by cagnulein** [comment]
Perfect!

**Comment by afitz85** [comment]
![2024-01-26_15-24-57_1](https://github.com/cagnulein/qdomyos-zwift/assets/157009794/3ec701ae-6c5e-4386-9c89-54ce1b06a676)
![2024-01-26_15-21-48_0](https://github.com/cagnulein/qdomyos-zwift/assets/157009794/fb294662-67c8-4ef5-91cd-584e5144abeb)
[debug-Fr__Jän_26_15_21_17_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14065959/debug-Fr__Jan_26_15_21_17_2024.log)

i tried a custom workout now (without ramps, just constant speed), because i can't find any zwift workout with constant speed, all have a warm-up ramp at the beginning.
So unfortunately it doesn't work at all... none of the speeds of the workout was transmitted to the treadmill...

**Comment by afitz85** [comment]
the settings i made are correct? or have i to do anything else?
![Unbenannt](https://github.com/cagnulein/qdomyos-zwift/assets/157009794/3e182344-c915-4eea-a638-79f05240dc01)

**Comment by victorypoint** [comment]
@afitz85, I will have a solution to this soon. Thanks for testing 👍

**Comment by afitz85** [comment]
Perfect, looking forward to this 👍🏻 thanks.

**Comment by victorypoint** [comment]
@afitz85, please try the attached custom workout. It will go through a series of quick speed and incline changes - 5 changes in total for 30 seconds each.

[QZ Test.zip](https://github.com/cagnulein/qdomyos-zwift/files/14066301/QZ.Test.zip)

**Comment by afitz85** [comment]
[debug-Fr__Jän_26_16_12_24_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14066496/debug-Fr__Jan_26_16_12_24_2024.log)

ok so that looks better now but...
- to start the workout i had to increase the speed manually because with my set speed_offset in the qz app (-0.55) the starting speed on my treadmill only was 0.2km/h (looks like this is to slow for zwift to start the workout timer).

- looks like the speed at the treadmill only changed when the incline changes, like the incline will trigger the speed to change (so incline definitely works)

**Comment by cagnulein** [comment]
@afitz85 if you change the speed from the qz tile are you able to do it without changing the inclination too?

**Comment by afitz85** [comment]
yes, when i change the speed from the qz tile, i can increase the speed without changing inclination

i tried the workout once again and i can say, the treadmill is starting automatically and the incline is set correctly. but the speed stays as it is (jumped not to the workout speed)

when the secound workout step started the speed doesn't change immediately, it took about 2 seconds then the incline changes, and then did the speed change

**Comment by afitz85** [comment]
but maybe it just took a while (2 to 3 seconds) till changes where applied, and speed will also change automatically without incline change!?

**Comment by cagnulein** [comment]
i guess i got it, it's because i'm sending a ftms frame to start the simulation 2 times and probably the treadmill refuses it (i did this for a technogym treadmill)

let me try a branch to remove this

**Comment by afitz85** [comment]
ok.

tried my custom workouts again (they are without incline) and there the workout neither starts by itself nor does the speed change

**Comment by cagnulein** [comment]
@afitz85 done https://github.com/cagnulein/qdomyos-zwift/actions/runs/7670262351

**Comment by cagnulein** [comment]
@afitz85 wait there is a major issue on your settings! the speed force setting in the treadmill section is disabled!

**Comment by afitz85** [comment]
This one?
![Unbenannt](https://github.com/cagnulein/qdomyos-zwift/assets/157009794/e37a8dd9-5fe7-4fa5-b417-15566b93828d)

yes it was disabled. i enabled it, restarted the qz app, but nothing changes

**Comment by afitz85** [comment]
> @afitz85 done https://github.com/cagnulein/qdomyos-zwift/actions/runs/7670262351

when it's ready i try the windows binary there?

**Comment by cagnulein** [comment]
> > @afitz85 done https://github.com/cagnulein/qdomyos-zwift/actions/runs/7670262351
> 
> when it's ready i try the windows binary there?

yes

**Comment by cagnulein** [comment]
> This one? ![Unbenannt](https://private-user-images.githubusercontent.com/157009794/300035941-e37a8dd9-5fe7-4fa5-b417-15566b93828d.JPG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYyODQ4NDgsIm5iZiI6MTcwNjI4NDU0OCwicGF0aCI6Ii8xNTcwMDk3OTQvMzAwMDM1OTQxLWUzN2E4ZGQ5LTVmZTctNGZhNS1iNDE3LTE1NTY2YjkzODI4ZC5KUEc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyNlQxNTU1NDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mYmFkNDk1ZWEzYWQyZGIxNTAxYjkwOGVkMzljMTcyMTJlZTNmY2MyNTU0OTk5ZDk4M2M0NGYyMzhkNzI5ZDIwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.AED2z2ZtOzNRJJrjZgxipiZ4nqPa4Ug1EhxntM0E9Ak)
> 
> yes it was disabled. i enabled it, restarted the qz app, but nothing changes

so you tried a zwo file with only speed changes and it doesn't work with this enabled? share a debug log plz

**Comment by afitz85** [comment]
[debug-Fr__Jän_26_16_57_25_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14066922/debug-Fr__Jan_26_16_57_25_2024.log)

yes, nothing changed

**Comment by cagnulein** [comment]
oki will check the log asap

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno ven 26 gen 2024 alle 17:03 afitz85 ***@***.***> ha
scritto:

**Comment by afitz85** [comment]
> > > @afitz85 done https://github.com/cagnulein/qdomyos-zwift/actions/runs/7670262351
> > 
> > 
> > when it's ready i try the windows binary there?
> 
> yes

I'm sorry, but now nothing is working, no incline and no speed (tried both, workout with and without incline)
[debug-Fr__Jän_26_17_31_28_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14067252/debug-Fr__Jan_26_17_31_28_2024.log)

**Comment by cagnulein** [comment]
ok so i will check it
thanks

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno ven 26 gen 2024 alle 17:39 afitz85 ***@***.***> ha
scritto:

**Comment by cagnulein** [comment]
So resume the working version now

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno ven 26 gen 2024 alle 18:45 cagnulein ***@***.***> ha
scritto:

**Comment by victorypoint** [comment]
@afitz85, when you get things working again, I have a fix for the workout speed and incline for you to test please. Download the attached, unzip, and copy the zwift-workout.py file inside your QZ folder overwriting the old one. Test a workout and let us know!

[zwift-workout.zip](https://github.com/cagnulein/qdomyos-zwift/files/14069273/zwift-workout.zip)

**Comment by cagnulein** [comment]
> [debug-Fr__Jän_26_16_57_25_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14066922/debug-Fr__Jan_26_16_57_25_2024.log)
> 
> yes, nothing changed i tried my workout without incline, and the one with incline

@afitz85 i checked this log and the speed is changing when qz asks it. i saw also, and maybe it's the issue that you are referring to, that when you set speed 0 qz can't control it, but that's quite usual for all the treadmills.
can you try a session without setting the speed to 0 manually?

**Comment by afitz85** [comment]
Should i tty these things going back to an earlier version than https://github.com/cagnulein/qdomyos-zwift/actions/runs/7670262351?

I can't set my tteadmill to 0 speed, the lowest possible is 0.8km/h. The 0 speed you see must be when i stop (pause) the treadmill!?

When it is in pause mode the workout automatically started with the test workout of @victorypoint, my custom workouts haven't done.

**Comment by cagnulein** [comment]
> Should i tty these things going back to an earlier version than https://github.com/cagnulein/qdomyos-zwift/actions/runs/7670262351?

yes

> 
> I can't set my tteadmill to 0 speed, the lowest possible is 0.8km/h. The 0 speed you see must be when i stop (pause) the treadmill!?

yes i guess so. in that case we need to handle a start, but let's put one problem in the fire at one time :)

> 
> When it is in pause mode the workout automatically started with the test workout of @victorypoint, my custom workouts haven't done. 

ok but if you don't press pause or stop on the treadmill, is the custom workout executed correctly? if not can you share a debug log with only a simple custom workout with only speed changes that doesn't work?

**Comment by afitz85** [comment]
ok, now i get an older version and workouts are still working the same as they did yesterday.

[debug-Sa__Jän_27_08_19_59_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14071465/debug-Sa__Jan_27_08_19_59_2024.log)

now my treadmill was running at 3.5km/h and i started my custom workout without incline, there nothing happens, no speed changes. Then i startet (while the treadmill was sill running) the Test Workout of @victorypoint  from yesterday and it worked the same as it did yesterday. speed was just changed when the incline was changed. But in the second workout step just the incline changes, no speed was changed!? The next steps worked then again.

BUT i haven't tried the new zwift-workout.py file yet... that's im gona do now.

**Comment by cagnulein** [comment]
@afitz85 i guess there is some confusion in the terms :D when i'm talking about custom workouts, i'm talking about loading a zwo file directly in qz.
Instead, in this log, I see that you are using zwift OCR for the workout, isn't it?

So in order to address the speed issue, just load a simple zwo file that you can create from http://80.211.67.253:8081/training.htm?fbclid=IwAR07s1MGtk-xjNPZDj_vsE89PEUqv6D5ycffYmNxDUqax8rD0bbdMFpqDLg

so i can understand if there is any issue with the speed at all in your treadmill.

also another question: which is the minium speed step that your treadmill can change? 0.5km/h? 0.1 km/h?

**Comment by afitz85** [comment]
oh ok... i created mine in zwiftworkout.com and put the zwo file in the workoutsfolder from zwift. i started all the workouts i tried now directly from zwift!?

What is zwift OCR? :)

with this link i created a fast workout now, but i get no zwo file, i get a xml
![1](https://github.com/cagnulein/qdomyos-zwift/assets/157009794/b96bcc32-025c-45cf-b822-ab1c4e7a50ed)

ok, so where i have to put the zwo file in qz? In the Trainings folder?
And it's not possible to start and run a workout directly from zwift, i always have to start it from qz?

i can set miy speed in 0.1km/h steps yes.

**Comment by afitz85** [comment]
> @afitz85, when you get things working again, I have a fix for the workout speed and incline for you to test please. Download the attached, unzip, and copy the zwift-workout.py file inside your QZ folder overwriting the old one. Test a workout and let us know!
> 
> [zwift-workout.zip](https://github.com/cagnulein/qdomyos-zwift/files/14069273/zwift-workout.zip)

[debug-Sa__Jän_27_08_33_24_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14071537/debug-Sa__Jan_27_08_33_24_2024.log)

i tried it now with this...
my custom workout (created with zwiftworkout.com and directly startet in zwift) doesn't work at all as before, but in the first workout step the speed of the treadmill (3.5km/h) was set to the minimum speed of the treadmill (0.8km/h) instead of 4.5km/h (i think) it should from the workout.

and your test workout from yesterday now just changes inclines, no speed at all anymore :(

**Comment by afitz85** [comment]
[debug-Sa__Jän_27_08_53_56_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14071551/debug-Sa__Jan_27_08_53_56_2024.log)

now i run the workout test from @victorypoint and my custom workout directly in qz app.
here the workout test just changes speed, but no incline

and my custom workout works so far as it looks, it changes speed correctly. But i also tried the first step because it's a longer workout... but i can also try shorter steps if you want again?

**Comment by cagnulein** [comment]
> oh ok... i created mine in zwiftworkout.com and put the zwo file in the workoutsfolder from zwift. i started all the workouts i tried now directly from zwift!?

yes this is how it should work with the OCR code from @victorypoint 
but let's first understand the speed issue with a classic xml file

> 
> What is zwift OCR? :)

the techinque that @victorypoint uses to get the speed and incline from treadmill

> 
> with this link i created a fast workout now, but i get no zwo file, i get a xml ![1](https://private-user-images.githubusercontent.com/157009794/300163850-b96bcc32-025c-45cf-b822-ab1c4e7a50ed.JPG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYzNDI2NTUsIm5iZiI6MTcwNjM0MjM1NSwicGF0aCI6Ii8xNTcwMDk3OTQvMzAwMTYzODUwLWI5NmJjYzMyLTAyNWMtNDVjZi1iODIyLWFiMWM0ZTdhNTBlZC5KUEc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyN1QwNzU5MTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yNjJjMGQxM2YyNzgwOTY0YzY5NzNhNmEyMzEwNjhhNmY5ZDg2YTc2ZWQ2MTA1ZGM4ZGRhNjAzZTg2MDY0MGUzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.JizQBbT2yU4SkeaoAlcSZ9Np-KyRVNERIHXfSl9lQWo)
> 
> ok, so where i have to put the zwo file in qz? In the Trainings folder? And it's not possible to start and run a workout directly from zwift, i always have to start it from qz?

just put wherever you want and from the training program window of qz, click other folder and select it. yes you can do it then from zwift, this is just an example to understand your speed issue. just to simpify the enviroment

> 
> i can set miy speed in 0.1km/h steps yes.

ok

**Comment by cagnulein** [comment]
> [debug-Sa__Jän_27_08_53_56_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14071551/debug-Sa__Jan_27_08_53_56_2024.log)
> 
> now i run the workout test from @victorypoint and my custom workout directly in qz app. here the workout test just changes speed, but no incline
> 
> and my custom workout works so far as it looks, it changes speed correctly. But i also tried the first step because it's a longer workout... but i can also try shorter steps if you want again?

i checked this log and the speed is working, check for example this

```
Sa. Jän 27 08:55:04 2024 1706342104295 Debug: bluetooth.cpp void bluetooth::debug(const QString&) "Current Speed: 0.25"
Sa. Jän 27 08:55:04 2024 1706342104957 Debug: trainprogram.cpp void trainprogram::scheduler() "trainprogram change speed7.74"
Sa. Jän 27 08:55:04 2024 1706342104961 Debug: treadmill.cpp virtual void treadmill::changeSpeed(double) changeSpeed 8.29 true 1 0 7.74
Sa. Jän 27 08:55:06 2024 1706342106327 Debug: bluetooth.cpp void bluetooth::debug(const QString&) "Current Speed: 7.73"
```

can you see it? it changes. which is the issue are you referiing? I don't understand

**Comment by cagnulein** [comment]
@afitz85 wait let's explain everything from the scratch.

Zwift workout: you can have zwift workout without the needing of opening in qz with the @victorypoint python files. So you don't have to load anything in qz. Just run the zwift workout in zwift on the same pc

QZ workout: when you are loading a file on qz, this is taking the control, so you can't load a file and also have zwift open with OCR enabled.

**Comment by afitz85** [comment]
so now i run this in qz (i created it with zwiftworkout.com (just speed changes, no incline) - and it worked!
![1](https://github.com/cagnulein/qdomyos-zwift/assets/157009794/001e473d-6ad4-4f95-aa12-7006b0373f4a)
[debug-Sa__Jän_27_09_19_43_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14071654/debug-Sa__Jan_27_09_19_43_2024.log)


the XML file (from before) doesn't change speeds, but it changes the incline in the last step
[debug-Sa__Jän_27_09_22_27_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14071655/debug-Sa__Jan_27_09_22_27_2024.log)

**Comment by afitz85** [comment]
> > [debug-Sa__Jän_27_08_53_56_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14071551/debug-Sa__Jan_27_08_53_56_2024.log)
> > now i run the workout test from @victorypoint and my custom workout directly in qz app. here the workout test just changes speed, but no incline
> > and my custom workout works so far as it looks, it changes speed correctly. But i also tried the first step because it's a longer workout... but i can also try shorter steps if you want again?
> 
> i checked this log and the speed is working, check for example this
> 
> ```
> Sa. Jän 27 08:55:04 2024 1706342104295 Debug: bluetooth.cpp void bluetooth::debug(const QString&) "Current Speed: 0.25"
> Sa. Jän 27 08:55:04 2024 1706342104957 Debug: trainprogram.cpp void trainprogram::scheduler() "trainprogram change speed7.74"
> Sa. Jän 27 08:55:04 2024 1706342104961 Debug: treadmill.cpp virtual void treadmill::changeSpeed(double) changeSpeed 8.29 true 1 0 7.74
> Sa. Jän 27 08:55:06 2024 1706342106327 Debug: bluetooth.cpp void bluetooth::debug(const QString&) "Current Speed: 7.73"
> ```
> 
> can you see it? it changes. which is the issue are you referiing? I don't understand

yes, the speed changes were correct, but the incline was ignored

**Comment by afitz85** [comment]
[debug-Sa__Jän_27_09_37_10_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14071678/debug-Sa__Jan_27_09_37_10_2024.log)
tested a second xml file with a workout created on your suggested site, and here also the incline works sometimes (not every time !?), and speed doesn't change at all.
![1](https://github.com/cagnulein/qdomyos-zwift/assets/157009794/371c3443-ba80-409d-afc2-ba382e11beb4)


but as said, the ones from zwiftworkout.com are working well so far in qz app (they are without incline)

**Comment by cagnulein** [comment]
i'm hanging out with my family, i will check this in the next days
thanks

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno sab 27 gen 2024 alle 09:41 afitz85 ***@***.***> ha
scritto:

**Comment by afitz85** [comment]
[debug-Sa__Jän_27_09_42_30_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14071689/debug-Sa__Jan_27_09_42_30_2024.log)
![2](https://github.com/cagnulein/qdomyos-zwift/assets/157009794/c241e5fc-d0d0-43a5-92a3-208469312563)

finally, the workout from before that worked directly in the qz app, doesn't work from when i start in in zwift

**Comment by cagnulein** [comment]
> [debug-Sa__Jän_27_09_37_10_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14071678/debug-Sa__Jan_27_09_37_10_2024.log) tested a second xml file with a workout created on your suggested site, and here also the incline works sometimes (not every time !?), and speed doesn't change at all. ![1](https://private-user-images.githubusercontent.com/157009794/300166862-371c3443-ba80-409d-afc2-ba382e11beb4.JPG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY0MjU1OTEsIm5iZiI6MTcwNjQyNTI5MSwicGF0aCI6Ii8xNTcwMDk3OTQvMzAwMTY2ODYyLTM3MWMzNDQzLWJhODAtNDA5ZC1hZmMyLWJhMzgyZTExYmViNC5KUEc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyOFQwNzAxMzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iNGRiNGYyYTdlNzZhMDFmNmVkMmEyY2E2YTliZTkxYWQ5MmYyNzM0YzM2ODk0NjhkN2ViNDVmYzJiOTU2NDY4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.f0OQSTI27Pm0Z5ZygTL8Az44ZGViyjzZrGcQfJrxMHE)
> 
> but as said, the ones from zwiftworkout.com are working well so far in qz app (they are without incline)

the problem here is that you set the forcespeed to 0. put it to 1

**Comment by cagnulein** [comment]
> [debug-Sa__Jän_27_09_42_30_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14071689/debug-Sa__Jan_27_09_42_30_2024.log) ![2](https://private-user-images.githubusercontent.com/157009794/300167166-c241e5fc-d0d0-43a5-92a3-208469312563.JPG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY0MjU1OTEsIm5iZiI6MTcwNjQyNTI5MSwicGF0aCI6Ii8xNTcwMDk3OTQvMzAwMTY3MTY2LWMyNDFlNWZjLWQwZDAtNDNhNS05MmEzLTIwODQ2OTMxMjU2My5KUEc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyOFQwNzAxMzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jODViNTg1OGQ0MjM5ZGM1MjkzYzFlNWVlZjMwNWIyNmUyZDA5YmExMTQzZmUzNGM2ZjNhMmI4YTE5MzJhM2ZjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.KgnUvFtylSt97W3NS2aqNcbte_RZ-z_wegS_kHgbcmc)
> 
> finally, the workout from before that worked directly in the qz app, doesn't work from when i start in in zwift

@victorypoint i can see the output correctly

```
Sa. Jän 27 09:45:05 2024 1706345105327 Debug: bluetooth.cpp void bluetooth::debug(const QString&) "python << OUT run at 8.8 kph for 20 sec \r\n8.8;None\r\n"
un >>  "zwift-workout.py"
Sa. Jän 27 09:45:05 2024 1706345105334 Debug: bluetooth.cpp void bluetooth::debug(const QString&) "python << ERR "
Sa. Jän 27 09:45:05 2024 1706345105336 Debug: bluetooth.cpp void bluetooth::debug(const QString&) "windows_zwift_workout_paddleocr_thread onInclination None\r\n onSpeed \u0000"
```

but probably this is too much `run at 8.8 kph for 20 sec \r\n`

did you add it for debug?

@afitz85 anyway good news, @victorypoint seems very near to the solution!

**Comment by afitz85** [comment]
> > [debug-Sa__Jän_27_09_37_10_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14071678/debug-Sa__Jan_27_09_37_10_2024.log) tested a second xml file with a workout created on your suggested site, and here also the incline works sometimes (not every time !?), and speed doesn't change at all. ![1](https://private-user-images.githubusercontent.com/157009794/300166862-371c3443-ba80-409d-afc2-ba382e11beb4.JPG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY0MjU1OTEsIm5iZiI6MTcwNjQyNTI5MSwicGF0aCI6Ii8xNTcwMDk3OTQvMzAwMTY2ODYyLTM3MWMzNDQzLWJhODAtNDA5ZC1hZmMyLWJhMzgyZTExYmViNC5KUEc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyOFQwNzAxMzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iNGRiNGYyYTdlNzZhMDFmNmVkMmEyY2E2YTliZTkxYWQ5MmYyNzM0YzM2ODk0NjhkN2ViNDVmYzJiOTU2NDY4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.f0OQSTI27Pm0Z5ZygTL8Az44ZGViyjzZrGcQfJrxMHE)
> > but as said, the ones from zwiftworkout.com are working well so far in qz app (they are without incline)
> 
> the problem here is that you set the forcespeed to 0. put it to 1

Ah ok... I just let it as it was
![Screenshot_20240128_080514](https://github.com/cagnulein/qdomyos-zwift/assets/157009794/c9114ad7-4168-44b0-b6c2-c401f916564c)

**Comment by afitz85** [comment]
> > [debug-Sa__Jän_27_09_42_30_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14071689/debug-Sa__Jan_27_09_42_30_2024.log) ![2](https://private-user-images.githubusercontent.com/157009794/300167166-c241e5fc-d0d0-43a5-92a3-208469312563.JPG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY0MjU1OTEsIm5iZiI6MTcwNjQyNTI5MSwicGF0aCI6Ii8xNTcwMDk3OTQvMzAwMTY3MTY2LWMyNDFlNWZjLWQwZDAtNDNhNS05MmEzLTIwODQ2OTMxMjU2My5KUEc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyOFQwNzAxMzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jODViNTg1OGQ0MjM5ZGM1MjkzYzFlNWVlZjMwNWIyNmUyZDA5YmExMTQzZmUzNGM2ZjNhMmI4YTE5MzJhM2ZjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.KgnUvFtylSt97W3NS2aqNcbte_RZ-z_wegS_kHgbcmc)
> > finally, the workout from before that worked directly in the qz app, doesn't work from when i start in in zwift
> 
> @victorypoint i can see the output correctly
> 
> ```
> Sa. Jän 27 09:45:05 2024 1706345105327 Debug: bluetooth.cpp void bluetooth::debug(const QString&) "python << OUT run at 8.8 kph for 20 sec \r\n8.8;None\r\n"
> un >>  "zwift-workout.py"
> Sa. Jän 27 09:45:05 2024 1706345105334 Debug: bluetooth.cpp void bluetooth::debug(const QString&) "python << ERR "
> Sa. Jän 27 09:45:05 2024 1706345105336 Debug: bluetooth.cpp void bluetooth::debug(const QString&) "windows_zwift_workout_paddleocr_thread onInclination None\r\n onSpeed \u0000"
> ```
> 
> but probably this is too much `run at 8.8 kph for 20 sec \r\n`
> 
> did you add it for debug?
> 
> @afitz85 anyway good news, @victorypoint seems very near to the solution!

Great to here 👍🏻💪🏻

**Comment by cagnulein** [comment]
> > > [debug-Sa__Jän_27_09_37_10_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14071678/debug-Sa__Jan_27_09_37_10_2024.log) tested a second xml file with a workout created on your suggested site, and here also the incline works sometimes (not every time !?), and speed doesn't change at all. ![1](https://private-user-images.githubusercontent.com/157009794/300166862-371c3443-ba80-409d-afc2-ba382e11beb4.JPG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY0MjU1OTEsIm5iZiI6MTcwNjQyNTI5MSwicGF0aCI6Ii8xNTcwMDk3OTQvMzAwMTY2ODYyLTM3MWMzNDQzLWJhODAtNDA5ZC1hZmMyLWJhMzgyZTExYmViNC5KUEc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyOFQwNzAxMzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iNGRiNGYyYTdlNzZhMDFmNmVkMmEyY2E2YTliZTkxYWQ5MmYyNzM0YzM2ODk0NjhkN2ViNDVmYzJiOTU2NDY4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.f0OQSTI27Pm0Z5ZygTL8Az44ZGViyjzZrGcQfJrxMHE)
> > > but as said, the ones from zwiftworkout.com are working well so far in qz app (they are without incline)
> > 
> > 
> > the problem here is that you set the forcespeed to 0. put it to 1
> 
> Ah ok... I just let it as it was ![Screenshot_20240128_080514](https://private-user-images.githubusercontent.com/157009794/300244181-c9114ad7-4168-44b0-b6c2-c401f916564c.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY0MjYwMDcsIm5iZiI6MTcwNjQyNTcwNywicGF0aCI6Ii8xNTcwMDk3OTQvMzAwMjQ0MTgxLWM5MTE0YWQ3LTQxNjgtNDRiMC1iNmMyLWM0MDFmOTE2NTY0Yy5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyOFQwNzA4MjdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xNDk5MTRlMDY1ZjkzNWMxOTlmYWU3MGE3OThmNDE3ZDE2YmE2YzQ5YWU2ZmMxZmUxMjRlZDg0NjU0NWZiMzczJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.qFdSuNLsJABygB3SSOCXycdJ6KDwPyl_SywicF6giTg)

yes you have to enable it, by default is off for safety reason :)

**Comment by victorypoint** [comment]
@afitz85, can you upload some of your custom workouts here that your've created? I can test them on my TM and confirm.

**Comment by afitz85** [comment]
Yes of course, but i can't upload them here, should i mail it to you?

**Comment by cagnulein** [comment]
> Yes of course, but i can't upload them here, should i mail it to you?

zip them

**Comment by afitz85** [comment]
[zwiftworkout test.zip](https://github.com/cagnulein/qdomyos-zwift/files/14077639/zwiftworkout.test.zip)

**Comment by victorypoint** [comment]
@afitz85, I tested your three custom workouts and they work fine on my treadmill. I've saved a video showing how onr workout progresses with speed changes.

https://www.dropbox.com/scl/fi/u7drruis0x3d9ed9o2z4v/lv_0_20240129122336.mp4?rlkey=3d4rxpl1uduuyeradzznebhd7&dl=0

**Comment by afitz85** [comment]
Any update to this?

**Comment by cagnulein** [comment]
@afitz85 @victorypoint Is in vacation till the mid of February. Anyway you have only to load his scripts replacing the default ones of qz. Did you already try this?

**Comment by cagnulein** [comment]
@afitz85 The attachment here https://github.com/cagnulein/qdomyos-zwift/issues/2042#issuecomment-1912679905

**Comment by afitz85** [comment]
https://github.com/cagnulein/qdomyos-zwift/issues/2042#issuecomment-1913061494

![Screenshot_20240130_220218_com android chrome](https://github.com/cagnulein/qdomyos-zwift/assets/157009794/33e66a44-0377-4294-95a4-9d98ec13a96a)

Oh that i tried, but it didn't work!?

**Comment by cagnulein** [comment]
Ok I will check the log if the issue was on the python side or in the qz side

**Comment by cagnulein** [comment]
log checked the first step of the workout is 

`Sa. Jän 27 08:36:13 2024 1706340973908 Debug: bluetooth.cpp void bluetooth::debug(const QString&) "python << OUT run at 8.8 kph for 400m \r\n8.8;None\r\n"`

so OCR is getting right but the problem is that it's not incapsulating correctly for qz (speed;inclination).

Are you sure that you used the new python files from @victorypoint ?

If so, we have to wait the end of februrary for @victorypoint 
Also Zwift seems that they will add FTMS control for the treadmill on June so maybe we could wait them.

Let me know!

**Comment by afitz85** [comment]
> log checked the first step of the workout is
> 
> `Sa. Jän 27 08:36:13 2024 1706340973908 Debug: bluetooth.cpp void bluetooth::debug(const QString&) "python << OUT run at 8.8 kph for 400m \r\n8.8;None\r\n"`
> 
> so OCR is getting right but the problem is that it's not incapsulating correctly for qz (speed;inclination).
> 
> Are you sure that you used the new python files from @victorypoint ?

yes, I replaced the original file with this one... but i will give it another try in the evening.

> 
> If so, we have to wait the end of februrary for @victorypoint Also Zwift seems that they will add FTMS control for the treadmill on June so maybe we could wait them.

ok no problem.

really? makes sense because of the wahoo kickr run treadmill

**Comment by cagnulein** [comment]
> ok no problem.
> 
> really? makes sense because of the wahoo kickr run treadmill

yes because has already the kickr run protocol :)

**Comment by afitz85** [comment]
[debug-Mi__Jän_31_16_47_11_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14113992/debug-Mi__Jan_31_16_47_11_2024.log)

i replaced the zwift-workout.py once more but i'm sorry, it didn't work. same result as before.

maybe @victorypoint forgot to post the actual now working file he was working on!?
the one he posted (and i actually tried) was two days older than his post that it worked on his treadmill...

**Comment by cagnulein** [comment]
@afitz85 i guess i got the issue
try this

[zwift-workout.zip](https://github.com/cagnulein/qdomyos-zwift/files/14114261/zwift-workout.zip)

**Comment by cagnulein** [comment]
for reference i just removed the 

print(ocr_text) 

line

**Comment by afitz85** [comment]
Yessa, it works!
I just tried it quickly, but with 3 different workouts (also warm-up ramps) and it looks good so far... should i find any problems i will let it you know.

Great! Thank you!!!

**Comment by afitz85** [comment]
[debug-Mi__Jän_31_17_26_35_2024.log](https://github.com/cagnulein/qdomyos-zwift/files/14114550/debug-Mi__Jan_31_17_26_35_2024.log)
... if you need the debug

**Comment by afitz85** [comment]
> @afitz85 done https://github.com/cagnulein/qdomyos-zwift/actions/runs/7670262351

![1](https://github.com/cagnulein/qdomyos-zwift/assets/157009794/be12a657-e4d8-4e8a-8c4e-eef7901a7573)


what came in my mind, just to be sure...
this was your version that doesn't work ( https://github.com/cagnulein/qdomyos-zwift/actions/runs/7670262351 ), where i went back to the last working older version

in all the newer versions now, this "wrong solution" isn't implimented isn't it? :)

**Comment by cagnulein** [comment]
> in all the newer versions now, this "wrong solution" isn't implimented isn't it? :)

correct, i dropped it. I'm adding the new python file in the master now so you can try directly the new package

**Comment by cagnulein** [comment]
new build is building https://github.com/cagnulein/qdomyos-zwift/actions/runs/7737795902

this must work without changing anything! let me know!

**Comment by afitz85** [comment]
> new build is building https://github.com/cagnulein/qdomyos-zwift/actions/runs/7737795902
> 
> this must work without changing anything! let me know!

just for info... yes, it works all fine here.

**Comment by cagnulein** [comment]
great! So can I close this?

**Comment by afitz85** [comment]
From my side yes, thank you 👍🏻

**Comment by afitz85** [comment]
> h
hello,
tried a workout again today, but didn't work very well... some workout steps (always when to switch to higher speed) are just ignored!? May you see something in the debug file... and here is my created workout also. But i tried also zwift original workouts. Thank you.
[debug-Do__Nov_14_16_28_33_2024.zip](https://github.com/user-attachments/files/17753821/debug-Do__Nov_14_16_28_33_2024.zip)
@cagnulein

**Comment by cagnulein** [comment]
@afitz85 please share the workout file that you used

**Comment by afitz85** [comment]
[workoutfile.zip](https://github.com/user-attachments/files/17754220/workoutfile.zip)
sorry

**Comment by afitz85** [comment]
but i also tried a zwift original workout

**Comment by cagnulein** [comment]
Where did you get this file? Also which segment are not respected?

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno gio 14 nov 2024 alle 18:38 afitz85 ***@***.***> ha
scritto:

**Comment by afitz85** [comment]
> Where did you get this file? Also which segment are not respected? 

i created it with intervals.icu ... the steps to 12.8km/h (the steps with hightest speed)

**Comment by cagnulein** [comment]
Ok I will check it out

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno gio 14 nov 2024 alle 18:45 afitz85 ***@***.***> ha
scritto:

**Comment by cagnulein** [comment]
Do you mean this one it's the one that it's not working

IntervalsT OnPower="1.0" OffPower="0.8" show_avg="1" Repeat="3"
OffDuration="140" OnDuration="112">

?

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno gio 14 nov 2024 alle 18:47 cagnulein ***@***.***> ha
scritto:

**Comment by afitz85** [comment]
Yes

**Comment by cagnulein** [comment]
Your qz version is quite old. Did you try with the latest build?

**Comment by cagnulein** [comment]
Ok I will check if I already fixed this so

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno gio 14 nov 2024 alle 19:43 afitz85 ***@***.***> ha
scritto:

**Comment by cagnulein** [comment]
With the latest version i just tried this and it worked 
[Fartlek_2 2.zwo.zip](https://github.com/user-attachments/files/17773701/Fartlek_2.2.zwo.zip)
try and if it's not working on your version please upgrade it and you will solve it
Let me know!

**Comment by afitz85** [comment]
[debug-Fr__Nov_15_14_42_21_2024.log](https://github.com/user-attachments/files/17776384/debug-Fr__Nov_15_14_42_21_2024.log)

i updated to 2.18.5 and tried it out... but the workout step to 12.8km/h still doesn't work. the speed from the treadmill stays the same as the step before. can you see anything in the debug?

+ i saw a new setting "Add inclination gain factor to the power". What exactly is this for? if it's enabled the power i see in QZ is shown higher because of inclination, and if it's disabled the power stays the same also if i add inclination to the treadmill?

Thanks for your help.

**Comment by cagnulein** [comment]
Thanks, I will check it ASAP

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno ven 15 nov 2024 alle 14:58 afitz85 ***@***.***> ha
scritto:

**Comment by cagnulein** [comment]
Thanks @victorypoint I guess it's more an issue on my side in case

**Comment by cagnulein** [comment]
@afitz85 i just tried again and it worked for me. Unfortunately in the log that you sent me there isn't a session where you open the train program from qz. Are you sure about the debug log? are you loading it from the training program in qz?
Let me know

**Comment by afitz85** [comment]
i'm starting/doing the workout directly in zwift, as i always did before.
Back in february 2024 as i lastly did treadmill workouts, i always did it that way and all worked fine.
Could it be that the workout step to a higher speed is ignored because of saftey reasons!? :) ... all the other steps are working i would say. But it's also the case that the treadmill doesn't jump to high speed steps, nor does it go back to the slower speed step when I run at high speed (set manually).
I'll try another workout tomorrow. Maybe I'll know more tomorrow.
Thank's for your help!

**Comment by cagnulein** [comment]
hah so you are loading the file there! i didn't get this / didn't remember abot this. So in Zwift do you see the workout correctly first of all?

**Comment by afitz85** [comment]
yes, everything looks correct in zwift.

**Comment by cagnulein** [comment]
maybe @afitz85 the screen UI of zwift changes when you are doing this fraction of the file? maybe it's slightly different from the original one? 

ok now I understand why @victorypoint offers to help :) in this case yes @victorypoint if you want to try the same zwo file (you can use https://github.com/user-attachments/files/17773701/Fartlek_2.2.zwo.zip that it's a reducted one) it will be very helpful!

thanks

**Comment by cagnulein** [comment]
i mean since everything in this case ishandled by recording the screen and parse it, if there is a UI change in the zwift UI when you are doing this fraction, the OCR engine that @victorypoint did, it could be have an unhandled case.

**Comment by victorypoint** [comment]
Hi guys. @cagnulein, during all my iFit2 testing, I updated the python scripts for auto-incline, climb portal, and workouts. Zwift changed UI elements which affected crops and colours. They are uploaded at https://gist.github.com/victorypoint.

**Comment by cagnulein** [comment]
thanks @victorypoint i was checking the zwift-workout.py used from @afitz85 but it was using paddleocr, instead now your file here https://gist.github.com/victorypoint/ace58f0bc68cf46f8b8afb3bd3c9d109 it's using the AI.server (i guess @afitz85 doesn't have). Do you suggest to use directly this? is the ai server binary on qz ready to use for this or he has to install something also?

**Comment by victorypoint** [comment]
@cagnulein, we can simply replace the ai.server lines with paddleocr. I will do that later today. Either way it will work.

**Comment by cagnulein** [comment]
it was just to reduce to the minimum the differences for @afitz85

**Comment by victorypoint** [comment]
@cagnulein, here are the updated python scripts to include with QZ. Let me know if you need anything else.

[new_python.zip](https://github.com/user-attachments/files/17848125/new_python.zip)

**Comment by cagnulein** [comment]
@victorypoint thanks
i checked and in the zwift-workout file the only thing changed is

if "kph" in ocr_text.lower():

to 

if "for" in ocr_text.lower():

i don't know if it will address the @afitz85 but it worth a try

@afitz85 can you replace the files in the @victorypoint zip into the qz windows folder (replacing the existing one)? It's important: you have to replace them

thanks

**Comment by afitz85** [comment]
Ok thanks, i will replace them tomorrow. 
what i can‘t do unfortunatly is to try the workout if it works, because of illness. It will take me some days to do 12+ kph 😅

**Comment by afitz85** [comment]
Just a beginner question to this to understand… zwift made little changes to the workout screen, and qz now can‘t visually „read“ the workout steps!?
But why can qz get the most steps right and some not (In my case the fastest steps)?

**Comment by cagnulein** [comment]
I don't know but since it's ocr everything is possible (it's not usual
coding :) it's visual computing)

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno ven 22 nov 2024 alle 06:50 afitz85 ***@***.***> ha
scritto:

**Comment by afitz85** [comment]
[debug-Do__Nov_28_16_49_28_2024.log](https://github.com/user-attachments/files/17950366/debug-Do__Nov_28_16_49_28_2024.log)
tested it now (with the new python files), but unfortunatly now no workout steps work so far. no changes in speed anymore!?

**Comment by afitz85** [comment]
[Test_Workout_QZ.zip](https://github.com/user-attachments/files/17950382/Test_Workout_QZ.zip)
this was the workout i created

**Comment by cagnulein** [comment]
yes i see all the

```
Do. Nov 28 16:56:01 2024 1732809361095 Debug: windows_zwift_workout_paddleocr_thread.cpp QString windows_zwift_workout_paddleocr_thread::runPython(QString) run >>  "zwift-workout.py"
Do. Nov 28 16:56:01 2024 1732809361113 Debug: devices/bluetooth.cpp void bluetooth::debug(const QString&) "python << OUT None;None\r\n"
```

i don't know if @victorypoint has time to check it. Unfortunately i'm overwhelmed by ticket

**Comment by victorypoint** [comment]
@afitz85, I have time to look at this. Can you catch me up? Do all the correct workout instructions appear when you tab through them in Zwift?

**Comment by afitz85** [comment]
Thanks. Yes all appears correctly as normal. Can‘t figure out any difference.
Here is my strava activity with a screenshot if it helps. 
https://strava.app.link/WbHGKAqvUOb

**Comment by victorypoint** [comment]
@afitz85, I just tested your zwo workout file. All the workout instructions are correctly communicated to my treadmill. Can you explain what exactly is not working for you?

Here's all the speed changes that were communicated to my treadmill. Note - the list shows current time, speed, incline. Also note - my speeds will be different than yours as my 10K Zwift pace is different:

```
15-39-04, 10.2;None
15-39-23, 11.7;None
15-40-05, 13.1;None
15-40-15, 14.6;None
15-40-18, 11.0;None
15-40-30, 14.6;None
15-40-43, 11.0;None
15-40-54, 14.6;None
15-41-08, 11.0;None
15-41-19, 14.6;None
15-41-23, 11.0;None
15-41-30, 15.1;None
15-41-36, 11.3;None
15-41-42, 15.1;None
15-41-58, 11.3;None
15-42-04, 11.0;None
15-42-15, 14.6;None
15-42-22, 15.3;None
15-42-39, 11.0;None
15-42-47, 14.6;None
15-42-53, 15.3;None
15-43-03, 11.0;None


```

**Comment by afitz85** [comment]
Ok. so i am on windows 10 and use my stryd as power/speed sensor. when a workout step starts my treadmill speed is set that my real stryd measured speed is correct (so maybe for a 10.0km/h, my treadmill runs at 10.7km/h).
With your old python files all worked good so far, till my fastest workout steps (think it was 13.8km/h), they were ignored!?
Now with your new python files no workout steps are working, treadmill speed stays the same all the time.
This is how i use a workout:
Starting zwift and do warm up with manual speed (no workout), after several minutes i start a workout in zwift while still running.

thanks for your time and help!

**Comment by victorypoint** [comment]
@afitz85, ok good to know. Attached is a new "zwift-workout.py" file to test with. Copy it to your QZ folder and replace the existing one. Then go ahead and run your Zwift workout. You don't have to run. Just start the workout, and while your avatar stands there, tab through all the workout steps (give about 5-10 seconds) between tabs). Once done, there will be a new "images" folder in your QZ folder. Zip that up and attach it here. Let me know how it goes

[zwift-workout.zip](https://github.com/user-attachments/files/17966368/zwift-workout.zip)

**Comment by afitz85** [comment]
i did that now... but there is no new "images" folder in my QZ folder? where exactly should it be?

**Comment by afitz85** [comment]
![2024-12-01](https://github.com/user-attachments/assets/84e0e5e3-6003-4e6d-91b8-8a2cfe5eabfe)
here is a screenshot of my workout... but think that's not what you are looking for :)

**Comment by afitz85** [comment]
does it make a difference what language i use in zwift? i'm using german, should i try english?

**Comment by victorypoint** [comment]
> does it make a difference which language i use in zwift? i'm using german, should i try english?

@afitz85, oh good question. I really don't know. Can you upload a QZ debug log of the workout session?

**Comment by afitz85** [comment]
[debug-So__Dez_1_09_46_26_2024.log](https://github.com/user-attachments/files/17969023/debug-So__Dez_1_09_46_26_2024.log)
here is the debug.
i'll try a workout now with zwift language english...
but as said... back in february 2023 all workouts worked well, and last week just the fastest workout setps (around 13.7km/h i think) doesn't work

**Comment by afitz85** [comment]
[debug-So__Dez_1_14_40_09_2024.zip](https://github.com/user-attachments/files/17969276/debug-So__Dez_1_14_40_09_2024.zip)
so i tried it and it doesn't work... no workout steps changed any speed... speed stays the same all the time
and again, no "image" folder is created.
here is my strava activity with pictures and video if it helps.
https://www.strava.com/activities/13023985278

thanks for your help!

**Comment by victorypoint** [comment]
@afitz85, ok so yes using German does affect this! Please use the new zwift-workout.py file attached (modified to accept both english and german) and upload the zipped images folder. Let me know how it goes.

[zwift-workout.zip](https://github.com/user-attachments/files/17969565/zwift-workout.zip)

**Comment by afitz85** [comment]
Ok i‘ll try this one with german. But unfortunatly the old one also with english it didn‘t work today!?

**Comment by afitz85** [comment]
Where do i find the images folder? In my QZ folder (where the python files are) is no images folder

**Comment by victorypoint** [comment]
@afitz85, yes it should be there. Please send a new QZ debug file.

**Comment by afitz85** [comment]
![image](https://github.com/user-attachments/assets/fd4595c9-94bc-450f-80a9-2a5619854d33)
@cagnulein just for interest, any news on this?

**Comment by cagnulein** [comment]
yes i implemented in the last android beta @afitz85 check this https://github.com/cagnulein/qdomyos-zwift/wiki/Can-Zwift-control-speed-and-or-inclination-of-my-treadmill%3F

read the thing about version 2.18.4 and above on android

**Comment by afitz85** [comment]
WOW! :)
so when i run zwift on my pc, and qz on my android device (called KICKR RUN), zwift controlls my treadmill (speed + incline), and this also in workouts?

**Comment by cagnulein** [comment]
Yes exactly!

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno lun 2 dic 2024 alle 12:36 afitz85 ***@***.***> ha
scritto:

**Comment by afitz85** [comment]
cool i'll try this out... how do i get the android 2.18.4 beta on my android device?
any plans on iOs for this?

**Comment by cagnulein** [comment]
This can work only on android. Join the beta here
https://play.google.com/apps/testing/org.cagnulen.qdomyoszwift

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno lun 2 dic 2024 alle 13:10 afitz85 ***@***.***> ha
scritto:

**Comment by afitz85** [comment]
Thank you, i'll test it.
Does it also work if i use the speed from my stryd in QZ? So automatically set the correct treadmill speed offset as i'm using it now, to match the "real" stryd speed. (Workout says 10.0km/h, treadmill is set to 10.8km/h so my stryd speed is 10.0km/h).
Sorry, i can't explain that better :-)

**Comment by cagnulein** [comment]
Zwift handles only inclination, speed is not handled (only read). For this
you still need the current OCR engine

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno lun 2 dic 2024 alle 13:36 afitz85 ***@***.***> ha
scritto:

**Comment by afitz85** [comment]
@victorypoint this one worked. but here and there were speed mistakes, but not often. one time for example it should be 11.8km/h but it was set at 1.8. one time it should be 12.8 (i think) but speed was set to 2.8, then to 5.1 and here it stayd... with the next step speed was set correct again.
here is my debug:
[debug-Mo__Dez_2_18_41_42_2024.log](https://github.com/user-attachments/files/17982085/debug-Mo__Dez_2_18_41_42_2024.log)
and here is the zip of the images folder:
https://1drv.ms/f/c/ddb7f7775b8b18d2/Eh2MQ7E72F1FuXKjYVWYwQ8BkjHvbom6oTHBYH3H7c6s9A?e=Us1vlw

**Comment by afitz85** [comment]
[zwift-18-45-59-full.zip](https://github.com/user-attachments/files/17982147/zwift-18-45-59-full.zip)
images are very big... here are some of them + the log file
the rest i hope worked with the onedrive link above!?

**Comment by victorypoint** [comment]
@afitz85, ok this is good progress! So there are speed mistakes because your Zwift is not full-screen which is a requirement for the OCR to work properly. In your images I see the Zwift titlebar which messes up the inclination detection. See an example of your screen below.

From the instructions: "Zwift has to be in Windowed mode (full screen mode will not work). Then use a tool that puts games in 'borderless windows' mode (removes the game titlebar, border, and any other border elements). There's many solutions out there but I've tested a popular one called 'Borderless Gaming' - https://www.techspot.com/downloads/7061-borderless-gaming.html. It loads as a tray app and puts Zwift into borderless mode each time it is started."

![zwift-18-45-24-full](https://github.com/user-attachments/assets/23bbec03-533a-42e4-92f2-5f1a72dda0e9)

**Comment by afitz85** [comment]
ok i understand, that makes sense, didn't know that.
i'll try a workout today with borderless windowed mode and tell you how it goes.
Thank you, great work!

**Comment by victorypoint** [comment]
@afitz85, I will fix the code later today so that you don't need to use borderless windowed mode. It used to work last year but recent Zwift updates broke it.

**Comment by afitz85** [comment]
i did a workout now with borderless windowed mode and all worked fine. just one time (i had many many steps) the speed didn't change, but that's ok i would say.
if it's not a big deal, it would be nice if it would also work without borderless (switching between proramms like youtube, netflix etc. could be easier).

and could you also please change the code, so that images are not saved anymore? my images folder is 26GB big after 1 hour run :-)

Big Thanks, great work from both of you!

**Comment by afitz85** [comment]
+++ i did it with zwift language english, just for information

**Comment by victorypoint** [comment]
@afitz85, ok that's excellent news. So I fixed the code so it will work without borderless window. I also removed the code that generates the debug images folder. You can go ahead and delete that images folder - not needed anymore. Please try this new version and let me know how it goes.

[zwift-workout.zip](https://github.com/user-attachments/files/17998742/zwift-workout.zip)

**Comment by victorypoint** [comment]
@afitz85, good catch! Attached is a new version with the German word fix. At this point, I don't know if the OCR engine will detect this word properly. Give it a test in German and let me know.

[zwift-workout.zip](https://github.com/user-attachments/files/18009025/zwift-workout.zip)

**Comment by afitz85** [comment]
i tried it now and it works with english in windowed mode + borderless windowed mode ... but german doesn't work at all.
but for me personally it's not a big deal... english is ok for me :)
Thanks.
[debug-Mi__Dez_4_17_36_13_2024.log](https://github.com/user-attachments/files/18011527/debug-Mi__Dez_4_17_36_13_2024.log)

**Comment by cagnulein** [comment]
No I don't think so @victorypoint  you already did a lot!

**Comment by afitz85** [comment]
For what exactly do you need the word „for“ or „für“?
Could this word also be „kph“, because that‘s the same in all languages except you use miles!?

**Comment by victorypoint** [comment]
> For what exactly do you need the word „for“ or „für“? Could this word also be „kph“, because that‘s the same in all languages except you use miles!?

It's the word used to parse the components of the workout instruction. I'll try a few more parsing ideas. Kph won't work because the OCR engine doesn't recognize it (It's too close to a little clock graphic which messes up the OCR).

**Comment by afitz85** [comment]
Ok, yeah the little clock is dramatically close to "kph" :-)
maybe the "ü" in "für" is a problem!? another idea for german could be "laufe" !?
![image](https://github.com/user-attachments/assets/c324196e-975d-41cd-b54c-8bed7aef4b22)

but as said, i'm fine with just english ;-)
