### ISSUE TITLE
iOS not connecting to NordicTrack x22i treadmill

### ISSUE THREAD

**Issue by tkakkos** [cagnulein/qdomyos-zwift#2407]
**Describe the bug**
I followed the procedure to connect to the treadmill with the QZ companion app running in the background. Permissions enabled in the settings. Many treadmill restarts do not permit a connection to the iOS app despite putting the correct ip address.

**To Reproduce**

**Expected behavior**

**Screenshots**
![IMG_2704 2](https://github.com/cagnulein/qdomyos-zwift/assets/81328589/b8a8afae-c825-4e90-821b-d7a527eda927)
![IMG_2705](https://github.com/cagnulein/qdomyos-zwift/assets/81328589/e543ec72-b731-45d8-b4e6-61d1b1831bf7)
![IMG_2706](https://github.com/cagnulein/qdomyos-zwift/assets/81328589/8c60569d-94b7-43d1-a5fc-97c75cfa313e)

**Smartphone (please complete the following information):**
 - Device: iPhone 14 Pro Max 
 - OS: iOS 17.5.1

**Append a debug log**

[debug-lun__juin_24_21_25_58_2024.log](https://github.com/user-attachments/files/15960551/debug-lun__juin_24_21_25_58_2024.log)

  
  
**Additional context**

**Comment by cagnulein** [comment]
thanks, i will check it tomorrow, 10pm here :)

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno lun 24 giu 2024 alle 21:49 tkakkos ***@***.***> ha
scritto:

**Comment by cagnulein** [comment]
@tkakkos log checked, the problem is that your wifi router is filtering the frames from the treadmill. Which wifi router are you using? can you try to use your phone as a access point for the treadmill instead? Let me know

**Comment by tkakkos** [comment]
Hello,

I connected the treadmill to my iPhone as hotspot and I still have the same problem, no connection. I attach the log file
My router is a Unifi Dream Machine Pro, I verified the settings and there is nothing preventing network clients to communicate with each other.

Thanks in advance

[debug-mar__juin_25_14_48_57_2024.log](https://github.com/user-attachments/files/15991150/debug-mar__juin_25_14_48_57_2024.log)

**Comment by cagnulein** [comment]
yeah the frames are not there. did you try to do a factory reset on the treadmill WITHOUT updating the ifit app and trying again? Something is preventing the UDP frames to reach the iphone.

**Comment by tkakkos** [comment]
I did a factory reset, the app connects now to the treadmill for some seconds reporting a speed of 2km/h and then it freezes, speed and incline do not update

[debug-mer__juin_26_19_57_14_2024.log](https://github.com/user-attachments/files/15993636/debug-mer__juin_26_19_57_14_2024.log)

**Comment by cagnulein** [comment]
ok that's a start, just to be sure, are you running the ifit app on top of
the treadmill tablet? you should use the manual workout

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mer 26 giu 2024 alle 20:15 tkakkos ***@***.***> ha
scritto:

**Comment by tkakkos** [comment]
Yes, iFit app is always running on top

**Comment by cagnulein** [comment]
ok that's strange because all other users with x22i don't have issue
reading on metrics.

anyway give it a try selecting on the companion app instead of x22i

- x7.5s
- 2950

reboot the treadmill after each try.
don't change any settings on ios side, there everything is fine

let me know

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mer 26 giu 2024 alle 20:28 tkakkos ***@***.***> ha
scritto:

**Comment by tkakkos** [comment]
So I tried the other profiles:
 - With the x7.5s profile the treadmill has the same problem I encounter with the x22i profile, speed and inclination reported just for some seconds and then it is not working
 - The x8.5s profile the treadmill reports perfectly speed and inclination but I cannot change them from the qz iOS app
 - With the 2950 (22km/h) profile, data are reported perfectly fine but speed changes directly to 10km/h with the first push in the speed + button in the app, inclination changes by 1% in place of 0,5%
I think that there is a problem with profiles as two profiles report fine the metrics, however I cannot control correctly speed and inclination with the iOS app.

Thanks in advance

**Comment by cagnulein** [comment]
that's a great news! it means that your treadmill has a different android base system. Ok i will create a new device profile in the companion to handle this. I will share the link shortly

**Comment by cagnulein** [comment]
@tkakkos could you please share the exact model of your treadmill so i will add this in the info in the companion app? Thanks!

**Comment by tkakkos** [comment]
It's a NordicTrack Commercial x22i (model: MalataMediatekArgon2) running Android 9.0.
To precise my last message, using the 2950 (22km/h) profile I can adjust inclination by 1% steps but clicking the plus or minus button for the speed does nothing appart simulating a click on the screen and bringing up the iFit menu. Pushing the + button for several seconds brings the speed directly to 10km/h. Lastly but with less importance, the fan button is not working.
Again thanks for your reactivity and help.

![tempImageWaunOw](https://github.com/cagnulein/qdomyos-zwift/assets/81328589/f0dea472-5324-4066-b772-a6ba191e4102)
![tempImageW89aq2](https://github.com/cagnulein/qdomyos-zwift/assets/81328589/68c625b1-6318-488f-a67d-12809d57894e)

**Comment by cagnulein** [comment]
Ok I will do this in the next days!

**Comment by cagnulein** [comment]
@tkakkos done https://github.com/cagnulein/QZCompanionNordictrackTreadmill/releases/download/3.3.45/QZCompanionNordictrackTreadmill.apk

select the new x22i v2 device in the companion and restart it.

If the coordinates are the same of the x22i it should also control correctly the speed and the inclination. Otherwise I will need the screenshot of the manual workout view with the sliders

let me know

**Comment by tkakkos** [comment]
Its reads correctly the data but it does not control speed and inclination.
I attach a screenshot of the manual workout view

![tempImagewXEWHp](https://github.com/cagnulein/qdomyos-zwift/assets/81328589/8dbf8b7a-40b4-427b-ac98-8a50f20fbf7c)

**Comment by cagnulein** [comment]
but do you see the touch event when you press the plus button on the tiles on qz? like you saw on the 2950 device for example?

**Comment by tkakkos** [comment]
After restarting the treadmill, speed button works 70% of the time by 0,4km/h to 0,5km/h increments, inclination button minus works at 0 degrees every time to -6 degrees but plus button doesn't work at 0 degrees. It starts to work at 3 degrees sometimes. I would say however that inclination does not work more often than it does.

[debug-ven__juin_28_09_46_00_2024.log](https://github.com/user-attachments/files/16026540/debug-ven__juin_28_09_46_00_2024.log)

**Comment by cagnulein** [comment]
ok it could be that the coordinates for your treadmill are different from the one that I already implemented for the x22i

use the script https://github.com/cagnulein/QZCompanionNordictrackTreadmill/blob/master/InstallPackage/adb-screenshot.bat to collect a screenshot directly from the monitor, i need the precise pixel coordinates.

Otherwise you can run the swipes command from adb to obtain the coordinates if the sliders are not linear.

**Comment by tkakkos** [comment]
Can you explain how I can do the screenshot from a Mac? When I run the ads-screenshot-mac.sh in Terminal I get the following error


<img width="1003" alt="Screenshot 2024-06-28 at 15 12 09" src="https://github.com/cagnulein/qdomyos-zwift/assets/81328589/e81260b8-feab-4c72-a000-77a9888f03c5">

**Comment by cagnulein** [comment]
you have to run the adb-screenshot-mac.sh from the folder directly

so first do the cd /Volumes/downloads/QZCompanion.....

and then run it

**Comment by tkakkos** [comment]
I open it inside the folder but I still have the same error

<img width="940" alt="Screenshot 2024-06-28 at 16 59 23" src="https://github.com/cagnulein/qdomyos-zwift/assets/81328589/1b0a710f-3585-4354-be69-4fb59a5eabaa">

**Comment by cagnulein** [comment]
The adb file is there? 
If so run 

chmod a+x adb

**Comment by tkakkos** [comment]
adb file is there, I ran the chmod a+x adb and still have the same problem..

<img width="2393" alt="Screenshot 2024-06-28 at 18 29 03" src="https://github.com/cagnulein/qdomyos-zwift/assets/81328589/d0f4a67d-ec84-4eb1-be85-d7a30c151e13">

**Comment by cagnulein** [comment]
I'm driving now. Talk to you soon

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno ven 28 giu 2024 alle 18:32 tkakkos ***@***.***> ha
scritto:

**Comment by cagnulein** [comment]
Run it with

./adb-screenshot-mwc.sh

**Comment by tkakkos** [comment]
Still the same.. 

<img width="2064" alt="Screenshot 2024-06-28 at 19 25 01" src="https://github.com/cagnulein/qdomyos-zwift/assets/81328589/4fa94aa4-cc7e-469c-9e0a-00ddc809b6ee">

**Comment by cagnulein** [comment]
Without open

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno ven 28 giu 2024 alle 19:26 tkakkos ***@***.***> ha
scritto:

**Comment by tkakkos** [comment]
Ok, that worked. Can you tell me how I can get the screenshot from the /sdcard folder?

<img width="830" alt="Screenshot 2024-06-28 at 19 47 35" src="https://github.com/cagnulein/qdomyos-zwift/assets/81328589/b3e3ee66-13ce-4ec9-9557-25c6504af6d6">

**Comment by tkakkos** [comment]
Sorry, I found it in the folder

![2024-06-28@19-45-36](https://github.com/cagnulein/qdomyos-zwift/assets/81328589/00e8ca1d-4287-4e83-94af-6318c0a7c60e)

**Comment by cagnulein** [comment]
Thanks, I'm away for the weekend, I will check next week.

Have a nice weekend

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno ven 28 giu 2024 alle 19:49 tkakkos ***@***.***> ha
scritto:

**Comment by tkakkos** [comment]
Thank you for your patience and your help.

Have a nice weekend too.

A. Kakkos

**Comment by cagnulein** [comment]
done @tkakkos https://github.com/cagnulein/QZCompanionNordictrackTreadmill/releases/download/3.3.46/QZCompanionNordictrackTreadmill.apk

let me know!

**Comment by cagnulein** [comment]
@tkakkos any news?
