### ISSUE TITLE
[BUG] Inclination stops updating in app after about 30 minutes (but treadmill adjustment still works)

### ISSUE THREAD

**Issue by kazuyoshifunaki** [cagnulein/qdomyos-zwift#2992]
**Describe the bug**
Using QZ with Zwift, on iPhone, on NordicTrack s20i treadmill

- While the update of the inclination still responds to changes in Zwift, the QZ iPhone app fails to update the display of the inclination after 25 - 30 minutes: It freezes at the latest inclination, until the treadmill is stopped, upon which the inclination updates.
- I have the "Add inclination gain factor to the power" activated. Unfortunately, the calculation also uses the "frozen" inclination as a basis, making the watt number invalid. 
- This error occurred in two instances now (the only two instances I ran over 30 minutes)

I haven't activated the debug log. What makes it difficult is that this mistakes only occurs after about 30 minutes. See attached screenshots. If the debug log is required, please let me know and I will activate it for my next run.

**To Reproduce**
- Run with QZ on Zwift for more than 30 minutes

**Expected behavior**

**Screenshots**
![Mon Jan 6 07_52_13 2025_speedInclination](https://github.com/user-attachments/assets/a1fe35e1-80b4-4145-909f-0b9bea34134b)
![Thu Jan 2 09_43_44 2025_speedInclination](https://github.com/user-attachments/assets/e8e89bff-e110-4a00-bedb-df73840e6ba5)

**Smartphone (please complete the following information):**
 - Device: iPhone 15Pro
 - OS: iOS 
 - Version 18.2

**Comment by cagnulein** [comment]
Hi please add a debug log from qz

**Comment by kazuyoshifunaki** [comment]
Here we go. Note that I accidentally used the iPad today, but the error still occurred.
[debug-Wed_Jan_8_06_24_57_2025.log](https://github.com/user-attachments/files/18343066/debug-Wed_Jan_8_06_24_57_2025.log)

**Comment by kazuyoshifunaki** [comment]
Just tested it and it still doesn’t work.
I ran about 25mins when I noticed it first time. See attached debug file. I tested version Version: 2.18 (993) on iPad

[debug-Fri_Jan_10_06_42_13_2025.log](https://github.com/user-attachments/files/18371458/debug-Fri_Jan_10_06_42_13_2025.log)

**Comment by cagnulein** [comment]
That's strange, I will check it 
Thanks

**Comment by cagnulein** [comment]
i guess i sent you the wrong version, i just send a newer one, could you please try again?

**Comment by kazuyoshifunaki** [comment]
Fantastic! It works now. I just ran a little bit more than 30 minutes and the inclination adjusted also on the dashboard period. Thank you so much
![Sat Jan 11 09_38_56 2025_speedInclination](https://github.com/user-attachments/assets/0f4ad4dd-70b6-4fe6-b316-84b48b944658)

I will close this bug.

**Comment by cagnulein** [comment]
That's great! Please remember to rate the app if you didn't already and also to join patreon if you can to support my work https://www.patreon.com/cagnulein

**Comment by kazuyoshifunaki** [comment]
Hi! 

A) I have noticed how suddenly the NordicTrack S20i is not selectable anymore. It automatically falls back onto Nordictrack S25. Is that by design?

B) I also noticed, how I cannot change the speed from the dashboard pressing the +/-. The incline changes work. I am wondering if this is connected to A). As far as I remember, this has never really worked. I have not tested this explicitly though, because I was more interested in the incline change.

C) I also added the speed preset tiles, but they seem to give completely strange speeds (it might be related to the heart rate PID though, so I don't put too much weight on this observation).

I can't tell when exactly I couldn't select S20i anymore and wonder whether this was introduced through some of the versions I got through TestFlight. I am on version 2.18.15 now.

**Comment by cagnulein** [comment]
I just sent a newer beta. There was an issue about the nordictrack
selection
Let me know if it's better now

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno dom 12 gen 2025 alle 22:28 kazuyoshifunaki <
***@***.***> ha scritto:

**Comment by kazuyoshifunaki** [comment]
I didnt get anything. Can you send again?

**Comment by cagnulein** [comment]
done!

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno lun 13 gen 2025 alle ore 07:28 kazuyoshifunaki <
***@***.***> ha scritto:

> I didnt get anything. Can you send again?

**Comment by kazuyoshifunaki** [comment]
Ok, update: The selection of Nordictrack S20i works now, but the behaviour is still strange:
- I did remove the PID on heart rate title just to remove that from the equation.1
- The + and - on the speed tile still does not work. It does simply nothing (which is the same behaviour I saw previously)
- I have presets for 6, 8, 9, 10 and 12 km/h and I went through each of them. Pressing sometimes gets to the speed I set up, but sometimes goes back to zero or walking speed? It is really strange and I don't see a pattern as to when it does it correctly and when not. I hope you can see what is happening in the debug files.

[debug-Mon_Jan_13_18_02_30_2025.log](https://github.com/user-attachments/files/18399916/debug-Mon_Jan_13_18_02_30_2025.log)

Note that I didn't have the time to actually run. So I am not sure if that has an impact, but it means that the data from my STRYD is zero Watts.

**Comment by cagnulein** [comment]
But does the speed tile ever worked? If not you have to collect an ifit log in this way https://ultrawyrypa.pl/index.php/2024/11/05/qz-fitness-connect-ifit-treadmil-to-zwift-and-not-only/

Let me know

**Comment by kazuyoshifunaki** [comment]
I don't think it ever worked. 
To do the logging thing, I will have to get back to you until I had the time - it seems very adventurous! I hope I do not need an iFit subscription? Because I don't have one

**Comment by cagnulein** [comment]
Nope you don't need any subscription

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno lun 13 gen 2025 alle 18:33 kazuyoshifunaki <
***@***.***> ha scritto:

**Comment by kazuyoshifunaki** [comment]
Ok, can't believe it went quite smooth. I was just waiting for a problem to occur, but no, following the description, all ok. 

Please find attached the log. I have first played with the inclination, and later, I altered the speed, first up to about 12km/h, and then all the way back. 

[Nordictracks20i bt snoop.log](https://github.com/user-attachments/files/18402178/Nordictracks20i.bt.snoop.log)

Hope this will give all the required data!

**Comment by cagnulein** [comment]
Thanks I will check it ASAP!

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno lun 13 gen 2025 alle 22:23 kazuyoshifunaki <
***@***.***> ha scritto:

**Comment by kazuyoshifunaki** [comment]
Hi Roberto, no pressure, but were you able to look into this? :-)

**Comment by cagnulein** [comment]
I was waiting the answer from @ptantot but in case I will create a new profile for you at this point

**Comment by cagnulein** [comment]
Anyway I have very busy days so it could take some days/week

**Comment by kazuyoshifunaki** [comment]
oh, ok. Yes absolutely no problem. Thanks much and - fingers crossed

**Comment by cagnulein** [comment]
done @kazuyoshifunaki i will send you the new version later today
let me know!

**Comment by cagnulein** [comment]
sent!

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno gio 16 gen 2025 alle ore 21:23 kazuyoshifunaki <
***@***.***> ha scritto:

**Comment by cagnulein** [comment]
you are using "Use speed from the power sensor". could you please disable for these tests? because we are mixing things with this enabled.

About the delay: do you have the same delay also with the original app when you change them from the app directly?

**Comment by kazuyoshifunaki** [comment]
You were right. With the speed from power meter disabled, the + - now worked.
The delay is now maybe half a second to a second. Strange. I guess I don’t mind the delay tbh :). 

I would really like to get the speed from the power meter though. I guess next time I run I can actually try it with the speed from power meter on.

**Comment by kazuyoshifunaki** [comment]
Question if https://github.com/cagnulein/qdomyos-zwift/issues/3030
Is something that could be done, without going through heart rate?

**Comment by cagnulein** [comment]
> I would really like to get the speed from the power meter though. I guess next time I run I can actually try it with the speed from power meter on.

yes you can do, but in this way we know that it was the issue with the step :)



> Question if [#3030](https://github.com/cagnulein/qdomyos-zwift/issues/3030) Is something that could be done, without going through heart rate?

yes as i said it's doable, but first of all check with the HR to check that's what you need :)

**Comment by kazuyoshifunaki** [comment]
Yes - will try!

Best wishes,
Ari

+41 78 207 61 65

**Comment by kazuyoshifunaki** [comment]
But stupid question, I don’t usually train with HR. I rely solely on power. Last time I activated my watch’s HR broadcast to test. I guess I will need this switched on or my HR will be 0 and this auto-adjustment wouldn’t work?

Best wishes,
Ari

+41 78 207 61 65

**Comment by cagnulein** [comment]
> I guess I will need this switched on or my HR will be 0 and this auto-adjustment wouldn’t work?

exactly

**Comment by kazuyoshifunaki** [comment]
Ok! Tested with "speed from power meter" switched off, and auto-speed by heart rate. 

I think the auto-adjustment for speed now works  (as do the "+" and "-" presses). I do find issues with either over-adjustments or too frequent adjustments, but again, the mechanic in general works following heart rate.

Now it would be great if I could do something similar with power. However, instead of following (and having to enter) power zones, I think it would be very elegant, if at any "incliniation change", the adjustment would take the average power e.g. for last 10 seconds and calculate an adjustment of speed. 

Then, whenever I manually change the speed, it would settle on a new power and from then on, this is my new base. 

Of course, maybe there's some tuning to be done as to how fast those adjustments happen, but the rough logic would be super cool!

**Comment by cagnulein** [comment]
Ok I will add a new setting for this
I will let you know when I will be ready to test it

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno sab 18 gen 2025 alle 10:14 kazuyoshifunaki <
***@***.***> ha scritto:

**Comment by kazuyoshifunaki** [comment]
Fantastic! Can't wait to test it :)

**Comment by cagnulein** [comment]
@kazuyoshifunaki done!

are you only on ios or are you able to test it also on android?
I added a new setting for this to enable under the traning program options

let me know!

**Comment by cagnulein** [comment]
sent!

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno lun 20 gen 2025 alle ore 10:29 kazuyoshifunaki <
***@***.***> ha scritto:

**Comment by kazuyoshifunaki** [comment]
Hi Roberto - unfortunately, nothing happened. I there was no strange behaviour or anything, but also no auto-adjustment.

Did I miss another setting? 
Debug file:
[

[debug-Tue_Jan_21_06_41_14_2025.log](https://github.com/user-attachments/files/18486326/debug-Tue_Jan_21_06_41_14_2025.log)

](url)

**Comment by cagnulein** [comment]
my fault, i missed 2 lines of code. i will send you another one later today hopefully

**Comment by cagnulein** [comment]
sent a new one!
let me know!

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mar 21 gen 2025 alle ore 08:33 kazuyoshifunaki <
***@***.***> ha scritto:

**Comment by kazuyoshifunaki** [comment]
Ok tested and here are my observations:

- strange start at the beginning, lots of small speed adjustment, but not really ramping up the speed. so it took many presses to get to actual speed. the adjustments seemed to override my button presses
- when at target speed/power, there was an adjustment that seemed to be sort of a vicious circle, really turning up the speed. I am not sure how fast it would have gone but I aborted.
- another time, the same happened, but went into a death spiral down to zero. 
- I have had to abort the workout after a while of trying

Couple of thoughts - maybe some of these are easy to implement:
- At the start of a run, there should be a timeout to allow the treadmill and runner to get up to target speed (and power) - maybe 60 seconds? 
- To add to that, a timeout should also be at every button press/manual adjustments. Maybe 10 - 15 seconds would be great. This would allow the power to adjust to a stable output. My guess is that the adjustment happens on data that has not fully adjusted yet which is then causing "death spirals"
- An as an additional thought: There should be a range that limits auto-adjustments to stay above a certain speed (to limit walking when incline increases to 8+ %), there should be an upper limit to avoid vicious circles to escalate beyond something like maybe 14km/h - this is more of a security feature)

Debug file:

**Comment by kazuyoshifunaki** [comment]
Can’t upload the log file..

**Comment by cagnulein** [comment]
Zip the file. I will check then

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mer 22 gen 2025 alle 07:38 kazuyoshifunaki <
***@***.***> ha scritto:

**Comment by kazuyoshifunaki** [comment]
[debug-Wed_Jan_22_06_04_57_2025.zip](https://github.com/user-attachments/files/18501035/debug-Wed_Jan_22_06_04_57_2025.zip)

Ohya… much better

**Comment by cagnulein** [comment]
Ok Thanks, I will check it, I'm away in these days

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mer 22 gen 2025 alle 07:44 kazuyoshifunaki <
***@***.***> ha scritto:

**Comment by cagnulein** [comment]
i got the issue, it's because you have the stryd also. i handled this edge case. I'm sending you a new one later today

**Comment by cagnulein** [comment]
yeah it was clear but i didn't test it in that scenario :)

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mer 22 gen 2025 alle ore 16:31 kazuyoshifunaki <
***@***.***> ha scritto:

**Comment by cagnulein** [comment]
new version sent!

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mer 22 gen 2025 alle ore 16:49 cagnulein ***@***.***> ha
scritto:

**Comment by kazuyoshifunaki** [comment]
Tested this morning.

There is something going on in terms of speed adjustment, but it is mostly upwards. I tried a few times in the beginning of the work out, had to switch it off, and did try again towards the end. 

The adjustment is mainly upwards and in all cases, no matter if the incline went up or down. It also meant that I ultimately ran really, really fast before I stopped it. 

Debug file attached.

[debug-Fri_Jan_24_08_19_14_2025.log.zip](https://github.com/user-attachments/files/18536867/debug-Fri_Jan_24_08_19_14_2025.log.zip)

**Comment by cagnulein** [comment]
ok thanks i will check it.

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno ven 24 gen 2025 alle ore 15:12 kazuyoshifunaki <
***@***.***> ha scritto:

**Comment by cagnulein** [comment]
argh i delete the email notification from my list, i will check this asap

**Comment by cagnulein** [comment]
@kazuyoshifunaki i was checking the log. for example

here 

`Fri Jan 24 08:28:09 2025 1737703689599 Debug: /Users/cagnulein/qdomyos-zwift/src/devices/treadmill.cpp bool treadmill::followPowerBySpeed() "changing speed to" 10.9 due to inclination changed 0 0.5`

qz was changing the speed from 9.9 to 10.9 because you changed inclination from 0.5 to 0%.
could you please make me an example of the sessiont that you feel not ok?

**Comment by cagnulein** [comment]
Yes please, because from my point of view it's working

Disable the auto inclination from zwift so you will be conscious about the
changes

Let me know

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mer 29 gen 2025 alle 19:07 kazuyoshifunaki <
***@***.***> ha scritto:

**Comment by kazuyoshifunaki** [comment]
So, I think here it is quite obvious:

![Image](https://github.com/user-attachments/assets/aa58a61f-2b5f-4992-bec5-97c9ec490b9e)

I set the speed to 8 km/h twice. You can see every time I add to the inclination, the speed actually goes up. In the first instance, it also goes down at some point, but the second time you can see how it just keeps going up, whether I press increase or decrease inclination. Obviously, it goes up when I decrease, but you can also see in the end, that I again increase the inclination, and it keeps going up.

[debug-Thu_Jan_30_07_54_10_2025.log](https://github.com/user-attachments/files/18598983/debug-Thu_Jan_30_07_54_10_2025.log)

**Comment by cagnulein** [comment]
yes i can see now the error. let me analyze it

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno gio 30 gen 2025 alle ore 08:37 kazuyoshifunaki <
***@***.***> ha scritto:

**Comment by cagnulein** [comment]
I guess I got it, it's because for the calculation of the new step range
i'm using the power calculation from the treadmill itself but instead you
have the stryd that reports a different calculation. This means that I
would have to collect a power table from the stryd to match it.
In order to validate this conclusion, please do a quick test without the
stryd. (disable it in the power sensor setting). If i'm right the speed
should change correctly then
let me know

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno gio 30 gen 2025 alle ore 10:14 cagnulein ***@***.***> ha
scritto:

**Comment by kazuyoshifunaki** [comment]
You were right. This way, it works. I didn't even know that there was a power calculation from the treadmill...

![Image](https://github.com/user-attachments/assets/106d0d0e-abc5-42c8-9565-8bbbf9096d95)

[debug-Thu_Jan_30_10_46_41_2025.log](https://github.com/user-attachments/files/18600578/debug-Thu_Jan_30_10_46_41_2025.log)

Obviously, it would be nice if the power and speed data both came from the Stryd - kind of why I have the sensor...

**Comment by cagnulein** [comment]
ok this is a great starting point! let me try to do a patch for this scenario too

**Comment by cagnulein** [comment]
done! i will send you a new one asap!

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno gio 30 gen 2025 alle ore 10:54 kazuyoshifunaki <
***@***.***> ha scritto:

**Comment by cagnulein** [comment]
sent!

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno gio 30 gen 2025 alle ore 11:27 cagnulein ***@***.***> ha
scritto:

**Comment by kazuyoshifunaki** [comment]
I will latest test tomorrow morning (but if time permits, very keen to try tonight!)

**Comment by cagnulein** [comment]
No rush! In this version I also handled setup where users don't have an
apple watch. I don't think it's your case but it will be a good test to
check that everything runs correctly too

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno gio 30 gen 2025 alle 13:08 kazuyoshifunaki <
***@***.***> ha scritto:

**Comment by kazuyoshifunaki** [comment]
Ok! I just ran 20 minutes in different scenarios and so far it looks great. There is a little bit of a wobble in the beginning until you found your desired speed, but in general it seems to work. I want to keep on testing a few days and will get back to you with feedback.

Thanks for the excellent stuff!

**Comment by cagnulein** [comment]
Amazing! Let me know if you have any other suggestions!

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno gio 30 gen 2025 alle 19:21 kazuyoshifunaki <
***@***.***> ha scritto:

**Comment by kazuyoshifunaki** [comment]
Just to give some feedback. This is working, really, really great! I love it

One observation:
- There seems to be a slight power or pace drift down. After a few adjustments up and down, often I return to zero incline, and for some reason, I am 0.1 or 0.2 slower. 

This is actually quite ok, but I thought I'd document it. I wouldn't want to change anything right now. I will keep on trying out different routes with this, so will feed back any findings.

But so far, great stuff! Thank you!
