### ISSUE TITLE
CycleOps Phantom 5

### ISSUE THREAD

**Issue by cagnulein** [cagnulein/qdomyos-zwift#3004]
https://github.com/codeinversion/sensors-swift-trainers/blob/master/Sources/SwiftySensorsTrainers/CycleOpsService.swift

**Comment by cagnulein** [comment]
![image](https://github.com/user-attachments/assets/4667a904-4c64-4dd7-8c94-682e4b973f26)

**Comment by cagnulein** [comment]
![image](https://github.com/user-attachments/assets/7b0e6015-844e-4b05-a012-332ae79abd40)

**Comment by uaflyr95** [comment]
[debug-Thu_Jan_9_17_03_53_2025.log](https://github.com/user-attachments/files/18368948/debug-Thu_Jan_9_17_03_53_2025.log)

**Comment by uaflyr95** [comment]
Here are some parallel screen shots as I completed this workout. I don’t know if the debug files are date-time stamped but you can see the corresponding rider experience. Adding resistance (when it works) is a one way street. A little gives a LOT — to the point of having to power down the bike and disable the resistance on the QZ app to get it back under control. With all my weight - STANDING ON THE PEDALS - I could not get the flywheel free once the resistance unit started to increase the load.

**Comment by uaflyr95** [comment]
![IMG_0237](https://github.com/user-attachments/assets/ad14af13-7f4e-456d-b0cd-5b88b9900de2)
![IMG_3485](https://github.com/user-attachments/assets/a18aca48-20cd-4e44-b712-118e2237f5d9)
![IMG_0238](https://github.com/user-attachments/assets/b73a3954-e7f9-4076-a256-a40442314cbf)
![IMG_3484](https://github.com/user-attachments/assets/780cde9c-3cca-4f83-8951-93efcb81423f)
![IMG_3486](https://github.com/user-attachments/assets/ed6900b8-083b-4452-aa8e-b06427e63af3)
![IMG_3489](https://github.com/user-attachments/assets/6cc13f92-1072-4ab0-b728-23a821d09879)
![IMG_3487](https://github.com/user-attachments/assets/2484f969-3826-415d-8cb1-93cabaf8f634)
![IMG_3488](https://github.com/user-attachments/assets/f9bef23d-fe8c-4952-8e54-5f50901bfd30)
![IMG_3483](https://github.com/user-attachments/assets/346e99c9-8b38-404e-ae71-93cb9ae37927)

**Comment by uaflyr95** [comment]
![IMG_0241](https://github.com/user-attachments/assets/bf3c3028-54f4-40d2-b960-871f2f32d18d)
![IMG_0240](https://github.com/user-attachments/assets/f5e7d77e-626e-4fc4-b6f9-ae7b1d066f36)
![IMG_0239](https://github.com/user-attachments/assets/5821cfac-b25e-4b2b-afa3-ab05e4f6e454)
![IMG_3486](https://github.com/user-attachments/assets/6786bd2c-fbb1-4026-897a-72323cbad14a)
![IMG_3485](https://github.com/user-attachments/assets/022f683d-b4f0-4675-a0be-067b392d0580)
![IMG_0238](https://github.com/user-attachments/assets/014ec072-48af-4a27-9a42-80f420d87b82)
![IMG_3484](https://github.com/user-attachments/assets/360421e6-9c39-4beb-9cc7-902cf77339e0)
![IMG_0237](https://github.com/user-attachments/assets/1b0e9389-3708-4439-a37e-112f8e5e82f0)
![IMG_3483](https://github.com/user-attachments/assets/f753d5cc-0473-4e4c-85ef-b92bd9ce5e67)

**Comment by uaflyr95** [comment]
The photos are chronologically out of order, but I feel like the timestamps. I think the picture will become clear.

**Comment by cagnulein** [comment]
@uaflyr95 one major thing that I saw on the log: you didn't connect the ride app (is it rouvy) directly to qz, so the game is not controlling QZ. Use the game on a device and qz on another, and put qz as a controllable device there so it should be better.
Let me know!

**Comment by uaflyr95** [comment]
I’m running the Rouvy app on my iPad as I always do — except for — instead of pairing Rouvy to my bike, I have it paired to my iPhone (which appeared as an option that I’ve never seen presented as such in the Rouvy device list).  My iPhone is running the QZ app. The telemetry presented within the Rouvy app differs slightly from the telemetry presented in the QZ tile screen. Changing the resistance on the QZ Tile screen DID change the resistance on the bike, but only upward… and in BIG BIG jumps - I could not get it to change the resistance, downward, (the big buttons on the QC tile screen for + / - did not seem to work in either direction). I’m not sure how I would connect QZ to Rouvy by any other method. Additionally, I’m not certain how I would configure QZ differently to be a controllable device. 

I AM optimistic that there are some communications  taking place between the bike, the QZ app and the Rouvy app. Whether or not I can establish the fidelity between the devices to accurately control the resistance unit remains in question. 

I first bought this bike in 2015, and CycleOps was responsible for the software that ran it. It was kind of clumsy. (in light of what we now know and expect). The original code made for a very jerky transitions on hills and workouts when when it called for a change in resistance. Eventually, they smoothed out the algorithm and made it better, but the. they handed off the code to Rouvy. Rouvy smoothed it out even more and the riding experience was really enjoyable…… right up until they quit supporting it.

 Rouvy has the code that controls this resistance unit, but apparently doesn’t want to share it with anybody. I’ve seen many willing software engineers on Reddit, who own a Phantom 5 and were more than willing to get involved so that Phantom 5 owners could regain normal function of their bikes. Apparently there are too many roadblocks to that end.  
 
The QZ app is as close as I’ve seen to a promising solution since Rouvy effectively kicked us off the planet by not supporting us on their current virtual platform.

**Comment by uaflyr95** [comment]
In case it isn’t obvious in the aforementioned text, the QZ app is paired to my bike. The bike was discoverable, and I selected it and configured it as you instructed earlier.

![IMG_3490](https://github.com/user-attachments/assets/4d328c40-659e-433a-86bc-421d9a6ac85c)

**Comment by cagnulein** [comment]
Ok I guess I understood why I don't see the inclination from rouvy : set the name of your phone to JUSTO

Exactly writtwn in this way and reboot the phone 

Don't worry we can get it, we just need to do small steps

**Comment by uaflyr95** [comment]
I didn’t have time today to do this, but I’m curious to understand how changing the name of my phone will lead us closer to a diagnosis of the problem. I admit my ignorance up front, but I’d like to see the big picture and can gain some understand of the basic mechanics behind all of this. Sorry to be such a novice. Thanks again for your time and persistence….AlanSent from my iPhoneOn Jan 10, 2025, at 13:46, Roberto Viola ***@***.***> wrote:﻿
Ok I guess I understood why I don't see the inclination from rouvy : set the name of your phone to JUSTO
Exactly writtwn in this way and reboot the phone
Don't worry we can get it, we just need to do small steps

**Comment by cagnulein** [comment]
Because rouvy is filtering the device based on the name. Showing a phone name instead of JUSTO to them means "this trainer is stupid, don't send inclination to it"

**Comment by uaflyr95** [comment]
As many times as I tried to do this, I cannot get this to work. Just to verify my set up: • My iPad is running the latest Rouvy app.• I renamed my iPhone (as you directed) with the name JUSTO • I shut down and restarted my phone. • I opened the QZ app on my phone • I scrolled through the list of Bluetooth devices detected by Rouvy on my iPad looking for JUSTOThis is my experience:• JUSTO does not appear on the list of detected Bluetooth devices. • My iPhone IS on the list, but is misspelled• If I disable Bluetooth on my iPhone, it disappears from the list of detected Bluetooth devices on the Rouvy app. • If I correct the name of my iPhone to the correct spelling, reboot my phone and turn Bluetooth back on, it reappears on the Rouvy list, but it retains the misspelled name• I have tried logging off Rouvy, deleting the app, reinstalling the app, and re-logging in with exactly the same results.• I also tried deleting the QZ app and reinstalling (the TestFlight version) with exactly the same results.There is definitely a communication problem between these devices / apps. That said,I’m not sure what to try next….AlanSent from my iPhoneOn Jan 11, 2025, at 00:30, Roberto Viola ***@***.***> wrote:﻿
Because rouvy is filtering the device based on the name. Showing a phone name instead of JUSTO to them means "this trainer is stupid, don't send inclination to it"

**Comment by cagnulein** [comment]
Hah wait @uaflyr95 I thought you were on android!

So you don't need to rename the device on ios.

So do you have fresh logs from these tests just to check if the same issue?

**Comment by uaflyr95** [comment]
I’m away until Thursday - I’ll forward logs when I get home….Thanks for your speedy responses!AlanSent from my iPhoneOn Jan 13, 2025, at 22:19, Roberto Viola ***@***.***> wrote:﻿
Hah wait @uaflyr95 I thought you were on android!
So you don't need to rename the device on ios.
So do you have fresh logs from these tests just to check if the same issue?

**Comment by cagnulein** [comment]
In the mean time I try to simulate the same setup

**Comment by cagnulein** [comment]
Just tried and on my end it works perfectly 

![image](https://github.com/user-attachments/assets/3b039987-1845-4983-aad1-3a89af459528)

You have to pair in this way

Also on qz, the incline tile must match automatically the one on rouvy 

Let me know

**Comment by cagnulein** [comment]
Anyway @uaflyr95 in order to start with simple things, try to use qz standalone and change the resistance from qz directly in the tile. Do you feel any difference in the resistance?

**Comment by uaflyr95** [comment]
Yes - there is a BIG change in resistance — a big INCREASE (to the point of locking up the resistance unit where I have to power it down to regain control). This was my experience with resistance changes in EITHER direction. It was also true when I used the big buttons for the Gear +\-  I’ll send you the debug log shortly… Sent from my iPhoneOn Jan 15, 2025, at 23:47, Roberto Viola ***@***.***> wrote:﻿
Anyway @uaflyr95 in order to start with simple things, try to use qz standalone and change the resistance from qz directly in the tile. Do you feel any difference in the resistance?

**Comment by uaflyr95** [comment]
[debug-Thu_Jan_16_17_10_46_2025.log](https://github.com/user-attachments/files/18446596/debug-Thu_Jan_16_17_10_46_2025.log)

**Comment by uaflyr95** [comment]
This is the debug file I promised from today’s trial with ONLY the QZ app open and controlling the bike. 

As I mentioned in my email, no matter what kind of change I made to the resistance, it seemed to instigate a runaway condition leading to MAX resistance. The only way I could regain control (to even move the pedals) was to shutdown and restart the bike by unpowering it and then turning it back on.  Hopefully the debug files will shed some light on the WHY of it…..

**Comment by cagnulein** [comment]
Perfect, maybe I just set a variable wrong!
I will be back to you shortly
Thanks

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno ven 17 gen 2025 alle 01:10 uaflyr95 ***@***.***> ha
scritto:

**Comment by cagnulein** [comment]
got the issue, thanks. do another test.
1. open qz
2. press the plus on the INCLINATION tile (only this one)
3. you should feel the resistance increases (don't mind about the resistance tile on qz), but only a light increment
4. then press the minus on the INCLINATION tile and it should be as the start

Let me know!

**Comment by uaflyr95** [comment]
There is change, but the jump is BIG. It’s not a runaway jump like it was before but big enough to make me get up off the saddle. Additionally, the (-) doesn’t give much relief in the way of decreasing resistance. I’ll send a log of that helps. Alan Sent from my iPhoneOn Jan 17, 2025, at 02:09, Roberto Viola ***@***.***> wrote:﻿
got the issue, thanks. do another test.

open qz
press the plus on the INCLINATION tile (only this one)
you should feel the resistance increases (don't mind about the resistance tile on qz), but only a light increment
then press the minus on the INCLINATION tile and it should be as the start

Let me know!

**Comment by uaflyr95** [comment]
[debug-Fri_Jan_17_17_04_54_2025.log](https://github.com/user-attachments/files/18461921/debug-Fri_Jan_17_17_04_54_2025.log)
[debug-Fri_Jan_17_17_07_29_2025.log](https://github.com/user-attachments/files/18461919/debug-Fri_Jan_17_17_07_29_2025.log)
[debug-Fri_Jan_17_17_11_16_2025.log](https://github.com/user-attachments/files/18461920/debug-Fri_Jan_17_17_11_16_2025.log)

**Comment by uaflyr95** [comment]
These are the three tests using the incline +\- tile. 
I appreciate your persistence in getting this unit back under control !

**Comment by cagnulein** [comment]
Ok perfect i will check them' don't worry we are very near! I believe it's
just a *10 factor

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno sab 18 gen 2025 alle 01:04 uaflyr95 ***@***.***> ha
scritto:

**Comment by cagnulein** [comment]
Just sent a newer version. Do the same the test and let me know if it's
better

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno sab 18 gen 2025 alle 08:02 cagnulein ***@***.***> ha
scritto:

**Comment by uaflyr95** [comment]
It IS a little better, but the jump is still pretty big. I tested it several times. I pedaled at about 70-75 RPM for a minute at about 120-140 Watts. I then pressed the incline + (just once) and the resistance went to  about 240 watts. The incline - button did not seem to decrease the resistance at all (even with multiple presses). I closed the app and re-did the same procedure with the same result. One additional observation is that the “0” value does not change when the +/- key is selected on the inclination button. I will include the debug file again; do those files help you at all?AlanSent from my iPhoneOn Jan 18, 2025, at 03:00, Roberto Viola ***@***.***> wrote:﻿
Just sent a newer version. Do the same the test and let me know if it's

better



Roberto Viola

Software engineer and open source enthusiast

http://robertoviola.cloud







Il giorno sab 18 gen 2025 alle 08:02 cagnulein ***@***.***> ha

scritto:

**Comment by uaflyr95** [comment]
[debug-Sat_Jan_18_08_23_36_2025.log](https://github.com/user-attachments/files/18466705/debug-Sat_Jan_18_08_23_36_2025.log)
[debug-Sat_Jan_18_10_48_15_2025.log](https://github.com/user-attachments/files/18466704/debug-Sat_Jan_18_10_48_15_2025.log)

**Comment by uaflyr95** [comment]
Debug files using 2.18 (1002)

**Comment by cagnulein** [comment]
Thanks,
Yes the debug log are essential to me!
I will let you know in these days

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno dom 19 gen 2025 alle 01:04 uaflyr95 ***@***.***> ha
scritto:

**Comment by cagnulein** [comment]
in the meantime, could we try another thing: enable the target watt tile in
the tiles settings, and try to change the target watt value from the tile
in qz. does it follow correctly?

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno dom 19 gen 2025 alle ore 07:14 cagnulein ***@***.***> ha
scritto:

**Comment by uaflyr95** [comment]
Sorry it took so long to get back to you on this. Good news though….. for the first time in a VERY long time - through your diligent effort,  I’ve experienced controllable resistance on my Phantom 5. I did as you suggested and discovered that it was functional in the way you described. So to enable further discovery, I tried this set up:- I opened the QZ app on my iPhone- I powered up the bike- I opened Rouvy on my iPad- I paired my iPad via Bluetooth to my iPhone- I selected a simple workout on Rouvy that required resistance adjustments across the course of a 20 minute workout.- I adjusted the resistance in 10 W increments from the QZ app with the same fidelity that I’ve come to expect from this bike since I’ve owned it. - The resistance levels were stable and only changed when I executed a manual change.- I’ll forward a debug log for your viewingAlanSent from my iPhoneOn Jan 19, 2025, at 02:19, Roberto Viola ***@***.***> wrote:﻿
in the meantime, could we try another thing: enable the target watt tile in

the tiles settings, and try to change the target watt value from the tile

in qz. does it follow correctly?



Roberto Viola

Software engineer and open source enthusiast

http://robertoviola.cloud







Il giorno dom 19 gen 2025 alle ore 07:14 cagnulein ***@***.***> ha

scritto:

**Comment by uaflyr95** [comment]
[debug-Mon_Jan_20_17_44_22_2025.log](https://github.com/user-attachments/files/18483373/debug-Mon_Jan_20_17_44_22_2025.log)

**Comment by uaflyr95** [comment]
Though this might require a small miracle, do you see any possibility of the bike responding automatically to ride data coming from Rouvy?
I have a hard time envisioning how that could occur. 

I am thrilled to have achieve THIS level of response, and I’m just looking at what other possibilities could be presented through these channels.

I can’t tell you how much I appreciate your effort on this.  It has  resurrected my ability to use this bike in a functional capacity.

**Comment by cagnulein** [comment]
Yes we just need to find the issue on the inclination thing. I will still
play with the offset and I will send you another version
Anyway we are near :)

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mar 21 gen 2025 alle 01:29 uaflyr95 ***@***.***> ha
scritto:

**Comment by cagnulein** [comment]
sent a new version for the inclination thing. let me know!
Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mar 21 gen 2025 alle ore 05:17 cagnulein ***@***.***> ha
scritto:

**Comment by uaflyr95** [comment]
I was out of town for a few days. I tried this tonight. I first tested the new version using ONLY the iPhone running the QZ app. The inclination (+/-) key only INCREASES the resistance. I could not get it to back off - even with repeated presses of the (-) key. I then did a ROUVY WORKOUT (as I did the other day before your latest update). The setup:- iPad running Rouvy- iPad (Rouvy) paired with iPhone (running QZ app) as the detected device- ROUVY WORKOUT functioned normally with manual control of the desired wattage using the (+/-) function (as was the case with the previous version). Finally, I tried riding a ROUVY ROUTE to test the inclination function. The setup:- iPad running Rouvy- iPad (Rouvy) paired with iPhone (running QZ app) as the detected device- ROUVY ROUTE data was reflected (fairly accurately) on the QZ app tile display (speed, cadence, incline/decline). - Resistance increased automatically to the increasing % on the route (although by too much proportionately). It did NOT decrease, however, with  a downhill (negative slope) despite my varied attempts to control resistance using the watt +/- and incline +/- functions. It seemed “stuck” at the higher resistance value. I am encouraged though by the fact that an increasing grade changed the resistance - AUTOMATICALLY - that is what I was ultimately hoping to see resurrected. Let me know if there is another way you’d like me to test this version. I’ll forward the debug logs of the tests I described above. Thanks again for all your work on this. AlanSent from my iPhoneOn Jan 21, 2025, at 04:12, Roberto Viola ***@***.***> wrote:﻿
sent a new version for the inclination thing. let me know!

Roberto Viola

Software engineer and open source enthusiast

http://robertoviola.cloud







Il giorno mar 21 gen 2025 alle ore 05:17 cagnulein ***@***.***> ha

scritto:

**Comment by cagnulein** [comment]
Please share a debug log 
Also the resistance is now correct or it's still too heavy?

**Comment by uaflyr95** [comment]
[debug-Thu_Jan_23_17_53_20_2025.log](https://github.com/user-attachments/files/18531615/debug-Thu_Jan_23_17_53_20_2025.log)
[debug-Thu_Jan_23_17_49_45_2025.log](https://github.com/user-attachments/files/18531614/debug-Thu_Jan_23_17_49_45_2025.log)
[debug-Tue_Jan_21_09_57_06_2025.log](https://github.com/user-attachments/files/18531613/debug-Tue_Jan_21_09_57_06_2025.log)

**Comment by uaflyr95** [comment]
I hope these help to illuminate my observations

**Comment by uaflyr95** [comment]
I think the resistance changes are still pretty heavy

**Comment by uaflyr95** [comment]
Why does the QZ app respond to Rouvy Route inclination data automatically, but still requires manual intervention on the Rouvy Workout to effect changes in the resistance? 

Also, should the Gear +/- key act on the resistance when grade changes are encountered on a Rouvy Route? (I realize that I might be getting ahead of our progress a bit here).

**Comment by uaflyr95** [comment]
I think the resistance changes are still pretty heavy  Why does the QZ app respond to Rouvy Route inclination data automatically, but still requires manual intervention on the Rouvy Workout to effect changes in the resistance?Also, should the Gear +/- key act on the resistance when grade changes are encountered on a Rouvy Route? (I realize that I might be getting ahead of our progress a bit here).Sent from my iPhoneOn Jan 24, 2025, at 00:44, Roberto Viola ***@***.***> wrote:﻿
Please share a debug log
Also the resistance is now correct or it's still too heavy?

**Comment by cagnulein** [comment]
@uaflyr95 in these log i don't see a rouvy workout, i only see qz standalone sessions. are you sure about the timestamps?
about the fact that you can't lower down the inclination is because i guess the bike doesn't handle negative inclination (i was trying to set -0.5)
anyway this is just to check without rouvy, with rouvy you shouldn't have this issue, but i need a qz with rouvy log to understand it.
let me know!

**Comment by uaflyr95** [comment]
How do I configure the setup to provide a Rouvy log? In the Rouvy sensors list, I chose my iPhone (not the bike) as the trainer. I thought because the QZ app was paired to the bike that I needed to pair Rouvy to my iPhone. I clearly have this configuration wrong…AlanSent from my iPhoneOn Jan 24, 2025, at 01:35, Roberto Viola ***@***.***> wrote:﻿
@uaflyr95 in these log i don't see a rouvy workout, i only see qz standalone sessions. are you sure about the timestamps?
about the fact that you can't lower down the inclination is because i guess the bike doesn't handle negative inclination (i was trying to set -0.5)
anyway this is just to check without rouvy, with rouvy you shouldn't have this issue, but i need a qz with rouvy log to understand it.
let me know!

**Comment by cagnulein** [comment]
yes iphone it's on on rouvy for all the tiles, so it must be a smart trainer in rouvy. show me a screenshot

**Comment by uaflyr95** [comment]
These pics show my tile setup on QZ, the sensor selections in the Rouvy app, and the data strip from last night’s ride (corresponding to the latest debug log). Sent from my iPhoneOn Jan 24, 2025, at 08:32, Roberto Viola ***@***.***> wrote:﻿
yes iphone it's on on rouvy for all the tiles, so it must be a smart trainer in rouvy. show me a screenshot

**Comment by cagnulein** [comment]
I can't see the photo because you have to upload them on github directly. Please upload them again

**Comment by uaflyr95** [comment]
![Image](https://github.com/user-attachments/assets/5a175828-427b-40a0-ba57-e5724d6ff815)
![Image](https://github.com/user-attachments/assets/97f9d011-fc9b-40fb-9fa0-83ed46bf85b5)
![Image](https://github.com/user-attachments/assets/35af151e-b9c4-4dfd-815f-4f14634fb44f)

**Comment by uaflyr95** [comment]
This is is how I had it configured last evening.

**Comment by cagnulein** [comment]
Rouvy setup seems fine. Are you sure the log that you sent me yesterday were about the rouvy sessions?

**Comment by uaflyr95** [comment]
![Image](https://github.com/user-attachments/assets/451803d5-e6be-4c85-b288-5365e86d46f0)
![Image](https://github.com/user-attachments/assets/54d01b49-41bf-4784-8914-530826a13b5e)

**Comment by uaflyr95** [comment]
This would be my normal configuration without QZ

**Comment by uaflyr95** [comment]
Let me resend…Sent from my iPhoneOn Jan 24, 2025, at 09:22, Roberto Viola ***@***.***> wrote:﻿
Rouvy setup seems fine. Are you sure the log that you sent me yesterday were about the rouvy sessions?

**Comment by cagnulein** [comment]
Ok check my previous question

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno ven 24 gen 2025 alle 16:23 uaflyr95 ***@***.***> ha
scritto:

**Comment by uaflyr95** [comment]
[debug-Thu_Jan_23_17_53_20_2025.log](https://github.com/user-attachments/files/18538254/debug-Thu_Jan_23_17_53_20_2025.log)

[debug-Thu_Jan_23_17_49_45_2025.log](https://github.com/user-attachments/files/18538253/debug-Thu_Jan_23_17_49_45_2025.log)

**Comment by uaflyr95** [comment]
These are yesterday’s debug files. I believe they are the same ones that I already sent you, but it’s worth a second try.

**Comment by uaflyr95** [comment]
One of the files I sent you last night WAS an old one as I look back…

**Comment by cagnulein** [comment]
Thanks, I'll check it out!


Il giorno ven 24 gen 2025 alle 16:38 uaflyr95 ***@***.***> ha
scritto:

**Comment by cagnulein** [comment]
No unfortunately they aren't about a rouvy session, could you please
collect another one? Even just a 2 minutes ride
Thanks

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno ven 24 gen 2025 alle 17:15 cagnulein ***@***.***> ha
scritto:

**Comment by uaflyr95** [comment]
[debug-Sat_Jan_25_19_09_05_2025.log](https://github.com/user-attachments/files/18548977/debug-Sat_Jan_25_19_09_05_2025.log)
[debug-Sat_Jan_25_19_09_51_2025.log](https://github.com/user-attachments/files/18548974/debug-Sat_Jan_25_19_09_51_2025.log)
[debug-Sat_Jan_25_19_20_35_2025.log](https://github.com/user-attachments/files/18548976/debug-Sat_Jan_25_19_20_35_2025.log)
[debug-Sat_Jan_25_19_19_00_2025.log](https://github.com/user-attachments/files/18548975/debug-Sat_Jan_25_19_19_00_2025.log)

**Comment by uaflyr95** [comment]
These were all paired up with a ROUVY ROUTE. 

![Image](https://github.com/user-attachments/assets/00f5efd3-170c-4371-b867-7f1b0c67e664)
![Image](https://github.com/user-attachments/assets/328a15a7-cf88-4e1a-87f3-09edc7cf861d)
![Image](https://github.com/user-attachments/assets/53b4d1d1-365d-4b6c-a434-74fdf1d5ac3e)
![Image](https://github.com/user-attachments/assets/675e89c7-9cba-437e-b986-b98996d4e79e)

**Comment by cagnulein** [comment]
that's the issue! controllable must also be the phone!

**Comment by uaflyr95** [comment]
I sent you some debug files and a few screen shots of the Rouvy Route I rode to retest the version as you requested. Question: How does QZ get data FROM Rouvy? Using the setup we’ve been using I understand where QZ gets the bike data because it’s paired directly to the bike sensors (as we saw by pairing them WITHOUT using Rouvy). When we open Rouvy and pair the iPhone (rather than the bike itself) is QZ then a recipient of the course data (I.e. incline / decline information).My experience  thus far is that on the Rouvy Route as well as the Rouvy Workout, the only control is a manual adjustment for desired watts. So I can set any resistance I desire MANUALLY and it STAYS that way —regardless of climbs / descents on a Rouvy Route or changing intervals during Rouvy Workouts. I did a Rouvy Workout using my Cannondale Bike on my Wahoo Kickr just before I did this test run tonight. Rouvy automatically increases / decreases the resistance to the desired intensity at each interval. On a Rouvy Route it behaves the same way for increasing /decreasing inclines. Another note tonight: The last time I tested this (using the same setup) I watched QZ mirror the data shown on my Rouvy Route . Although I was making resistance changes manually through QZ, QZ tiles were mirroring Watts, Incline, Cadence etc. closely with the Rouvy Route display. Tonight it did not do that. The only telemetry displayed wats Watts. Just thoughts, questions cans observations. Thanks again for your pursuit!AlanSent from my iPhoneOn Jan 25, 2025, at 12:07, Roberto Viola ***@***.***> wrote:﻿
No unfortunately they aren't about a rouvy session, could you please

collect another one? Even just a 2 minutes ride

Thanks



Roberto Viola

Software engineer and open source enthusiast

http://robertoviola.cloud







Il giorno ven 24 gen 2025 alle 17:15 cagnulein ***@***.***> ha

scritto:

**Comment by uaflyr95** [comment]
[debug-Mon_Jan_27_16_42_06_2025.log](https://github.com/user-attachments/files/18566112/debug-Mon_Jan_27_16_42_06_2025.log)
[debug-Mon_Jan_27_17_08_01_2025.log](https://github.com/user-attachments/files/18566114/debug-Mon_Jan_27_17_08_01_2025.log)
[debug-Mon_Jan_27_16_57_28_2025.log](https://github.com/user-attachments/files/18566113/debug-Mon_Jan_27_16_57_28_2025.log)

**Comment by uaflyr95** [comment]
Up until now Rouvy would not allow QZ to be controllable.....and I tried MANY times. I consistently got this screen message.

![Image](https://github.com/user-attachments/assets/40a670ce-4e1e-46a0-ab7d-b5794e0370f6)

Ultimately, I DID  figure out why Rouvy wouldn't allow QZ to be controllable;  apparently I overlooked the cadence sensor that was still paired to the bike.  I disabled everything --  and Rouvy FINALLY allowed QZ to take control of the Cadence AND the Controllable elements. 

![Image](https://github.com/user-attachments/assets/71e959f9-2660-4d03-9e60-d95115debebb)

 
I sent debug files from tonight. I rode part of a Rouvy Route and part of a Rouvy Workout.

Rouvy Route: It seems fixed in an ERG mode. The resistance is fixed and the changing inclination does not change the reisistance. Speed changes appropriately to the incline or decline, but resistance remains constant with no apparent way to increase or decrease it. I tried every tile that  had a +/- function to no avail.

Rouvy Workout: I created this workout as a 20 minute - steady 120W - 75 RPM target ride. If you can see the attached screen shot, the average power was 181W at an average cadence of 70 RPM. The resistance is too heavy and I could not control it lower using the QZ tiles (like I could when the BIKE was paired as the "controllable" device).

<img width="1282" alt="Image" src="https://github.com/user-attachments/assets/df845c26-32ad-4407-910f-d11ef477fcb5" />
![Image](https://github.com/user-attachments/assets/f50fe6a9-440a-47a4-a7a8-44f507d2e75a)

Now that I finally caught up to your guidance with the pairing issue, is there anything I can try on my end to facilitate some control of the baseline resistance or the information coming from the Rouvy app? 

You've been extremely patient and more than helpful. Thank you for your continued attention.

Alan

**Comment by cagnulein** [comment]
> Ultimately, I DID figure out why Rouvy wouldn't allow QZ to be controllable; apparently I overlooked the cadence sensor that was still paired to the bike. I disabled everything -- and Rouvy FINALLY allowed QZ to take control of the Cadence AND the Controllable elements.
> 

perfect! now it's perfect also in the debug log from rouvy!


> 
> Rouvy Route: It seems fixed in an ERG mode. The resistance is fixed and the changing inclination does not change the reisistance. Speed changes appropriately to the incline or decline, but resistance remains constant with no apparent way to increase or decrease it. I tried every tile that had a +/- function to no avail.

i see the session and i see qz changing the inclination accordingly to rouvy. let me put back the calculation that it was before, because i guess, now that we have this in place, the calculation was right

> 
> Rouvy Workout: I created this workout as a 20 minute - steady 120W - 75 RPM target ride. If you can see the attached screen shot, the average power was 181W at an average cadence of 70 RPM. The resistance is too heavy and I could not control it lower using the QZ tiles (like I could when the BIKE was paired as the "controllable" device).

**you missed one thing here: you have to enable the zwift erg mode in qz as well for this under the bike options. disabled for routes and enabled for workout.**

i'm sending you a new one. let me know!

**Comment by uaflyr95** [comment]
The app continuously crashes today. I tried many different combinations for powering up and pairing; the tiles appear momentarily and then the app crashes and closes. Sent from my iPhoneOn Jan 28, 2025, at 01:37, Roberto Viola ***@***.***> wrote:﻿

Ultimately, I DID figure out why Rouvy wouldn't allow QZ to be controllable; apparently I overlooked the cadence sensor that was still paired to the bike. I disabled everything -- and Rouvy FINALLY allowed QZ to take control of the Cadence AND the Controllable elements.

perfect! now it's perfect also in the debug log from rouvy!

Rouvy Route: It seems fixed in an ERG mode. The resistance is fixed and the changing inclination does not change the reisistance. Speed changes appropriately to the incline or decline, but resistance remains constant with no apparent way to increase or decrease it. I tried every tile that had a +/- function to no avail.

i see the session and i see qz changing the inclination accordingly to rouvy. let me put back the calculation that it was before, because i guess, now that we have this in place, the calculation was right

Rouvy Workout: I created this workout as a 20 minute - steady 120W - 75 RPM target ride. If you can see the attached screen shot, the average power was 181W at an average cadence of 70 RPM. The resistance is too heavy and I could not control it lower using the QZ tiles (like I could when the BIKE was paired as the "controllable" device).

you missed one thing here: you have to enable the zwift erg mode in qz as well for this under the bike options. disabled for routes and enabled for workout.
i'm sending you a new one. let me know!

**Comment by cagnulein** [comment]
I didn't change anything.from the testflight app you are able to go the
previous one. Is it the same?

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mar 28 gen 2025 alle 21:04 uaflyr95 ***@***.***> ha
scritto:

**Comment by uaflyr95** [comment]
I just deleted the app from my phone and reinstalled it through the TestFlight app. It continues to crash as soon as it senses the bike. If I turn the bike off the app comes up, and stays open but obviously doesn't show the tiles. The only thing I can configured differently since we last discussed this is the erg mode for a workout. I have since disabled that feature; it responds by crashing as soon as the tile screen displays.Sent from my iPhoneOn Jan 28, 2025, at 14:06, Roberto Viola ***@***.***> wrote:﻿
I didn't change anything.from the testflight app you are able to go the

previous one. Is it the same?



Roberto Viola

Software engineer and open source enthusiast

http://robertoviola.cloud







Il giorno mar 28 gen 2025 alle 21:04 uaflyr95 ***@***.***> ha

scritto:

**Comment by uaflyr95** [comment]
I don’t see the option to rerun to the previous version. I’m using 2.18.17 currently. Sent from my iPhoneOn Jan 28, 2025, at 14:06, Roberto Viola ***@***.***> wrote:﻿
I didn't change anything.from the testflight app you are able to go the

previous one. Is it the same?



Roberto Viola

Software engineer and open source enthusiast

http://robertoviola.cloud







Il giorno mar 28 gen 2025 alle 21:04 uaflyr95 ***@***.***> ha

scritto:

**Comment by cagnulein** [comment]
From the test flight app use the button to load an older version, check if
it works with the previous one

Let me know i don't think I changed anything else

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mar 28 gen 2025 alle 21:12 uaflyr95 ***@***.***> ha
scritto:

**Comment by cagnulein** [comment]
You can also send me a debug log of the crash.
I'm going to bed now

**Comment by uaflyr95** [comment]
2.18 (2004) worked PERFECTLY on Rouvy Workout (with ERG enabled in Bike Settings). The resistance on Rouvy Routes is too heavy and doesn’t vary at all with increasing or decreasing inclination in this version (with ERG disabled in Bike Settings). I am THRILLED to see how perfectly it adheres to the workout profile, however!2.18 (1007) continues to crash continuously after opening and pairing with the bike. After successfully riding a Rouvy Workout in version 2.18 (2004), I reinstalled the newer version and experienced the same result as earlier. I’ll send any debug log that QZ saved today. AlanSent from my iPhoneOn Jan 28, 2025, at 14:31, Roberto Viola ***@***.***> wrote:﻿
You can also send me a debug log of the crash.
I'm going to bed now

**Comment by cagnulein** [comment]
Ok share me a debug log for the new one and I will check the new version, I
guess it's something else
Thanks

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mar 28 gen 2025 alle 22:16 uaflyr95 ***@***.***> ha
scritto:

**Comment by cagnulein** [comment]
got the crash, i'm sending you a new one
Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mer 29 gen 2025 alle ore 06:26 cagnulein ***@***.***> ha
scritto:

**Comment by cagnulein** [comment]
Sent!

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mer 29 gen 2025 alle 06:41 cagnulein ***@***.***> ha
scritto:

**Comment by uaflyr95** [comment]
I’m out of town town currently; I’ll test it on Thursday. Thanks for your super speedy update — did you even sleep?Sent from my iPhoneOn Jan 28, 2025, at 23:54, Roberto Viola ***@***.***> wrote:﻿
Sent!



Roberto Viola

Software engineer and open source enthusiast

http://robertoviola.cloud







Il giorno mer 29 gen 2025 alle 06:41 cagnulein ***@***.***> ha

scritto:

**Comment by cagnulein** [comment]
I'm trying to sleep but when I have something on mind I can't :)

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mer 29 gen 2025 alle 06:59 uaflyr95 ***@***.***> ha
scritto:

**Comment by uaflyr95** [comment]
You sir, are in good company! Most high achievers I know suffer from the same problem….Im on the other side of the planet — it’s about time I give it a try!Chat soon…AlanSent from my iPhoneOn Jan 29, 2025, at 00:09, Roberto Viola ***@***.***> wrote:﻿
I'm trying to sleep but when I have something on mind I can't :)



Roberto Viola

Software engineer and open source enthusiast

http://robertoviola.cloud







Il giorno mer 29 gen 2025 alle 06:59 uaflyr95 ***@***.***> ha

scritto:

**Comment by uaflyr95** [comment]
[debug-Fri_Jan_31_17_57_10_2025.log](https://github.com/user-attachments/files/18626717/debug-Fri_Jan_31_17_57_10_2025.log)
[debug-Fri_Jan_31_18_27_51_2025.log](https://github.com/user-attachments/files/18626719/debug-Fri_Jan_31_18_27_51_2025.log)
[debug-Fri_Jan_31_18_01_34_2025.log](https://github.com/user-attachments/files/18626718/debug-Fri_Jan_31_18_01_34_2025.log)

**Comment by uaflyr95** [comment]
I included 3 logs:

1. Route Ride - REALLY heavy resistance for the relative grade / inclination with no apparent way to “shift gears”.  (18:01 / 3.6 MB)

2. Workout Ride - PERFECT (18:23. / 17 MB)

3. Route Ride - Again —- REALLY heavy resistance for the relative grade / inclination with no apparent way to “shift gears”. (18:32 / 4 MB)

I’ve tried different routes with the same experience.

**Comment by cagnulein** [comment]
So the previous one with free ride was too light and this one is too heavy?
Interesting

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno sab 1 feb 2025 alle 02:03 uaflyr95 ***@***.***> ha
scritto:

**Comment by cagnulein** [comment]
Gears buttons should already works but probably there is a still root issue due to the fact you are still feel it too heavy.

I will review the code again in the next days, thanks

**Comment by cagnulein** [comment]
@uaflyr95 i was checking the log and the bike is answering me correctly for the route mode. I was wondering: there is a command code that I didn't use yet, it's called "Headless mode". Do you know anything about it?

**Comment by cagnulein** [comment]
i have a plan: since it seems the incline control doesn't work, i was thinking to use ERG mode also for routes. For example setting a base target wattage for 0%, idk, 150W and then when the slope increments, also increments the wattage and so on. also gears will work with the same concept. what do you think?

**Comment by cagnulein** [comment]
sent!
let me know!
you can also calibrate the wattage request using the zwift resistance
offset and zwift resistance gain

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno lun 3 feb 2025 alle ore 20:22 cagnulein ***@***.***> ha
scritto:

**Comment by uaflyr95** [comment]
[debug-Thu_Feb_6_18_15_34_2025.log](https://github.com/user-attachments/files/18699736/debug-Thu_Feb_6_18_15_34_2025.log)
[debug-Thu_Feb_6_18_29_17_2025.log](https://github.com/user-attachments/files/18699737/debug-Thu_Feb_6_18_29_17_2025.log)

**Comment by uaflyr95** [comment]
IT WORKS !!!!!!!

I rode a Rouvy Route tonight using your recommendations and had a déjà vu experience; a recollection of days past when the bike was functioning properly. 

I'm not sure that my zwift resistance offset (set at 20) and zwift resistance gain (set at 1) are set properly, but after I played around with them a bit I was off and running. 

The resistance was completely controllable with the big gear buttons; it vacillated a bit at times (like it was hunting for the correct resistance), but it did not require any gear changes and did not really degrade the riding experience.  

If you see anything in the debug files or have any suggestions that you think would further improve the fidelity of the experience, please let me know. I REALLY APPRECIATE YOUR TENACITY IN THIS PURSUIT!

Thanks again

Alan

**Comment by uaflyr95** [comment]
Incidentally, I rode this with the ERG mode **OFF**

**Comment by cagnulein** [comment]
That's amazing!
Yes erg mode off is right for rides. Erg mode on is only for workouts
Feel free to close the ticket if you are happy with the solution!

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno ven 7 feb 2025 alle 03:06 uaflyr95 ***@***.***> ha
scritto:

**Comment by uaflyr95** [comment]
I apologize for not responding to you in a timely manner.  I was taking the opportunity to ride Routes and Workouts several more times to ensure I could repeat my success. Your app works VERY well.
I'd like to thank you again for all the effort you’ve invested in resurrecting my Phantom 5.
I just read that ROUVY is backtracking; they’re adding virtual shifting back into their interface, but I highly doubt whether it will include my “old” bike. 
I'd like to close our ticket at this point 
CycleOps Phantom 5 #3004
How do I do that?

Alan

**Comment by cagnulein** [comment]
That's great! I'm closing it for you! Remember to share the good news on internet!

About the virtual shifting on their HUD I will check if it's something that I can do

**Comment by cagnulein** [comment]
I will update the production version at the end of the winter to don't break anything in the hottest period of indoor workouts :)
