### ISSUE TITLE
[REQ] Add Waterrower USB connection Support

### ISSUE THREAD

**Issue by CodingDutchman** [cagnulein/qdomyos-zwift#3059]
**Is your feature request related to a problem? Please describe.**
I have a Waterrower with an S4 console/computer with a USB port on the back. The Waterrower app can connect via USB cable to the machine and display the strokes and such. It would be nice to be able to connect to this with QZ to consolidate my metrics and possibly support Zwift or other apps.

**Describe the solution you'd like**
Integrate the java library https://github.com/tbressler/waterrower-core to be able to read Waterrower metric via USB

**Describe alternatives you've considered**
N/A

**Additional context**

**Comment by cagnulein** [comment]
Thanks I will check it ASAP

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno ven 17 gen 2025 alle 18:10 Matthew Van Zante <
***@***.***> ha scritto:

**Comment by cagnulein** [comment]
started a PR for this, i will let you know when I will have something ready to test, it could take a while

**Comment by CodingDutchman** [comment]
No worries. Let me know if I can help in any way. Like if I need to run some app to log the USB output from the waterrower, or something like that.

**Comment by cagnulein** [comment]
When the merge is ready I will tell you how to collect a bug report :)

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno lun 20 gen 2025 alle 16:18 Matthew Van Zante <
***@***.***> ha scritto:

**Comment by cagnulein** [comment]
hi @CodingDutchman finally i'm here! i created a verison for you https://github.com/cagnulein/qdomyos-zwift/actions/runs/16672354067/artifacts/3666375580
you need to enable the water rower setting in the rower options in QZ and restart QZ
Share a debug log then to understand how far are we from a working version :)

**Comment by CodingDutchman** [comment]
Oh shoot, I kept forgetting about this. And now it looks like the download
link has expired. Can you send me a new link? Sorry!

**Comment by cagnulein** [comment]
it's still available, you simply need to login to github first

**Comment by CodingDutchman** [comment]
Okay, I captured this log. Haven't had a chance to examine it yet. 

[debug-Sun_Aug_17_19_43_09_2025.log](https://github.com/user-attachments/files/21825585/debug-Sun_Aug_17_19_43_09_2025.log)

**Comment by CodingDutchman** [comment]
From a cursory glance I didn't spot any useful data coming from the rower. Do I need to run the Water Rower app alongside QZ to capture the USB events?

**Comment by cagnulein** [comment]
It's promising the connection went fine. I will check deeply the log later
today

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno lun 18 ago 2025 alle 03:01 Matthew Van Zante <
***@***.***> ha scritto:

**Comment by cagnulein** [comment]
thanks, new build https://github.com/cagnulein/qdomyos-zwift/actions/runs/17042174300

i added more logs

**Comment by CodingDutchman** [comment]
Looks like the Android build failed?

**Comment by cagnulein** [comment]
Sorry about that! i'm actually running outside, I will check when I will
come back later


Il giorno lun 18 ago 2025 alle 16:14 Matthew Van Zante <
***@***.***> ha scritto:

**Comment by cagnulein** [comment]
no it's fine
https://github.com/cagnulein/qdomyos-zwift/actions/runs/17042174300/artifacts/3789233695

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno lun 18 ago 2025 alle ore 16:21 cagnulein ***@***.***> ha
scritto:

**Comment by CodingDutchman** [comment]
My apologies, I wasn't sure where to look. I'll give this a try either tonight or tomorrow.

**Comment by cagnulein** [comment]
No problem, take your time!

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno lun 18 ago 2025 alle ore 19:52 Matthew Van Zante <
***@***.***> ha scritto:

**Comment by CodingDutchman** [comment]
[debug-Tue_Aug_19_07_17_16_2025.log](https://github.com/user-attachments/files/21855419/debug-Tue_Aug_19_07_17_16_2025.log)

**Comment by cagnulein** [comment]
got the issue, i forgot to add the filter to the manifest, new one is
building https://github.com/cagnulein/qdomyos-zwift/actions/runs/17071404754

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mar 19 ago 2025 alle ore 14:20 Matthew Van Zante <
***@***.***> ha scritto:

**Comment by CodingDutchman** [comment]
[debug-Wed_Aug_27_06_52_56_2025.log](https://github.com/user-attachments/files/22006276/debug-Wed_Aug_27_06_52_56_2025.log)

**Comment by cagnulein** [comment]
thanks @CodingDutchman  could you please run this https://play.google.com/store/apps/details?id=aws.apps.usbDeviceEnumerator&hl=it with the rower connected and send me a screenshot?

**Comment by cagnulein** [comment]
@CodingDutchman Any news?

**Comment by cagnulein** [comment]
@CodingDutchman ??

**Comment by CodingDutchman** [comment]
I'm sorry, it's been a busy month. I will try to remember to try this out
tonight.

**Comment by cagnulein** [comment]
No problem, take your time :)


Il giorno lun 6 ott 2025 alle 18:15 Matthew Van Zante <
***@***.***> ha scritto:

**Comment by CodingDutchman** [comment]
I finally remembered to run the USB info app 

Device Info 
Device Path: /dev/bus/usb/001/002
Device Class: Communication Device (0x2)
Vendor ID:  04d8
Vendor Name (reported):  Microchip Technology Inc.
Vendor Name (from DB):  Microchip Technology, Inc.
Product ID:  000a
Product Name (reported):  CDC RS-232: WR-S4.2
Product Name (from DB):  CDC RS-232 Emulation Demo

Interface #0 
ID:  0
Name:  null
Alternate Setting: 0
Class: Communication Device (0x2)
Subclass: Unknown (0x2)
Protocol: 1
Endpoint: #0
Address        : 0x82 (10000010)
Number         : 2
Direction      : Inbound (0x80)
Type           : Interrupt (0x3)
Poll Interval  : 2
Max Packet Size: 8
Attributes     : 00000011
 
Interface #1 
ID:  1
Name:  null
Alternate Setting: 0
Class: Communication Device Class (CDC) (0xa)
Subclass: Unknown (0x0)
Protocol: 0
Endpoint: #0
Address        : 0x03 (00000011)
Number         : 3
Direction      : Outbound (0x0)
Type           : Bulk (0x2)
Poll Interval  : 0
Max Packet Size: 64
Attributes     : 00000010
Endpoint: #1
Address        : 0x83 (10000011)
Number         : 3
Direction      : Inbound (0x80)
Type           : Bulk (0x2)
Poll Interval  : 0
Max Packet Size: 64
Attributes     : 00000010

Configuration #0 
ID:  1
Name:  
Max Power:  20
Self Powered: true
Remote Wakeup: false

**Comment by cagnulein** [comment]
thanks! created a new version
https://github.com/cagnulein/qdomyos-zwift/actions/runs/19900015638

let me know!

Roberto Viola

I sometimes trade time with my daughter to help. If this was valuable,
please support my time:
https://buymeacoffee.com/cagnulein
https://www.patreon.com/cagnulein/join
https://paypal.me/cagnulein

Software engineer and open source enthusiast, QZ Creator
http://robertoviola.cloud
http://qzfitness.com/


Il giorno mer 3 dic 2025 alle ore 15:57 Matthew Van Zante <
***@***.***> ha scritto:

**Comment by 42nately** [comment]
Hi. I have a Waterrower with an S4 without the com module and am interested in getting the rowing data to your app via usb cord. Happy to help test or provide debug logs if you are interested in working on this. Best regards

**Comment by cagnulein** [comment]
@42nately 

Sure!

https://github.com/cagnulein/qdomyos-zwift/actions/runs/28277332546


Google is very slow in these days, reviewing the app on the store, even the beta ones. For this reason, in order to check right now if the patch that I did is right, you can use the android build in the link (check at the bottom of the page in about 1 hour). In order to test it you need first to remove the current QZ version on your phone, install the one that you downloaded.
This version is a 15 minutes trial (you can restart it as many times as you want) and I can unlock it if you want, send me an email to roberto.viola83@gmail.com mentioning this ticket and that you are on android.
Let me know if you have any questions

**Comment by 42nately** [comment]
Thank you. I look forward to trying the next test build.

**Comment by cagnulein** [comment]
this https://github.com/cagnulein/qdomyos-zwift/actions/runs/28277332546/artifacts/7920907792

**Comment by 42nately** [comment]
Hi I tried it earlier today. I am using an older android 12 phone because it has native ant+. I have other android phones. In settings I checked the box for waterrower usb, the S4 monitor woke up but I did not see any data flowing into the app. I can collect a debug file. Please let me know what else I can do to help. Best regards

**Comment by cagnulein** [comment]
Yes please share a debug log
https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F


Roberto Viola

I sometimes trade time with my daughter to help. If this was valuable,
please support my time:
https://buymeacoffee.com/cagnulein
https://www.patreon.com/cagnulein/join
https://paypal.me/cagnulein

Software engineer and open source enthusiast, QZ Creator
http://robertoviola.cloud
http://qzfitness.com/

Il giorno mer 1 lug 2026 alle 07:27 42nately ***@***.***> ha
scritto:

**Comment by 42nately** [comment]
[debug-Wed_Jul_1_10_26_04_2026\[1\].log](https://github.com/user-attachments/files/29562066/debug-Wed_Jul_1_10_26_04_2026.1.log)

**Comment by 42nately** [comment]
Hi, for that debug test I saw no data flowing into the QZ app.

**Comment by cagnulein** [comment]
I saw that you have the fake rower setting enabled under the experimental
settings. Must be disabled
Let me know and share a fresh debug log then
Thanks


Roberto Viola

I sometimes trade time with my daughter to help. If this was valuable,
please support my time:
https://buymeacoffee.com/cagnulein
https://www.patreon.com/cagnulein/join
https://paypal.me/cagnulein

Software engineer and open source enthusiast, QZ Creator
http://robertoviola.cloud
http://qzfitness.com/

Il giorno mer 1 lug 2026 alle 19:47 42nately ***@***.***> ha
scritto:

**Comment by 42nately** [comment]
[debug-Wed_Jul_1_10_54_21_2026\[1\].log](https://github.com/user-attachments/files/29562571/debug-Wed_Jul_1_10_54_21_2026.1.log)

**Comment by cagnulein** [comment]
Stupid question : was the rower connected via USB to this device?

**Comment by 42nately** [comment]
[debug-Wed_Jul_1_11_19_50_2026\[1\].log](https://github.com/user-attachments/files/29563286/debug-Wed_Jul_1_11_19_50_2026.1.log) here is another. yes, connected via usb. yes, with setting checked to use s4 usb. phone does prompt when i plug in the usb cable so it looks like the app sees the phone but then breaks....

**Comment by cagnulein** [comment]
Got it, I'm checking


Roberto Viola

I sometimes trade time with my daughter to help. If this was valuable,
please support my time:
https://buymeacoffee.com/cagnulein
https://www.patreon.com/cagnulein/join
https://paypal.me/cagnulein

Software engineer and open source enthusiast, QZ Creator
http://robertoviola.cloud
http://qzfitness.com/

Il giorno mer 1 lug 2026 alle 20:29 42nately ***@***.***> ha
scritto:

**Comment by cagnulein** [comment]
ok i reworked the serial part, let's see if it's better https://github.com/cagnulein/qdomyos-zwift/actions/runs/28540609662
@42nately

**Comment by 42nately** [comment]
[debug-Wed_Jul_1_13_21_35_2026\[1\].log](https://github.com/user-attachments/files/29572553/debug-Wed_Jul_1_13_21_35_2026.1.log)

**Comment by 42nately** [comment]
looks like some progress, but i dont see data flowing during the app. best regards

**Comment by cagnulein** [comment]
That's great! New patch here https://github.com/cagnulein/qdomyos-zwift/actions/runs/28565027574

**Comment by cagnulein** [comment]
Sorry new one https://github.com/cagnulein/qdomyos-zwift/actions/runs/28565625320

**Comment by 42nately** [comment]
[debug-Wed_Jul_1_22_17_38_2026\[1\].log](https://github.com/user-attachments/files/29583507/debug-Wed_Jul_1_22_17_38_2026.1.log)

**Comment by cagnulein** [comment]
I can see the matrix now moving, isn't it?

**Comment by 42nately** [comment]
The logs show movement, but the app doesnt lock onto the rower to show data while actually rowing. i cannot select the S4/usb connection as the ftms rower.... Any thoughts?

**Comment by cagnulein** [comment]
Got it, let me fix it. We are very near!

**Comment by 42nately** [comment]
Sounds good. Looking forward to the next round. Best regards

**Comment by cagnulein** [comment]
Done I'm confident
https://github.com/cagnulein/qdomyos-zwift/actions/runs/28572142575


Roberto Viola

I sometimes trade time with my daughter to help. If this was valuable,
please support my time:
https://buymeacoffee.com/cagnulein
https://www.patreon.com/cagnulein/join
https://paypal.me/cagnulein

Software engineer and open source enthusiast, QZ Creator
http://robertoviola.cloud
http://qzfitness.com/

Il giorno gio 2 lug 2026 alle 08:46 42nately ***@***.***> ha
scritto:

**Comment by 42nately** [comment]
[debug-Thu_Jul_2_10_13_56_2026\[1\].log](https://github.com/user-attachments/files/29608031/debug-Thu_Jul_2_10_13_56_2026.1.log). thanks. unfortunately on this one i dont see data flowing in the background and the app does not initialize.

**Comment by cagnulein** [comment]
unfortunately the log is truncated. Could you please try again?


Roberto Viola

I sometimes trade time with my daughter to help. If this was valuable,
please support my time:
https://buymeacoffee.com/cagnulein
https://www.patreon.com/cagnulein/join
https://paypal.me/cagnulein

Software engineer and open source enthusiast, QZ Creator
http://robertoviola.cloud
http://qzfitness.com/

Il giorno gio 2 lug 2026 alle 19:25 42nately ***@***.***> ha
scritto:

**Comment by 42nately** [comment]
[debug-Thu_Jul_2_10_42_03_2026\[1\].log](https://github.com/user-attachments/files/29608745/debug-Thu_Jul_2_10_42_03_2026.1.log) summary shows 0 after ending.....

**Comment by cagnulein** [comment]
Still corrupted :( are you closing qz before sending it?
Let me know


Roberto Viola

I sometimes trade time with my daughter to help. If this was valuable,
please support my time:
https://buymeacoffee.com/cagnulein
https://www.patreon.com/cagnulein/join
https://paypal.me/cagnulein

Software engineer and open source enthusiast, QZ Creator
http://robertoviola.cloud
http://qzfitness.com/

Il giorno gio 2 lug 2026 alle 19:48 42nately ***@***.***> ha
scritto:

**Comment by 42nately** [comment]
[debug-Thu_Jul_2_12_04_28_2026\[1\].log](https://github.com/user-attachments/files/29611142/debug-Thu_Jul_2_12_04_28_2026.1.log) cleared log and reinstalled. i see data in the app in real  time! but distance is way to hi and watts flash on and off.....

**Comment by cagnulein** [comment]
Fixed both!
https://github.com/cagnulein/qdomyos-zwift/actions/runs/28615724717
We will need to understand why you needed to reset the app
Let me know!


Roberto Viola

I sometimes trade time with my daughter to help. If this was valuable,
please support my time:
https://buymeacoffee.com/cagnulein
https://www.patreon.com/cagnulein/join
https://paypal.me/cagnulein

Software engineer and open source enthusiast, QZ Creator
http://robertoviola.cloud
http://qzfitness.com/

Il giorno gio 2 lug 2026 alle 21:14 42nately ***@***.***> ha
scritto:

**Comment by 42nately** [comment]
[debug-Thu_Jul_2_13_02_54_2026\[1\].log](https://github.com/user-attachments/files/29612442/debug-Thu_Jul_2_13_02_54_2026.1.log) Looking good! Watts, stroke rate and odometer match. Couple of small issues. Stroke count shows 0. In using Ant+ to connect phone to watch, distance shows 0.

**Comment by cagnulein** [comment]
That's great! Both fixed
https://github.com/cagnulein/qdomyos-zwift/actions/runs/28634960576


Roberto Viola

I sometimes trade time with my daughter to help. If this was valuable,
please support my time:
https://buymeacoffee.com/cagnulein
https://www.patreon.com/cagnulein/join
https://paypal.me/cagnulein

Software engineer and open source enthusiast, QZ Creator
http://robertoviola.cloud
http://qzfitness.com/

Il giorno gio 2 lug 2026 alle 22:12 42nately ***@***.***> ha
scritto:

**Comment by 42nately** [comment]
Data looks great in the app, including stroke count. But, the app always starts at the wizard/start page before beginning so user has to hit the "start" button and then select "im fine" before splash screen is available. Regarding distance in Ant+ broadcast, it still shows as 0 on garmin device. From the log, it looks like Ant+ broadcasts show distance stuck at 0x00, even though the app's internal tracker (TemplateInfoSender) correctly logs a growing rowing distance and BikeTransmitterController isn't reading that tracked value when building the TX payload....

[debug-Fri_Jul_3_10_41_49_2026\[1\].log](https://github.com/user-attachments/files/29644783/debug-Fri_Jul_3_10_41_49_2026.1.log)

**Comment by cagnulein** [comment]
For the wizard select the wifi device there, it should be fine. I'm
checking the ant+ now


Roberto Viola

I sometimes trade time with my daughter to help. If this was valuable,
please support my time:
https://buymeacoffee.com/cagnulein
https://www.patreon.com/cagnulein/join
https://paypal.me/cagnulein

Software engineer and open source enthusiast, QZ Creator
http://robertoviola.cloud
http://qzfitness.com/

Il giorno ven 3 lug 2026 alle 20:18 42nately ***@***.***> ha
scritto:

**Comment by 42nately** [comment]
I selected/set WIFI, but still land on start page and have to press start and hit i'm fine for app to get to the tile screen.

**Comment by cagnulein** [comment]
Hah Ok got it


Roberto Viola

I sometimes trade time with my daughter to help. If this was valuable,
please support my time:
https://buymeacoffee.com/cagnulein
https://www.patreon.com/cagnulein/join
https://paypal.me/cagnulein

Software engineer and open source enthusiast, QZ Creator
http://robertoviola.cloud
http://qzfitness.com/

Il giorno ven 3 lug 2026 alle 20:40 42nately ***@***.***> ha
scritto:

**Comment by cagnulein** [comment]
Actually the distance is not always 0, is 0 when it's a multiple of 256. On
the garmin watch which sensor are you connecting?


Roberto Viola

I sometimes trade time with my daughter to help. If this was valuable,
please support my time:
https://buymeacoffee.com/cagnulein
https://www.patreon.com/cagnulein/join
https://paypal.me/cagnulein

Software engineer and open source enthusiast, QZ Creator
http://robertoviola.cloud
http://qzfitness.com/

Il giorno ven 3 lug 2026 alle 21:05 cagnulein ***@***.***> ha
scritto:

**Comment by 42nately** [comment]
on garmin, it appears as power and smart trainer. i tried it as a smart trainer and it showed 0 and both and it showed 0.

**Comment by cagnulein** [comment]
I thought was only the distance wrong on ant+, isn't it?
Or all the metrics are 0 on all the profiles?


Roberto Viola

I sometimes trade time with my daughter to help. If this was valuable,
please support my time:
https://buymeacoffee.com/cagnulein
https://www.patreon.com/cagnulein/join
https://paypal.me/cagnulein

Software engineer and open source enthusiast, QZ Creator
http://robertoviola.cloud
http://qzfitness.com/

Il giorno ven 3 lug 2026 alle 21:27 42nately ***@***.***> ha
scritto:

**Comment by 42nately** [comment]
Sorry for any confusion. I am seeing 0 for distance on garmin via ant+. other metrics are there. Could garmin/ant+ receiver be ignoring the distance data because the capabilities field currently shows 0x00?

**Comment by cagnulein** [comment]
I'm trying here to send as a rower
https://github.com/cagnulein/qdomyos-zwift/actions/runs/28681465308
Wizard page also fixed
Let me know


Roberto Viola

I sometimes trade time with my daughter to help. If this was valuable,
please support my time:
https://buymeacoffee.com/cagnulein
https://www.patreon.com/cagnulein/join
https://paypal.me/cagnulein

Software engineer and open source enthusiast, QZ Creator
http://robertoviola.cloud
http://qzfitness.com/

Il giorno ven 3 lug 2026 alle 21:56 42nately ***@***.***> ha
scritto:

**Comment by 42nately** [comment]
Gave it a quick test and it's looking very good! Could you provide unlock for a longer test? Best regards

**Comment by 42nately** [comment]
Hello. Its looking good! My licensed android copy of your app is @ ***@***.*** from my iPhoneOn Jul 2, 2026, at 11:56 AM, Roberto Viola ***@***.***> wrote:﻿cagnulein left a comment (cagnulein/qdomyos-zwift#3059)
Still corrupted :( are you closing qz before sending it?

Let me know





Roberto Viola



I sometimes trade time with my daughter to help. If this was valuable,

please support my time:

https://buymeacoffee.com/cagnulein

https://www.patreon.com/cagnulein/join

https://paypal.me/cagnulein



Software engineer and open source enthusiast, QZ Creator

http://robertoviola.cloud

http://qzfitness.com/



Il giorno gio 2 lug 2026 alle 19:48 42nately ***@***.***> ha

scritto:

**Comment by cagnulein** [comment]
That's amazing! I can't see your full email. Send me it to Roberto.viola83
at Gmail.com
Thanks


Roberto Viola

I sometimes trade time with my daughter to help. If this was valuable,
please support my time:
https://buymeacoffee.com/cagnulein
https://www.patreon.com/cagnulein/join
https://paypal.me/cagnulein

Software engineer and open source enthusiast, QZ Creator
http://robertoviola.cloud
http://qzfitness.com/

Il giorno ven 3 lug 2026 alle 23:33 42nately ***@***.***> ha
scritto:

**Comment by 42nately** [comment]
Tried it with ant+ to garmin device and ble to ios device running EXR. Speed was jittery and watts somewhat jittery. But overall stable and working!

[mini_debug.txt](https://github.com/user-attachments/files/29769755/mini_debug.txt)

**Comment by cagnulein** [comment]
That's great! Could you please share the full log so I can check it?
Thanks


Roberto Viola

I sometimes trade time with my daughter to help. If this was valuable,
please support my time:
https://buymeacoffee.com/cagnulein
https://www.patreon.com/cagnulein/join
https://paypal.me/cagnulein

Software engineer and open source enthusiast, QZ Creator
http://robertoviola.cloud
http://qzfitness.com/

Il giorno mer 8 lug 2026 alle 00:44 42nately ***@***.***> ha
scritto:

**Comment by 42nately** [comment]
[debug-Tue_Jul_7_14_05_31_2026.zip](https://github.com/user-attachments/files/29783338/debug-Tue_Jul_7_14_05_31_2026.zip)

**Comment by cagnulein** [comment]
One question you see the speed and power glitches also in qz or only on
ant+?


Roberto Viola

I sometimes trade time with my daughter to help. If this was valuable,
please support my time:
https://buymeacoffee.com/cagnulein
https://www.patreon.com/cagnulein/join
https://paypal.me/cagnulein

Software engineer and open source enthusiast, QZ Creator
http://robertoviola.cloud
http://qzfitness.com/

Il giorno mer 8 lug 2026 alle 06:25 42nately ***@***.***> ha
scritto:

**Comment by 42nately** [comment]
Yes. In the app. So the speed will jump up and down. No smoothing or averaging. Power jumps around, but not as much.

**Comment by cagnulein** [comment]
Fixed speed
https://github.com/cagnulein/qdomyos-zwift/actions/runs/28923782408

For the power enable the power average setting in the advanced settings
Let me know


Roberto Viola

I sometimes trade time with my daughter to help. If this was valuable,
please support my time:
https://buymeacoffee.com/cagnulein
https://www.patreon.com/cagnulein/join
https://paypal.me/cagnulein

Software engineer and open source enthusiast, QZ Creator
http://robertoviola.cloud
http://qzfitness.com/

Il giorno mer 8 lug 2026 alle 08:24 42nately ***@***.***> ha
scritto:

**Comment by 42nately** [comment]
Hi. Speed is looking smooth!Best regardsSent from my iPhoneOn Jul 7, 2026, at 11:58 PM, Roberto Viola ***@***.***> wrote:﻿cagnulein left a comment (cagnulein/qdomyos-zwift#3059)
Fixed speed

https://github.com/cagnulein/qdomyos-zwift/actions/runs/28923782408



For the power enable the power average setting in the advanced settings

Let me know





Roberto Viola



I sometimes trade time with my daughter to help. If this was valuable,

please support my time:

https://buymeacoffee.com/cagnulein

https://www.patreon.com/cagnulein/join

https://paypal.me/cagnulein



Software engineer and open source enthusiast, QZ Creator

http://robertoviola.cloud

http://qzfitness.com/



Il giorno mer 8 lug 2026 alle 08:24 42nately ***@***.***> ha

scritto:

**Comment by cagnulein** [comment]
Perfect any other issues? Could I merge it?


Roberto Viola

I sometimes trade time with my daughter to help. If this was valuable,
please support my time:
https://buymeacoffee.com/cagnulein
https://www.patreon.com/cagnulein/join
https://paypal.me/cagnulein

Software engineer and open source enthusiast, QZ Creator
http://robertoviola.cloud
http://qzfitness.com/

Il giorno gio 9 lug 2026 alle 08:26 42nately ***@***.***> ha
scritto:

**Comment by 42nately** [comment]
Yes! Lots of Waterrower S4 users out there who can benefit from your excellent app. There were some other S4 to USB phone apps but they are no longer being developed and none of them converted workout in realtime to bluetooth or Ant+ like yours.Sent from my iPhoneOn Jul 8, 2026, at 11:38 PM, Roberto Viola ***@***.***> wrote:﻿cagnulein left a comment (cagnulein/qdomyos-zwift#3059)
Perfect any other issues? Could I merge it?





Roberto Viola



I sometimes trade time with my daughter to help. If this was valuable,

please support my time:

https://buymeacoffee.com/cagnulein

https://www.patreon.com/cagnulein/join

https://paypal.me/cagnulein



Software engineer and open source enthusiast, QZ Creator

http://robertoviola.cloud

http://qzfitness.com/



Il giorno gio 9 lug 2026 alle 08:26 42nately ***@***.***> ha

scritto:

**Comment by cagnulein** [comment]
Amazing! Share the good news!


Roberto Viola

I sometimes trade time with my daughter to help. If this was valuable,
please support my time:
https://buymeacoffee.com/cagnulein
https://www.patreon.com/cagnulein/join
https://paypal.me/cagnulein

Software engineer and open source enthusiast, QZ Creator
http://robertoviola.cloud
http://qzfitness.com/

Il giorno gio 9 lug 2026 alle 20:34 42nately ***@***.***> ha
scritto:

**Comment by cagnulein** [comment]
ok i'm ready to merge it, could you please check this build https://github.com/cagnulein/qdomyos-zwift/actions/runs/29089549449
nothing should be changed but let's do a final check
thanks!

**Comment by 42nately** [comment]
Hi. The app is working well. Any thoughts on when the S4 USB support will be merged into the app?Best regardsSent from my iPhoneOn Jul 10, 2026, at 4:30 AM, Roberto Viola ***@***.***> wrote:﻿cagnulein left a comment (cagnulein/qdomyos-zwift#3059)
ok i'm ready to merge it, could you please check this build https://github.com/cagnulein/qdomyos-zwift/actions/runs/29089549449
nothing should be changed but let's do a final check
thanks!

**Comment by cagnulein** [comment]
Hi, that's great. sure i can merge it. Let me do now
