### ISSUE TITLE
[BUG] Lifesmart TM6500 PowerTouch Treadmill doesn't Automatically Incline in Zwift

### ISSUE THREAD

**Issue by trailrunners** [cagnulein/qdomyos-zwift#4045]
**Describe the bug**
The Lifesmart TM6500 PowerTouch Treadmill does not automatically incline when connected to Zwift.  TM6500 connects to QZ and incline and speed can be controlled using the QZ tiles.  However, when entering the game and running a route, incline is not automatically controlled with QZ.  In Zwift, QZ is connected with iPhone 17 iOs.

**To Reproduce**
1. Turn on TM6500 trreadmill
2. Connect treadmill to QZ with iPhone 17 using iOS. 
3. Go to Zwift
4. Connect Zwift to iPhone 17 iOS
5. Go to route to start run
6. Start treadmill and start running
7. Automatic incline does not work in Zwift using QZ

**Expected behavior**
When I start running a route in Zwift, I am expecting that incline will be controlled automatically with QZ app.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: iPhone 17 Pro
 - OS: iOS
 - Version 26.1

[debug-Sun_Dec_28_21_58_30_2025.log](https://github.com/user-attachments/files/24372020/debug-Sun_Dec_28_21_58_30_2025.log)

**Append a debug log**

 Follow this guide https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
  
  
**Additional context**

**Comment by cagnulein** [comment]
The problem is that you have the zwift inclination gain to 0 in the
advanced settings. Set it to 0.5

Roberto Viola

I sometimes trade time with my daughter to help. If this was valuable,
please support my time:
https://buymeacoffee.com/cagnulein
https://www.patreon.com/cagnulein/join
https://paypal.me/cagnulein

Software engineer and open source enthusiast, QZ Creator
http://robertoviola.cloud
http://qzfitness.com/


Il giorno lun 29 dic 2025 alle 19:08 trailrunners ***@***.***>
ha scritto:

**Comment by trailrunners** [comment]
This is great, thank you!

**Comment by trailrunners** [comment]
This is great, thank you!

**Comment by trailrunners** [comment]
I set inclination gain to 0.5 and it seems to be working but takes a while to start matching the inclination on Zwift, seems to not be entirely accurate with the inclination, and does not go negative inclination.  My treadmill does go down to -3%.  Will QZ adjust inclination to negative percentage?


> The problem is that you have the zwift inclination gain to 0 in the
> advanced settings. Set it to 0.5
> 
> Roberto Viola
> 
> I sometimes trade time with my daughter to help. If this was valuable,
> please support my time:
> https://buymeacoffee.com/cagnulein
> https://www.patreon.com/cagnulein/join
> https://paypal.me/cagnulein
> 
> Software engineer and open source enthusiast, QZ Creator
> http://robertoviola.cloud
> http://qzfitness.com/
> 
> 
> Il giorno lun 29 dic 2025 alle 19:08 trailrunners ***@***.***>
> ha scritto:
> […](#)

**Comment by cagnulein** [comment]
Yes Qz will use the inclination one too, share a debug log maybe I have to
enable for your treadmill

For the inclination consider that zwift sends it every 5 seconds and send
the actual values but it shows the average.

Let me know

Roberto Viola

I sometimes trade time with my daughter to help. If this was valuable,
please support my time:
https://buymeacoffee.com/cagnulein
https://www.patreon.com/cagnulein/join
https://paypal.me/cagnulein

Software engineer and open source enthusiast, QZ Creator
http://robertoviola.cloud
http://qzfitness.com/


Il giorno mar 30 dic 2025 alle 02:33 trailrunners ***@***.***>
ha scritto:

**Comment by trailrunners** [comment]
Hello Roberto,

Getting back to the incline/decline function of the Lifesmart TM6500 PowerTouch.  The incline appears to working pretty well, but it will not go into DECLINE along with what's shown in Zwift.  Please see the attached debug log. I think it's the correct log and should show where the machine does not decline along with Zwift.  I have another log if this one doesn't work.  Thanks!

[debug-Fri_Jan_9_11_48_27_2026.log](https://github.com/user-attachments/files/24533593/debug-Fri_Jan_9_11_48_27_2026.log)

**Comment by trailrunners** [comment]
Hello Roberto,

Thank you again for all of your help.  I sent a debug log to our Github
message.  Let me know if you need anything else.

Thanks!
Andy

**Comment by cagnulein** [comment]
Thanks I will check it ASAP

Roberto Viola

I sometimes trade time with my daughter to help. If this was valuable,
please support my time:
https://buymeacoffee.com/cagnulein
https://www.patreon.com/cagnulein/join
https://paypal.me/cagnulein

Software engineer and open source enthusiast, QZ Creator
http://robertoviola.cloud
http://qzfitness.com/


Il giorno ven 9 gen 2026 alle 19:53 trailrunners ***@***.***>
ha scritto:

**Comment by cagnulein** [comment]
fixed! send me an email to roberto.viola83 at gmail.com indicating this ticket and if you are on android or iOS. Thanks

**Comment by trailrunners** [comment]
Thank you so much for all of your work! I finally tried the treadmill with Zwift and it still did not go into decline along with what was shown on Zwift.  When it was negative percent the treadmill just went to 0 and stayed there, it did not go to negative.  Is there a setting that I am still missing to allow the treadmill to go into decline?  Thank you!

**Comment by cagnulein** [comment]
Could you please share a fresh log so I can check if my patch went fine?

**Comment by trailrunners** [comment]
Please see the most recent debug log.  Incline is working, but treadmill is not going into decline.  The Lifesmart TM6500 goes to a -3% maximum decline.  Thank you!

[debug-Mon_Jan_12_10_40_11_2026.log](https://github.com/user-attachments/files/24569490/debug-Mon_Jan_12_10_40_11_2026.log)

**Comment by trailrunners** [comment]
Thank you, I shared the debug file on Github

**Comment by cagnulein** [comment]
Hi the problem is the app is still on the old version. Did you update the
app from the apple email that I sent you?

Roberto Viola

I sometimes trade time with my daughter to help. If this was valuable,
please support my time:
https://buymeacoffee.com/cagnulein
https://www.patreon.com/cagnulein/join
https://paypal.me/cagnulein

Software engineer and open source enthusiast, QZ Creator
http://robertoviola.cloud
http://qzfitness.com/


Il giorno lun 12 gen 2026 alle 17:58 trailrunners ***@***.***>
ha scritto:

**Comment by trailrunners** [comment]
Hi Roberto,

My QZ app is version 2.19.2. I don't see a new version and did not see an
apple email that you sent.  I will check again.

Thank you,
Andy

**Comment by cagnulein** [comment]
> fixed! send me an email to roberto.viola83 at gmail.com indicating this ticket and if you are on android or iOS. Thanks


Did you send me an email 2 days ago about this? Consider that when you are answering this you are not sending me a mail but instead posting directly on github 

I need an email directly so I can see your email to send you the version

I hope it's clear

**Comment by trailrunners** [comment]
I did not send you an email directly.  I will do so now.

**Comment by cagnulein** [comment]
Ok, thanks.


Il giorno lun 12 gen 2026 alle 18:29 trailrunners ***@***.***>
ha scritto:

**Comment by trailrunners** [comment]
Wow!! It works now for incline and decline! I don't know how you do it, but it is amazing!  Thank you!

I'm not sure if this is possible, but I thought I'd check.  The incline on the TM6500 seems relatively slow.  Is there any way the incline adjustments could be made faster on the machine?  I just thought I'd check.  Thank you again for all of your amazing help.

**Comment by cagnulein** [comment]
That's great! Do you mean the motor of the inclination is slow?
Please remember to rate the app on the store if you like it, it means a lot
to me! Thanks!

Roberto Viola

I sometimes trade time with my daughter to help. If this was valuable,
please support my time:
https://buymeacoffee.com/cagnulein
https://www.patreon.com/cagnulein/join
https://paypal.me/cagnulein

Software engineer and open source enthusiast, QZ Creator
http://robertoviola.cloud
http://qzfitness.com/


Il giorno lun 12 gen 2026 alle 20:31 trailrunners ***@***.***>
ha scritto:

**Comment by trailrunners** [comment]
I will definitely rate the app on the store!  Yes, the motor is relatively
slow with incline adjustments.  It does however have a 4HP motor which
should be more than adequate for quicker adjustments.  I guess I am
wondering if the machine is being programmed to adjust the incline slowly
and if that is something that could be adjusted?

**Comment by cagnulein** [comment]
Unfortunately I can't do anything about it :( I can only sends commands :(

Roberto Viola

I sometimes trade time with my daughter to help. If this was valuable,
please support my time:
https://buymeacoffee.com/cagnulein
https://www.patreon.com/cagnulein/join
https://paypal.me/cagnulein

Software engineer and open source enthusiast, QZ Creator
http://robertoviola.cloud
http://qzfitness.com/


Il giorno lun 12 gen 2026 alle 20:42 trailrunners ***@***.***>
ha scritto:

**Comment by trailrunners** [comment]
No worries at all, just thought I'd check.  Thank you again for all the
help!  Just posted a 5 star review in the app store.

**Comment by cagnulein** [comment]
Awesome, thank you so much!


Il giorno lun 12 gen 2026 alle 20:50 trailrunners ***@***.***>
ha scritto:
