### ISSUE TITLE
[BUG] Unable to load settings from "Other folders"

### ISSUE THREAD

**Issue by grantland** [cagnulein/qdomyos-zwift#722]
**Describe the bug**
Loading settings using "Other folders" and my Downloads folder doesn't work

**To Reproduce**
1. Go to Settings > Import
2. Tap "Other folders"
3. Select a qzs file from my Downloads folder

**Expected behavior**
The settings loads

**Actual behavior**
The settings don't load

**Screenshots**
n/a

**Smartphone (please complete the following information):**
 - Device: emulator, Pixel 4, Fire HD 8
 - OS: Android
 - Version: master

**Append a debug log**
```
D qDomyos-Zwift: qml: You chose: content://com.android.providers.downloads.documents/document/raw%3A%2Fstorage%2Femulated%2F0%2FDownload%2Fgrantland.qzs
D qDomyos-Zwift: homeform::loadSettings QUrl("content://com.android.providers.downloads.documents/document/raw%3A%2Fstorage%2Femulated%2F0%2FDownload%2Fgrantland.qzs")
```
  
**Additional context**
* I added debug logs to output the keys in the settings2Load and it didn't output anything
* I think there might be an issue with QT and reading from Android Content Providers, but I'm not too familiar

**Comment by cagnulein** [comment]
@p3g4asus could you help me on this?

**Comment by p3g4asus** [comment]
@cagnulein I will work on this!

**Comment by p3g4asus** [comment]
I implemented this request. Please look at [this video](https://user-images.githubusercontent.com/3275734/158054018-4ac147a6-d91b-4f89-8295-e269e05fb3a3.mp4).

@grantland  Please test it: You can find it [here](https://github.com/p3g4asus/qdomyos-zwift/tree/share_send_recv)

**Comment by cagnulein** [comment]
@grantland any news?

**Comment by cagnulein** [comment]
@grantland Hello?

**Comment by grantland** [comment]
@p3g4asus it works when importing a file by attempting to open a `.qzs` file directly but it still doesn't work when attempting to open a file from "Other Folders" in the import menu. I think it's confusing that "Other Folders" doesn't work, could that be fixed or at the very least be removed on Android?

**Comment by grantland** [comment]
Another issue is that QZ is trying to open files of other extensions such as `.pdf`s

**Comment by p3g4asus** [comment]
> @p3g4asus it works when importing a file by attempting to open a `.qzs` file directly but it still doesn't work when attempting to open a file from "Other Folders" in the import menu. I think it's confusing that "Other Folders" doesn't work, could that be fixed or at the very least be removed on Android?
You are right. That button should be removed as it is not working still. I will remove it in a new commit

> Another issue is that QZ is trying to open files of other extensions such as `.pdf`s

Absolutely right but I tryed to filter by extension the intent sending on android and it appears to be not working / not possible. The only thing that can be done is to display an error message when one tryes to open a non-qzs file.

**Comment by grantland** [comment]
I think you might need to utilize `intent-filter` on a receiving `Activity` and ensure that the `Activity` is `exported`

References:
* https://stackoverflow.com/questions/1733195/android-intent-filter-for-a-particular-file-extension
* https://developer.android.com/about/versions/12/behavior-changes-12#exported

Also posted here: https://github.com/p3g4asus/qdomyos-zwift/commit/815b94809acec33297892be7e65d26d91fe03974#r71729561

**Comment by p3g4asus** [comment]
The problem is that these filters work only when data is shared using the "file" scheme (`<data android:scheme="file" />`). On modern Android versions data is shared always with "content". scheme and thus can be filtered only by using mimeType which is effective only if the data file has a known extension (video, images, documents, json, etc.).

In the last commit the Load Settings should be completely fixed (including Other folders button)

**Comment by cagnulein** [comment]
@grantland any news?

**Comment by grantland** [comment]
So I can see the file picker show up when I select "Other Folders", but I can't test fully since the share intent fix from #723 no longer works.
